@generated
Call dependencies
{
  "Function{access_path.indexes_and_attributes}": [
    "Function{pysa._test_sink}", "Function{pysa._test_source}",
    "Method{access_path.SpecialDict.__getitem__}",
    "Method{access_path.SpecialDict.__init__}",
    "Method{builtins.object.__new__}"
  ],
  "Function{access_path.indexes_are_attributes_for___dict__}": [
    "Function{pysa._test_sink}", "Function{pysa._test_source}",
    "Method{builtins.dict.__getitem__}", "Method{builtins.object.__init__}",
    "Method{builtins.object.__new__}"
  ],
  "Function{access_path.indexes_are_strings}": [
    "Function{pysa._test_sink}", "Function{pysa._test_source}",
    "Method{builtins.dict.__getitem__}", "Method{builtins.dict.__setitem__}"
  ],
  "Function{access_path.issue_positional_and_variadic}": [
    "Function{access_path.positional_and_variadic1}",
    "Function{access_path.positional_and_variadic2}",
    "Function{pysa._test_source}"
  ],
  "Function{access_path.positional_and_variadic1}": [
    "Function{pysa._test_sink}"
  ],
  "Function{access_path.positional_and_variadic2}": [
    "Function{pysa._test_sink}"
  ],
  "Method{access_path.SpecialDict.__getitem__}": [
    "Method{builtins.dict.get}"
  ]
}