@generated
Call dependencies
{
  "Function{add_feature_to_argument.add_feature_to_argument_does_not_propagate_inferred_tito_feature}": [
    "Function{add_feature_to_argument.add_feature_to_first}",
    "Function{add_feature_to_argument.tito_with_feature}"
  ],
  "Function{add_feature_to_argument.add_feature_to_argument_does_not_propagate_inferred_type_breadcrumb}": [
    "Function{add_feature_to_argument.add_feature_to_first}",
    "Function{add_feature_to_argument.tito_returns_int}"
  ],
  "Function{add_feature_to_argument.add_feature_to_argument_does_not_propagate_inferred_via_breadcrumb}": [
    "Function{add_feature_to_argument.add_feature_to_first}",
    "Function{add_feature_to_argument.add_via_breadcrumb}"
  ],
  "Function{add_feature_to_argument.adds_and_taints}": [
    "Function{add_feature_to_argument.add_feature_to_first}",
    "Function{pysa._test_source}"
  ],
  "Function{add_feature_to_argument.dict_test_add_via_value_of_second}": [
    "Function{add_feature_to_argument.add_via_value_of}",
    "Function{pysa._test_source}"
  ],
  "Function{add_feature_to_argument.propagate_add_feature}": [
    "Function{add_feature_to_argument.add_feature_to_first}"
  ],
  "Function{add_feature_to_argument.propagate_multiple_add_feature}": [
    "Function{add_feature_to_argument.add_feature_to_first}",
    "Function{add_feature_to_argument.add_feature_to_second}",
    "Method{_random.Random.random}", "Method{builtins.float.__gt__}"
  ],
  "Function{add_feature_to_argument.source_add_feature_to_argument_does_not_propagate_inferred_tito_feature}": [
    "Function{add_feature_to_argument.add_feature_to_argument_does_not_propagate_inferred_tito_feature}",
    "Function{pysa._test_source}"
  ],
  "Function{add_feature_to_argument.source_add_feature_to_argument_does_not_propagate_inferred_type_breadcrumb}": [
    "Function{add_feature_to_argument.add_feature_to_argument_does_not_propagate_inferred_type_breadcrumb}",
    "Function{pysa._test_source}"
  ],
  "Function{add_feature_to_argument.source_add_feature_to_argument_does_not_propagate_inferred_via_breadcrumb}": [
    "Function{add_feature_to_argument.add_feature_to_argument_does_not_propagate_inferred_via_breadcrumb}",
    "Function{pysa._test_source}"
  ],
  "Function{add_feature_to_argument.test_add_feature_in_comprehension}": [
    "Function{add_feature_to_argument.add_feature_to_first}",
    "Function{pysa._test_sink}", "Function{pysa._test_source}",
    "Method{builtins.list.__getitem__}", "Method{builtins.list.__iter__}",
    "Method{typing.Iterator.__next__}"
  ],
  "Function{add_feature_to_argument.test_add_feature_to_sink_in_comprehension}": [
    "Function{add_feature_to_argument.add_feature_to_first}",
    "Function{pysa._test_sink}", "Method{builtins.list.__iter__}",
    "Method{typing.Iterator.__next__}"
  ],
  "Function{add_feature_to_argument.test_add_feature_to_sink}": [
    "Function{add_feature_to_argument.add_feature_to_first}",
    "Function{pysa._test_sink}"
  ],
  "Function{add_feature_to_argument.test_add_multiple_feature}": [
    "Function{add_feature_to_argument.propagate_multiple_add_feature}",
    "Function{pysa._test_sink}"
  ],
  "Function{add_feature_to_argument.test_add_via_value_of_second}": [
    "Function{add_feature_to_argument.add_via_value_of}",
    "Function{pysa._test_source}"
  ]
}