@generated
Call dependencies
{
  "Function{add_breadcrumb_to_state.add_breadcrumb_to_state_wrapper}": [
    "Function{add_breadcrumb_to_state.add_breadcrumb_to_state}"
  ],
  "Function{add_breadcrumb_to_state.test_add_breadcrumb_context_manager}": [
    "Function{pysa._test_sink}", "Function{pysa._test_source}",
    "Method{add_breadcrumb_to_state.BreadcrumbOnEnter.__enter__}",
    "Method{add_breadcrumb_to_state.BreadcrumbOnEnter.__init__}",
    "Method{builtins.object.__new__}"
  ],
  "Function{add_breadcrumb_to_state.test_if_issue}": [
    "Function{add_breadcrumb_to_state.add_breadcrumb_to_state}",
    "Function{pysa._test_sink}", "Function{pysa._test_source}"
  ],
  "Function{add_breadcrumb_to_state.test_if_sink_outside_condition}": [
    "Function{add_breadcrumb_to_state.add_breadcrumb_to_state}",
    "Function{pysa._test_sink}"
  ],
  "Function{add_breadcrumb_to_state.test_if_sink_within_condition}": [
    "Function{add_breadcrumb_to_state.add_breadcrumb_to_state}",
    "Function{pysa._test_sink}"
  ],
  "Function{add_breadcrumb_to_state.test_if_source_outside_condition}": [
    "Function{add_breadcrumb_to_state.add_breadcrumb_to_state}",
    "Function{pysa._test_source}"
  ],
  "Function{add_breadcrumb_to_state.test_if_source_within_condition}": [
    "Function{add_breadcrumb_to_state.add_breadcrumb_to_state}",
    "Function{pysa._test_source}"
  ],
  "Function{add_breadcrumb_to_state.test_wrapper}": [
    "Function{add_breadcrumb_to_state.add_breadcrumb_to_state_wrapper}",
    "Function{pysa._test_sink}", "Function{pysa._test_source}"
  ]
}