@generated
Call dependencies
{
  "Function{all_static_fields.return_source_b}": [
    "Method{all_static_fields.C.__init__}", "Method{builtins.object.__new__}"
  ],
  "Function{all_static_fields.return_source_c}": [
    "Method{all_static_fields.C.__init__}", "Method{builtins.object.__new__}"
  ],
  "Function{all_static_fields.return_source_dataclass}": [
    "Method{all_static_fields.Dataclass.__init__}",
    "Method{builtins.object.__new__}"
  ],
  "Function{all_static_fields.return_source_d}": [
    "Method{all_static_fields.D.__init__}", "Method{builtins.object.__new__}"
  ],
  "Function{all_static_fields.return_source_empty}": [
    "Method{all_static_fields.Empty.__init__}",
    "Method{builtins.object.__new__}"
  ],
  "Function{all_static_fields.return_source_regular_class}": [
    "Method{all_static_fields.RegularClass.__init__}",
    "Method{builtins.object.__new__}"
  ],
  "Function{all_static_fields.return_source_union_c_d}": [
    "Method{all_static_fields.D.__init__}", "Method{builtins.object.__new__}"
  ],
  "Function{all_static_fields.return_source_union_dataclass_regular}": [
    "Method{all_static_fields.RegularClass.__init__}",
    "Method{builtins.object.__new__}"
  ],
  "Method{all_static_fields.C.__init__}": [
    "Method{all_static_fields.A.__init__}",
    "Method{builtins.object.__new__}", "Method{builtins.super.__init__}"
  ],
  "Method{all_static_fields.D.__init__}": [
    "Method{all_static_fields.A.__init__}",
    "Method{builtins.object.__new__}", "Method{builtins.super.__init__}"
  ]
}