@generated
Call dependencies
{
  "Function{any_index.post_0}": [
    "Function{pysa._test_source}", "Method{builtins.dict.__getitem__}",
    "Method{builtins.dict.__setitem__}"
  ],
  "Function{any_index.post_1}": [
    "Function{pysa._test_source}", "Method{builtins.dict.__getitem__}",
    "Method{builtins.dict.__setitem__}"
  ],
  "Function{any_index.post_2}": [
    "Function{pysa._test_source}", "Method{_random.Random.random}",
    "Method{builtins.dict.__getitem__}", "Method{builtins.dict.__setitem__}",
    "Method{builtins.float.__gt__}"
  ],
  "Function{any_index.post_3}": [
    "Function{pysa._test_source}", "Method{_random.Random.random}",
    "Method{builtins.dict.__getitem__}", "Method{builtins.dict.__setitem__}",
    "Method{builtins.float.__gt__}"
  ],
  "Function{any_index.pre_0}": [
    "Function{pysa._test_sink}", "Method{builtins.dict.__getitem__}",
    "Method{builtins.dict.__setitem__}"
  ],
  "Function{any_index.pre_1}": [
    "Function{pysa._test_sink}", "Method{builtins.dict.__getitem__}",
    "Method{builtins.dict.__setitem__}"
  ],
  "Function{any_index.pre_2}": [
    "Function{pysa._test_sink}", "Method{_random.Random.random}",
    "Method{builtins.dict.__getitem__}", "Method{builtins.dict.__setitem__}",
    "Method{builtins.float.__gt__}"
  ],
  "Function{any_index.pre_3}": [
    "Function{pysa._test_sink}", "Method{_random.Random.random}",
    "Method{builtins.dict.__getitem__}", "Method{builtins.dict.__setitem__}",
    "Method{builtins.float.__gt__}"
  ]
}