@generated
Call dependencies
{
  "Function{applies_to_index.issue_only_with_a_key}": [
    "Function{applies_to_index.only_applies_to_a_key}",
    "Function{pysa._test_sink}", "Method{builtins.dict.__getitem__}"
  ],
  "Function{applies_to_index.issue_only_with_first}": [
    "Function{applies_to_index.only_applies_to_first}",
    "Function{pysa._test_sink}"
  ],
  "Function{applies_to_index.issue_only_with_nested_first}": [
    "Function{applies_to_index.only_applies_to_nested}",
    "Function{pysa._test_sink}"
  ],
  "Function{applies_to_index.issue_only_with_second}": [
    "Function{applies_to_index.only_applies_to_second}",
    "Function{pysa._test_sink}"
  ],
  "Function{applies_to_index.issue_with_member}": [
    "Function{applies_to_index.only_applies_to_a_member}",
    "Function{pysa._test_sink}"
  ]
}