@generated
Call dependencies
{
  "Function{attach_features.attach_to_parameter_source}": [
    "Function{pysa._test_sink}"
  ],
  "Function{attach_features.attach_to_returned_sink}": [
    "Function{pysa._test_source}"
  ],
  "Function{attach_features.attach_to_returned_with_captures.nested}": [
    "Function{pysa._test_source}"
  ],
  "Function{attach_features.attach_to_returned_with_captures}": [
    "Function{attach_features.attach_to_returned_with_captures.nested}"
  ],
  "Function{attach_features.inferred_is_propagated}": [
    "Function{attach_features.source_with_inferred}"
  ],
  "Function{attach_features.inferred_sink}": [ "Function{pysa._test_sink}" ],
  "Function{attach_features.modeled_sink_with_optionals}": [
    "Function{pysa._test_sink}"
  ],
  "Function{attach_features.no_tito}": [
    "Function{attach_features.attach_without_tito}"
  ],
  "Function{attach_features.sink_is_propagated}": [
    "Function{attach_features.inferred_sink}"
  ],
  "Function{attach_features.source_with_inferred}": [
    "Function{attach_features.source}"
  ],
  "Function{attach_features.tito_and_sink}": [ "Function{pysa._test_sink}" ],
  "Function{attach_features.tito_is_propagated}": [
    "Function{attach_features.taint_in_taint_out}"
  ],
  "Method{attach_features.HasMethods.method_with_optionals}": [
    "Function{pysa._test_sink}"
  ]
}