@generated
Call dependencies
{
  "Function{attributes.$toplevel}": [ "Function{dataclasses.dataclass}" ],
  "Function{attributes.Request.$class_toplevel}": [
    "Method{builtins.object.__init__}", "Method{builtins.object.__new__}"
  ],
  "Function{attributes.test_attribute_union_sink}": [
    "ClassInstanceAttribute{attributes.Sink.token}",
    "Function{builtins.isinstance}", "Function{pysa._test_source}"
  ],
  "Function{attributes.test_attribute_union_source}": [
    "ClassInstanceAttribute{attributes.Token.token}",
    "Function{builtins.isinstance}", "Function{pysa._test_sink}"
  ],
  "Function{attributes.test_attribute_via_dunder_dict}": [
    "Function{pysa._test_sink}", "Function{pysa._test_source}",
    "Method{attributes.UseViaDict.__init__}",
    "Method{builtins.dict.__getitem__}", "Method{builtins.object.__new__}"
  ],
  "Function{attributes.test_attribute}": [
    "ClassInstanceAttribute{attributes.Token.token}"
  ],
  "Function{attributes.test_getattr_backwards_default}": [
    "ClassInstanceAttribute{attributes.Token.token}",
    "Function{builtins.getattr}", "Function{pysa._test_sink}"
  ],
  "Function{attributes.test_getattr_backwards}": [
    "ClassInstanceAttribute{attributes.Token.token}",
    "Function{builtins.getattr}", "Function{pysa._test_sink}"
  ],
  "Function{attributes.test_getattr_default}": [
    "Function{builtins.getattr}", "Function{pysa._test_source}"
  ],
  "Function{attributes.test_getattr_forward}": [
    "ClassInstanceAttribute{attributes.Token.token}",
    "Function{builtins.getattr}"
  ],
  "Function{attributes.test_issue_with_text_key_of_dictionary}": [
    "ClassInstanceAttribute{attributes.C.dictionary}",
    "Function{pysa._test_sink}", "Method{builtins.dict.__getitem__}"
  ],
  "Function{attributes.test_issue_with_tito_copy_dict}": [
    "Function{attributes.tito_copy_dict}", "Function{pysa._test_sink}",
    "Function{pysa._test_source}"
  ],
  "Function{attributes.test_issue_with_tito_copy_multiple_possible_dictlike_objects}": [
    "Function{attributes.tito_copy_multiple_possible_dictlike_objects}",
    "Function{pysa._test_sink}", "Function{pysa._test_source}",
    "Method{attributes.RegularForm.__init__}",
    "Method{builtins.object.__new__}", "Method{typing.Mapping.__getitem__}"
  ],
  "Function{attributes.test_issue_with_update_to_self_attribute}": [
    "ClassInstanceAttribute{attributes.D.buffer}",
    "Function{pysa._test_source}", "Method{builtins.list.append}"
  ],
  "Function{attributes.test_no_issue_sanitize_via_call}": [
    "Function{attributes.sanitize_attribute}", "Function{pysa._test_sink}",
    "Function{pysa._test_source}", "Method{builtins.object.__init__}",
    "Method{builtins.object.__new__}"
  ],
  "Function{attributes.test_no_issue_sanitize}": [
    "Function{pysa._test_sink}", "Function{pysa._test_source}",
    "Method{builtins.object.__init__}", "Method{builtins.object.__new__}"
  ],
  "Function{attributes.test_no_issue_with_other_key_of_dictionary}": [
    "ClassInstanceAttribute{attributes.C.dictionary}",
    "Function{pysa._test_sink}", "Method{builtins.dict.__getitem__}"
  ],
  "Function{attributes.test_no_list_inference}": [
    "Function{pysa._test_source}",
    "Method{attributes.NoListInference.__init__}",
    "Method{attributes.NoListInference.append}",
    "Method{attributes.NoListInference.sink}",
    "Method{builtins.object.__new__}"
  ],
  "Function{attributes.test_via_non_optional}": [
    "ClassInstanceAttribute{attributes.Token.token}"
  ],
  "Function{attributes.test_via_optional}": [
    "ClassInstanceAttribute{attributes.Token.token}"
  ],
  "Function{attributes.tito_copy_multiple_possible_dictlike_objects}": [
    "Method{attributes.PartiallyZonedDict.copy}",
    "Method{attributes.ZonedForm.data}", "Method{builtins.dict.copy}"
  ],
  "Method{attributes.IsAttributeBug.issue}": [
    "Function{pysa._test_sink}", "Function{pysa._test_source}",
    "Method{attributes.IsAttributeBug.__init__}",
    "Method{builtins.object.__new__}"
  ],
  "Method{attributes.NoListInference.append}": [
    "Method{builtins.list.append}"
  ],
  "Method{attributes.NoListInference.sink}": [ "Function{pysa._test_sink}" ]
}