@generated
Call dependencies
{
  "Function{binary_operators.test1}": [
    "Function{pysa._test_source}", "Method{binary_operators.Add.__add__}",
    "Method{builtins.object.__init__}", "Method{builtins.object.__new__}"
  ],
  "Function{binary_operators.test2}": [
    "Function{pysa._test_source}", "Method{binary_operators.Add.__add__}",
    "Method{builtins.object.__init__}", "Method{builtins.object.__new__}"
  ],
  "Method{binary_operators.Add.__add__}": [ "Function{pysa._test_sink}" ]
}