@generated
Call dependencies
{
  "Function{breadcrumbs.bool_parameter}": [ "Function{pysa._test_sink}" ],
  "Function{breadcrumbs.bool_source}": [ "Function{pysa._test_source}" ],
  "Function{breadcrumbs.float_parameter}": [ "Function{pysa._test_sink}" ],
  "Function{breadcrumbs.float_source}": [ "Function{pysa._test_source}" ],
  "Function{breadcrumbs.int_parameter}": [ "Function{pysa._test_sink}" ],
  "Function{breadcrumbs.int_source}": [ "Function{pysa._test_source}" ],
  "Function{breadcrumbs.scalar_attribute_backward}": [
    "Function{pysa._test_sink}", "Method{_random.Random.random}",
    "Method{builtins.float.__gt__}", "Method{builtins.list.__iter__}",
    "Method{builtins.object.__init__}", "Method{builtins.object.__repr__}",
    "Method{builtins.str.__new__}", "Method{builtins.str.join}",
    "Method{typing.Iterator.__next__}"
  ],
  "Function{breadcrumbs.scalar_attribute_forward}": [
    "Function{breadcrumbs.tpm_request}", "Method{_random.Random.random}",
    "Method{builtins.float.__gt__}", "Method{builtins.list.__iter__}",
    "Method{builtins.object.__init__}", "Method{builtins.object.__repr__}",
    "Method{builtins.str.__new__}", "Method{builtins.str.join}",
    "Method{typing.Iterator.__next__}"
  ]
}