@generated
Call dependencies
{
  "Function{builder_pattern.test_chained_class_setter}": [
    "Function{pysa._test_sink}", "Function{pysa._test_source}",
    "Method{builder_pattern.Builder.__init__}",
    "Method{builder_pattern.Builder.return_self}",
    "Method{builder_pattern.Builder.set_saved_no_return}",
    "Method{builtins.object.__new__}"
  ],
  "Function{builder_pattern.test_class_setter}": [
    "Function{pysa._test_sink}", "Function{pysa._test_source}",
    "Method{builder_pattern.Builder.__init__}",
    "Method{builder_pattern.Builder.set_saved_no_return}",
    "Method{builtins.object.__new__}"
  ],
  "Function{builder_pattern.test_issue_with_sub_builder}": [
    "Function{pysa._test_source}",
    "Method{builder_pattern.Builder.__init__}",
    "Method{builder_pattern.Builder.async_save}",
    "Method{builder_pattern.Builder.set_not_saved_through_typevar}",
    "Method{builder_pattern.Builder.set_saved_through_typevar}",
    "Method{builtins.object.__new__}"
  ],
  "Function{builder_pattern.test_issue_with_type_var}": [
    "Function{pysa._test_source}",
    "Method{builder_pattern.Builder.__init__}",
    "Method{builder_pattern.Builder.async_save}",
    "Method{builder_pattern.Builder.set_not_saved_through_typevar}",
    "Method{builder_pattern.Builder.set_saved_through_typevar}",
    "Method{builtins.object.__new__}"
  ],
  "Function{builder_pattern.test_issue}": [
    "Function{pysa._test_source}",
    "Method{builder_pattern.Builder.__init__}",
    "Method{builder_pattern.Builder.async_save}",
    "Method{builder_pattern.Builder.set_not_saved}",
    "Method{builder_pattern.Builder.set_saved}",
    "Method{builtins.object.__new__}"
  ],
  "Function{builder_pattern.test_no_issue_with_sub_builder}": [
    "Function{pysa._test_source}",
    "Method{builder_pattern.Builder.__init__}",
    "Method{builder_pattern.Builder.async_save}",
    "Method{builder_pattern.Builder.set_not_saved_through_typevar}",
    "Method{builder_pattern.Builder.set_saved_through_typevar}",
    "Method{builtins.object.__new__}"
  ],
  "Function{builder_pattern.test_no_issue_with_type_var}": [
    "Function{pysa._test_source}",
    "Method{builder_pattern.Builder.__init__}",
    "Method{builder_pattern.Builder.async_save}",
    "Method{builder_pattern.Builder.set_not_saved_through_typevar}",
    "Method{builder_pattern.Builder.set_saved_through_typevar}",
    "Method{builtins.object.__new__}"
  ],
  "Function{builder_pattern.test_no_issue}": [
    "Function{pysa._test_source}",
    "Method{builder_pattern.Builder.__init__}",
    "Method{builder_pattern.Builder.async_save}",
    "Method{builder_pattern.Builder.set_not_saved}",
    "Method{builder_pattern.Builder.set_saved}",
    "Method{builtins.object.__new__}"
  ],
  "Function{builder_pattern.test_taint_update_receiver_declaration}": [
    "Function{pysa._test_sink}", "Function{pysa._test_source}",
    "Method{builder_pattern.Builder.__init__}",
    "Method{builder_pattern.Builder.return_self}",
    "Method{builder_pattern.Builder.set_saved}",
    "Method{builtins.object.__new__}"
  ],
  "Method{builder_pattern.Builder.async_save}": [
    "Function{pysa._test_sink}"
  ]
}