@generated
Call dependencies
{
  "Function{call_graph.is_dict}": [ "Function{builtins.isinstance}" ],
  "Function{call_graph.no_op_decorator_factory.inner}": [
    "Function{builtins.setattr}"
  ],
  "Function{call_graph.no_op_decorator_factory.inner}[formal(original, position=0)=Method{call_graph.CallableKindConfusion.foo}]": [
    "Function{builtins.setattr}"
  ],
  "Function{call_graph.test_chained_assign_subscript}": [
    "Function{call_graph.is_dict}", "Method{builtins.dict.__getitem__}",
    "Method{builtins.dict.__setitem__}"
  ],
  "Function{call_graph.test_chained_assign}": [
    "Function{pysa._test_sink}", "Method{builtins.object.__new__}",
    "Method{call_graph.NotSource.__init__}",
    "Method{call_graph.NotSource.method}"
  ],
  "Function{call_graph.test_default_parameters}": [
    "Function{pysa._test_sink}", "Function{pysa._test_source}"
  ],
  "Function{call_graph.test_localized_target}": [
    "Function{call_graph.test_localized_target.f}",
    "Method{_random.Random.random}", "Method{builtins.float.__gt__}"
  ],
  "Function{call_graph.test_match_type_of}": [
    "Function{pysa._test_sink}", "Method{builtins.type.__init__}",
    "Method{builtins.type.__new__}",
    "Method{call_graph.namespace.A.__call__}",
    "Method{call_graph.namespace.B.__call__}",
    "Method{call_graph.namespace.C.__call__}"
  ],
  "Method{call_graph.CallableKindConfusion.foo@decorated}": [
    "Function{call_graph.no_op_decorator_factory.inner}[formal(original, position=0)=Method{call_graph.CallableKindConfusion.foo}]",
    "Function{call_graph.no_op_decorator_factory}",
    "Function{call_graph.no_op_decorator}[formal(f, position=0)=Method{call_graph.CallableKindConfusion.foo}]"
  ],
  "Method{call_graph.IsSource.method}": [ "Function{pysa._test_source}" ],
  "Method{call_graph.NotSource.method}": [
    "Method{builtins.object.__new__}", "Method{call_graph.IsSource.__init__}"
  ]
}