@generated
Call dependencies
{
  "Function{callables.async_execute_event_processor}": [
    "Function{callables.get_event_processors}",
    "Function{pysa._test_source}", "Method{builtins.list.__iter__}",
    "Method{builtins.object.__new__}",
    "Method{callables.AbstractEventProcessor.__init__}",
    "Method{typing.Iterator.__next__}",
    "Override{callables.AbstractEventProcessor.async_call_tainted}",
    "Override{callables.AbstractEventProcessor.async_run}"
  ],
  "Method{callables.ConcreteEventProcessor.async_call_tainted}": [
    "Function{pysa._test_sink}"
  ],
  "Method{callables.ConcreteEventProcessor.async_run}": [
    "Function{pysa._test_sink}"
  ]
}