@generated
Call dependencies
{
  "Function{class_methods.bar}": [
    "Function{pysa._test_source}", "Method{class_methods.Test.foo}"
  ],
  "Function{class_methods.issue_with_abstract_class_method}": [
    "Function{pysa._test_source}",
    "Method{class_methods.C.one_hop_abstract_class_method}",
    "Method{class_methods.C.one_hop_abstract_method}",
    "Method{class_methods.C.one_hop_class_abstractmethod}",
    "Method{class_methods.C.one_hop_class_method}",
    "Method{class_methods.C.one_hop_static_abstractmethod}"
  ],
  "Function{class_methods.issue_with_abstract_property}": [
    "Function{pysa._test_sink}", "Function{pysa._test_source}",
    "Method{builtins.object.__new__}", "Method{class_methods.D.__init__}",
    "Method{class_methods.D.my_abstract_property@setter}",
    "Method{class_methods.D.my_abstract_property}"
  ],
  "Function{class_methods.test_obscure_class_method_tito}": [
    "Function{pysa._test_sink}", "Function{pysa._test_source}",
    "Method{builtins.object.__new__}",
    "Method{class_methods.ObscureClassMethodTito.__init__}",
    "Method{class_methods.ObscureClassMethodTito.method}"
  ],
  "Method{class_methods.C.class_method}": [ "Function{pysa._test_sink}" ],
  "Method{class_methods.C.one_hop_abstract_class_method}": [
    "Override{class_methods.C.abstract_class_method}"
  ],
  "Method{class_methods.C.one_hop_abstract_method}": [
    "Method{class_methods.C.abstract_method}"
  ],
  "Method{class_methods.C.one_hop_class_abstractmethod}": [
    "Override{class_methods.C.class_abstractmethod}"
  ],
  "Method{class_methods.C.one_hop_class_method}": [
    "Method{class_methods.C.class_method}"
  ],
  "Method{class_methods.C.one_hop_static_abstractmethod}": [
    "Method{class_methods.C.static_abstractmethod}"
  ],
  "Method{class_methods.C.static_abstractmethod}": [
    "Function{pysa._test_sink}"
  ],
  "Method{class_methods.D.__init__}": [
    "Method{builtins.object.__new__}", "Method{builtins.super.__init__}"
  ],
  "Method{class_methods.D.abstract_class_method}": [
    "Function{pysa._test_sink}"
  ],
  "Method{class_methods.D.abstract_method}": [ "Function{pysa._test_sink}" ],
  "Method{class_methods.D.class_abstractmethod}": [
    "Function{pysa._test_sink}"
  ],
  "Method{class_methods.Test.foo}": [ "Function{pysa._test_sink}" ]
}