@generated
Call dependencies
{
  "Function{class_attribute.class_attribute_A_a_flow}": [
    "Function{class_attribute.class_attribute_A_a_sink}",
    "Function{class_attribute.class_attribute_A_a_source}"
  ],
  "Function{class_attribute.class_attribute_A_a_no_flow}": [
    "Function{class_attribute.class_attribute_A_a_sink}",
    "Function{class_attribute.class_attribute_A_a_source}"
  ],
  "Function{class_attribute.class_attribute_A_a_sink}": [
    "Function{pysa._test_sink}"
  ],
  "Function{class_attribute.class_attribute_A_a_source}": [
    "Function{pysa._test_source}"
  ],
  "Function{class_attribute.class_attribute_A_b_flow1}": [
    "Function{class_attribute.class_attribute_A_b_sink}",
    "Method{builtins.object.__new__}", "Method{class_attribute.A.__init__}"
  ],
  "Function{class_attribute.class_attribute_A_b_flow2}": [
    "Method{builtins.object.__new__}", "Method{class_attribute.A.__init__}",
    "Method{class_attribute.A.sink_b}"
  ],
  "Function{class_attribute.class_attribute_A_b_sink}": [
    "Function{pysa._test_sink}"
  ],
  "Function{class_attribute.instance_attribute_A_c_no_flow}": [
    "Method{builtins.object.__new__}", "Method{class_attribute.A.__init__}",
    "Method{class_attribute.A.sink_c}"
  ],
  "Function{class_attribute.instance_attribute_A_d_flow}": [
    "Method{builtins.object.__new__}", "Method{class_attribute.A.__init__}",
    "Method{class_attribute.A.sink_d}"
  ],
  "Method{class_attribute.A.__init__}": [ "Function{pysa._test_source}" ],
  "Method{class_attribute.A.sink_a}": [ "Function{pysa._test_sink}" ],
  "Method{class_attribute.A.sink_b}": [ "Function{pysa._test_sink}" ],
  "Method{class_attribute.A.sink_c}": [ "Function{pysa._test_sink}" ],
  "Method{class_attribute.A.sink_d}": [ "Function{pysa._test_sink}" ]
}