@generated
Call dependencies
{
  "Function{class_interval.abstract_method}": [
    "Function{pysa._test_sink}", "Method{class_interval.A13.f}"
  ],
  "Function{class_interval.call_method_via_class_name}": [
    "Method{class_interval.A9.f}"
  ],
  "Function{class_interval.canonical_example}": [
    "Function{pysa._test_source}", "Method{class_interval.B0.m0}"
  ],
  "Function{class_interval.issue_precise_tito_intervals}": [
    "Function{pysa._test_sink}", "Function{pysa._test_source}",
    "Method{class_interval.A23.m0}"
  ],
  "Function{class_interval.multi_inheritance_issue}": [
    "Function{pysa._test_sink}", "Method{class_interval.B16.m0}"
  ],
  "Function{class_interval.multi_inheritance_no_issue_one_hop}": [
    "Function{pysa._test_sink}", "Method{class_interval.B14.m0}"
  ],
  "Function{class_interval.multi_inheritance_no_issue_two_hops}": [
    "Function{pysa._test_sink}", "Method{class_interval.B15.m0}"
  ],
  "Function{class_interval.multiple_inheritance}": [
    "Function{pysa._test_source}", "Method{class_interval.B2.m0}"
  ],
  "Function{class_interval.no_call_to_parent_class}": [
    "Function{pysa._test_source}", "Method{class_interval.B1.m0}"
  ],
  "Function{class_interval.no_issue_source_through_staticmethod_tito}": [
    "Function{pysa._test_sink}", "Method{class_interval.A24.m0}"
  ],
  "Function{class_interval.no_issue_taint_transform_with_class_interval_for_classmethods}": [
    "Function{class_interval.sink_d}", "Function{pysa._test_source}",
    "Method{class_interval.A21.m0}"
  ],
  "Function{class_interval.no_issue_taint_transform_with_class_interval}": [
    "Function{class_interval.sink_d}", "Function{pysa._test_source}",
    "Method{class_interval.A22.m0}"
  ],
  "Function{class_interval.propagate_source_empty}": [
    "Function{pysa._test_sink}", "Method{class_interval.A6.m1}"
  ],
  "Function{class_interval.sink_in_subclass}": [
    "Function{pysa._test_source}", "Override{class_interval.B3.m0}"
  ],
  "Function{class_interval.sink_two_hops}": [
    "Function{pysa._test_source}", "Method{class_interval.B5.m0}"
  ],
  "Function{class_interval.source_two_hops}": [
    "Function{pysa._test_source}", "Method{class_interval.D4.m0}"
  ],
  "Function{class_interval.test_class_methods}": [
    "Function{pysa._test_source}", "Method{builtins.object.__init__}",
    "Method{builtins.object.__new__}", "Method{class_interval.A17.m0}",
    "Method{class_interval.A17.m2}"
  ],
  "Function{class_interval.test_multi_inheritance_parent_call}": [
    "Function{pysa._test_source}", "Method{class_interval.A20.m0}"
  ],
  "Function{class_interval.test_multi_inheritance_parent_issue}": [
    "Function{class_interval.test_multi_inheritance_parent_call}",
    "Method{builtins.object.__init__}", "Method{builtins.object.__new__}"
  ],
  "Function{class_interval.test_static_methods}": [
    "Function{pysa._test_source}", "Method{builtins.object.__init__}",
    "Method{builtins.object.__new__}", "Method{class_interval.C18.m0}"
  ],
  "Function{class_interval.undetected_issue}": [
    "Function{pysa._test_sink}", "Method{class_interval.A12.f}"
  ],
  "Method{class_interval.A0.m1}": [ "Override{class_interval.A0.m2}" ],
  "Method{class_interval.A1.m1}": [ "Override{class_interval.A1.m2}" ],
  "Method{class_interval.A10.object_target}": [
    "ClassInstanceAttribute{class_interval.A10.f}",
    "Method{builtins.object.__init__}", "Method{builtins.object.__new__}"
  ],
  "Method{class_interval.A13.f}": [ "Override{class_interval.A13.g}" ],
  "Method{class_interval.A14.m1}": [ "Override{class_interval.A14.m2}" ],
  "Method{class_interval.A15.m1}": [ "Override{class_interval.A15.m2}" ],
  "Method{class_interval.A16.m1}": [ "Override{class_interval.A16.m2}" ],
  "Method{class_interval.A17.m0}": [ "Override{class_interval.A17.m1}" ],
  "Method{class_interval.A17.m2}": [ "Method{class_interval.D17.m1}" ],
  "Method{class_interval.A19.m0}": [ "Method{class_interval.A19.m1}" ],
  "Method{class_interval.A19.m1}": [ "Function{pysa._test_sink}" ],
  "Method{class_interval.A19.m2}": [ "Method{class_interval.A19.m3}" ],
  "Method{class_interval.A19.m3}": [ "Function{pysa._test_sink}" ],
  "Method{class_interval.A2.m1}": [ "Override{class_interval.A2.m2}" ],
  "Method{class_interval.A21.m0}": [ "Override{class_interval.A21.m1}" ],
  "Method{class_interval.A22.m0}": [ "Override{class_interval.A22.m1}" ],
  "Method{class_interval.A23.m0}": [ "Override{class_interval.A23.m1}" ],
  "Method{class_interval.A24.m0}": [
    "Method{class_interval.A24.tito}", "Override{class_interval.A24.m1}"
  ],
  "Method{class_interval.A3.m1}": [ "Override{class_interval.A3.m2}" ],
  "Method{class_interval.A4.m2}": [ "Override{class_interval.A4.m3}" ],
  "Method{class_interval.A5.m1}": [ "Override{class_interval.A5.m2}" ],
  "Method{class_interval.A6.m1}": [ "Override{class_interval.A6.m0}" ],
  "Method{class_interval.A7.f}": [ "Method{class_interval.B7.foo}" ],
  "Method{class_interval.A8.bar}": [
    "Method{builtins.int.__eq__}", "Method{builtins.object.__init__}",
    "Method{builtins.object.__new__}", "Method{class_interval.A8.baz}",
    "Method{class_interval.B8.foo}", "Method{class_interval.C8.foo}"
  ],
  "Method{class_interval.A8.baz}": [ "Function{pysa._test_source}" ],
  "Method{class_interval.A9.f}": [ "Function{pysa._test_source}" ],
  "Method{class_interval.B0.m0}": [ "Method{class_interval.A0.m1}" ],
  "Method{class_interval.B1.m0}": [ "Method{class_interval.B1.m1}" ],
  "Method{class_interval.B14.m0}": [ "Method{class_interval.A14.m1}" ],
  "Method{class_interval.B15.m0}": [ "Method{class_interval.A15.m1}" ],
  "Method{class_interval.B16.m0}": [ "Method{class_interval.A16.m1}" ],
  "Method{class_interval.B18.m0}": [ "Function{class_interval.sink_b}" ],
  "Method{class_interval.B2.m0}": [ "Method{class_interval.A2.m1}" ],
  "Method{class_interval.B21.m1}": [ "Function{class_interval.transformX}" ],
  "Method{class_interval.B22.m1}": [ "Function{class_interval.transformX}" ],
  "Method{class_interval.B24.m1}": [ "Function{pysa._test_source}" ],
  "Method{class_interval.B3.m0}": [ "Method{class_interval.A3.m1}" ],
  "Method{class_interval.B4.m1}": [ "Method{class_interval.A4.m2}" ],
  "Method{class_interval.B5.m0}": [ "Method{class_interval.A5.m1}" ],
  "Method{class_interval.B6.m0}": [
    "Function{pysa._test_source}", "Method{_random.Random.random}",
    "Method{builtins.float.__gt__}", "Method{builtins.object.__init__}",
    "Method{builtins.object.__new__}", "Method{class_interval.E6.m3}"
  ],
  "Method{class_interval.B7.bar}": [ "Function{pysa._test_source}" ],
  "Method{class_interval.B7.foo}": [ "Method{class_interval.B7.bar}" ],
  "Method{class_interval.B8.foo}": [ "Function{pysa._test_source}" ],
  "Method{class_interval.C0.m2}": [ "Function{pysa._test_sink}" ],
  "Method{class_interval.C1.m2}": [ "Function{pysa._test_sink}" ],
  "Method{class_interval.C12.g}": [ "Function{pysa._test_source}" ],
  "Method{class_interval.C13.g}": [ "Function{pysa._test_source}" ],
  "Method{class_interval.C14.m2}": [ "Function{pysa._test_source}" ],
  "Method{class_interval.C17.m1}": [ "Function{class_interval.sink_c}" ],
  "Method{class_interval.C18.m0}": [ "Method{class_interval.B18.m0}" ],
  "Method{class_interval.C20.m0}": [ "Function{pysa._test_sink}" ],
  "Method{class_interval.C23.m1}": [
    "Function{class_interval.add_feature_c}"
  ],
  "Method{class_interval.C3.m0}": [ "Method{class_interval.A3.m1}" ],
  "Method{class_interval.C3.m2}": [ "Function{pysa._test_sink}" ],
  "Method{class_interval.C4.m3}": [ "Function{pysa._test_sink}" ],
  "Method{class_interval.C6.m2}": [ "Method{class_interval.A6.m1}" ],
  "Method{class_interval.D16.m2}": [ "Function{pysa._test_source}" ],
  "Method{class_interval.D17.m1}": [ "Function{class_interval.sink_c}" ],
  "Method{class_interval.D2.m2}": [ "Function{pysa._test_sink}" ],
  "Method{class_interval.D23.m1}": [
    "Function{class_interval.add_feature_d}"
  ],
  "Method{class_interval.D4.m0}": [ "Method{class_interval.B4.m1}" ],
  "Method{class_interval.D5.m2}": [ "Function{pysa._test_sink}" ],
  "Method{class_interval.D6.m0}": [
    "Method{builtins.object.__new__}", "Method{builtins.super.__init__}",
    "Method{class_interval.B6.m0}"
  ],
  "Method{class_interval.E15.m2}": [ "Function{pysa._test_source}" ],
  "Method{class_interval.E23.m1}": [
    "Function{class_interval.add_feature_e}"
  ],
  "Method{class_interval.E6.m3}": [ "Function{pysa._test_source}" ]
}