@generated
Call dependencies
{
  "Function{closure.async_nonlocal_closure_tito_ignore_decorator}": [
    "Function{closure.async_tito}[formal(function, position=0)=Function{closure.async_nonlocal_closure_tito_ignore_decorator.inner}]",
    "Function{pysa._test_sink}", "Function{pysa._test_source}"
  ],
  "Function{closure.async_nonlocal_closure_tito_with_decorator.inner@decorated}": [
    "Function{closure.decorator}[formal(function, position=0)=Function{closure.async_nonlocal_closure_tito_with_decorator.inner}]"
  ],
  "Function{closure.async_nonlocal_closure_tito_with_decorator}": [
    "Function{closure.async_tito}[formal(function, position=0)=Function{closure.decorator.wrapper}[captured_variable(function, closure.decorator)=Function{closure.async_nonlocal_closure_tito_with_decorator.inner}]]",
    "Function{pysa._test_sink}", "Function{pysa._test_source}"
  ],
  "Function{closure.async_tito}[formal(function, position=0)=Function{closure.async_nonlocal_closure_tito_ignore_decorator.inner}]": [
    "Function{closure.async_nonlocal_closure_tito_ignore_decorator.inner}"
  ],
  "Function{closure.async_tito}[formal(function, position=0)=Function{closure.decorator.wrapper}[captured_variable(function, closure.decorator)=Function{closure.async_nonlocal_closure_tito_with_decorator.inner}]]": [
    "Function{closure.decorator.wrapper}[captured_variable(function, closure.decorator)=Function{closure.async_nonlocal_closure_tito_with_decorator.inner}]"
  ],
  "Function{closure.closure.sink}": [ "Function{pysa._test_sink}" ],
  "Function{closure.closure.source}": [ "Function{pysa._test_source}" ],
  "Function{closure.closure_flow}": [
    "Function{closure.closure.sink}", "Function{closure.closure.source}",
    "Function{closure.closure}"
  ],
  "Function{closure.closure_nested_sink_flow.sink1.sink2.sink3}": [
    "Function{pysa._test_sink}"
  ],
  "Function{closure.closure_nested_sink_flow.sink1.sink2}": [
    "Function{closure.closure_nested_sink_flow.sink1.sink2.sink3}",
    "Function{pysa._test_sink}"
  ],
  "Function{closure.closure_nested_sink_flow.sink1}": [
    "Function{closure.closure_nested_sink_flow.sink1.sink2}",
    "Function{pysa._test_sink}"
  ],
  "Function{closure.closure_nested_sink_flow}": [
    "Function{closure.closure_nested_sink_flow.sink1}",
    "Function{pysa._test_source}"
  ],
  "Function{closure.closure_no_flow}": [
    "Function{closure.closure.sink}", "Function{closure.closure.source}",
    "Function{closure.closure}"
  ],
  "Function{closure.closure_wrapper_sink_flow.sink}": [
    "Function{pysa._test_sink}"
  ],
  "Function{closure.closure_wrapper_sink_flow.wrapper}": [
    "Function{closure.closure_wrapper_sink_flow.sink}"
  ],
  "Function{closure.closure_wrapper_sink_flow}": [
    "Function{closure.closure_wrapper_sink_flow.wrapper}",
    "Function{pysa._test_source}", "Method{builtins.list.append}"
  ],
  "Function{closure.closure}": [
    "Method{builtins.object.__new__}", "Method{closure.Object.__init__}"
  ],
  "Function{closure.decorator.wrapper}[captured_variable(function, closure.decorator)=Function{closure.async_nonlocal_closure_tito_with_decorator.inner}]": [
    "Function{closure.async_nonlocal_closure_tito_with_decorator.inner}"
  ],
  "Function{closure.higher_order_function}[formal(f, position=0)=Function{closure.wrapper_for_taint_propagation_hof.inner}]": [
    "Function{closure.wrapper_for_taint_propagation_hof.inner}"
  ],
  "Function{closure.nonlocal_closure_conditional_write.conditional_write}": [
    "Function{closure._test_source2}"
  ],
  "Function{closure.nonlocal_closure_conditional_write}": [
    "Function{closure.nonlocal_closure_conditional_write.clear}",
    "Function{closure.nonlocal_closure_conditional_write.conditional_write}",
    "Function{pysa._test_sink}", "Function{pysa._test_source}"
  ],
  "Function{closure.nonlocal_closure_define_before_variable_initialization.read}": [
    "Function{pysa._test_sink}"
  ],
  "Function{closure.nonlocal_closure_define_before_variable_initialization}": [
    "Function{closure.nonlocal_closure_define_before_variable_initialization.read}",
    "Function{pysa._test_source}"
  ],
  "Function{closure.nonlocal_closure_flow.sink}": [
    "Function{pysa._test_sink}"
  ],
  "Function{closure.nonlocal_closure_flow.source}": [
    "Function{pysa._test_source}"
  ],
  "Function{closure.nonlocal_closure_flow}": [
    "Function{closure.nonlocal_closure_flow.sink}",
    "Function{closure.nonlocal_closure_flow.source}"
  ],
  "Function{closure.nonlocal_closure_inner_flow.flow}": [
    "Function{pysa._test_sink}", "Function{pysa._test_source}"
  ],
  "Function{closure.nonlocal_closure_inner_flow}": [
    "Function{closure.nonlocal_closure_inner_flow.flow}"
  ],
  "Function{closure.nonlocal_closure_multiple_reads.conditional_read}": [
    "Function{pysa._test_sink}"
  ],
  "Function{closure.nonlocal_closure_multiple_reads.overread}": [
    "Function{pysa._test_sink}"
  ],
  "Function{closure.nonlocal_closure_multiple_reads}": [
    "Function{closure.nonlocal_closure_multiple_reads.conditional_read}",
    "Function{closure.nonlocal_closure_multiple_reads.overread}",
    "Function{pysa._test_source}"
  ],
  "Function{closure.nonlocal_closure_multiple_writes.conditional_write}": [
    "Function{pysa._test_source}"
  ],
  "Function{closure.nonlocal_closure_multiple_writes.overwrite}": [
    "Function{pysa._test_source}"
  ],
  "Function{closure.nonlocal_closure_multiple_writes}": [
    "Function{closure.nonlocal_closure_multiple_writes.conditional_write}",
    "Function{closure.nonlocal_closure_multiple_writes.overwrite}",
    "Function{pysa._test_sink}"
  ],
  "Function{closure.nonlocal_closure_nested_source_flow.source1.source2.source3}": [
    "Function{pysa._test_source}"
  ],
  "Function{closure.nonlocal_closure_nested_source_flow.source1.source2}": [
    "Function{closure.nonlocal_closure_nested_source_flow.source1.source2.source3}",
    "Function{pysa._test_sink}"
  ],
  "Function{closure.nonlocal_closure_nested_source_flow.source1}": [
    "Function{closure.nonlocal_closure_nested_source_flow.source1.source2}",
    "Function{pysa._test_sink}"
  ],
  "Function{closure.nonlocal_closure_nested_source_flow}": [
    "Function{closure.nonlocal_closure_nested_source_flow.source1}",
    "Function{pysa._test_sink}"
  ],
  "Function{closure.nonlocal_closure_no_flow.sink}": [
    "Function{pysa._test_sink}"
  ],
  "Function{closure.nonlocal_closure_no_flow.source}": [
    "Function{pysa._test_source}"
  ],
  "Function{closure.nonlocal_closure_no_flow}": [
    "Function{closure.nonlocal_closure_no_flow.sink}",
    "Function{closure.nonlocal_closure_no_flow.source}"
  ],
  "Function{closure.nonlocal_closure_obscure.sink}": [
    "Function{pysa._test_sink}"
  ],
  "Function{closure.nonlocal_closure_obscure.source}": [
    "Function{pysa._test_source}"
  ],
  "Function{closure.nonlocal_closure_read_reduction.inner}": [
    "Function{pysa._test_sink}"
  ],
  "Function{closure.nonlocal_closure_read_reduction}": [
    "Function{closure.nonlocal_closure_read_reduction.inner}",
    "Function{pysa._test_source}"
  ],
  "Function{closure.nonlocal_closure_reduction.sink}": [
    "Function{pysa._test_sink}"
  ],
  "Function{closure.nonlocal_closure_reduction.source}": [
    "Function{pysa._test_source}"
  ],
  "Function{closure.nonlocal_closure_reduction}": [
    "Function{closure.nonlocal_closure_reduction.sink}",
    "Function{closure.nonlocal_closure_reduction.source}",
    "Function{closure.nonlocal_closure_reduction.tito}"
  ],
  "Function{closure.nonlocal_closure_tito}": [
    "Function{closure.nonlocal_closure_tito.inner}",
    "Function{pysa._test_sink}", "Function{pysa._test_source}"
  ],
  "Function{closure.nonlocal_closure_wrapper_source_flow.source}": [
    "Function{pysa._test_source}"
  ],
  "Function{closure.nonlocal_closure_wrapper_source_flow.wrapper}": [
    "Function{closure.nonlocal_closure_wrapper_source_flow.source}"
  ],
  "Function{closure.nonlocal_closure_wrapper_source_flow}": [
    "Function{closure.nonlocal_closure_wrapper_source_flow.wrapper}",
    "Function{pysa._test_sink}"
  ],
  "Function{closure.nonlocal_closure_wrapper_source_max_trace_length.f1}": [
    "Function{closure.nonlocal_closure_wrapper_source_max_trace_length.source}"
  ],
  "Function{closure.nonlocal_closure_wrapper_source_max_trace_length.f2}": [
    "Function{closure.nonlocal_closure_wrapper_source_max_trace_length.f1}"
  ],
  "Function{closure.nonlocal_closure_wrapper_source_max_trace_length.f3}": [
    "Function{closure.nonlocal_closure_wrapper_source_max_trace_length.f2}"
  ],
  "Function{closure.nonlocal_closure_wrapper_source_max_trace_length.source}": [
    "Function{pysa._test_source}"
  ],
  "Function{closure.nonlocal_closure_wrapper_source_max_trace_length}": [
    "Function{closure.nonlocal_closure_wrapper_source_max_trace_length.f3}",
    "Function{pysa._test_sink}"
  ],
  "Function{closure.nonlocal_closure_write_reduction.source}": [
    "Function{pysa._test_source}"
  ],
  "Function{closure.nonlocal_closure_write_reduction}": [
    "Function{closure.nonlocal_closure_write_reduction.source}",
    "Function{pysa._test_sink}"
  ],
  "Function{closure.nonlocal_obscure_flow}": [
    "Function{closure.nonlocal_closure_obscure.sink}",
    "Function{closure.nonlocal_closure_obscure.source}",
    "Function{closure.nonlocal_closure_obscure}"
  ],
  "Function{closure.nonlocal_obscure_no_flow}": [
    "Function{closure.nonlocal_closure_obscure.sink}",
    "Function{closure.nonlocal_closure_obscure.source}",
    "Function{closure.nonlocal_closure_obscure}"
  ],
  "Function{closure.parameter_order_swap.inner}": [
    "Function{pysa._test_sink}"
  ],
  "Function{closure.parameter_order_swap_different_variable_names.inner}": [
    "Function{pysa._test_sink}"
  ],
  "Function{closure.parameter_order_swap_different_variable_names}": [
    "Function{closure.parameter_order_swap_different_variable_names.inner}"
  ],
  "Function{closure.parameter_order_swap_tito}": [
    "Function{closure.parameter_order_swap_tito.inner}",
    "Function{pysa._test_sink}", "Method{builtins.tuple.__getitem__}"
  ],
  "Function{closure.parameter_order_swap}": [
    "Function{closure.parameter_order_swap.inner}"
  ],
  "Function{closure.taint_propagation_hof}": [
    "Function{closure.wrapper_for_taint_propagation_hof}",
    "Function{pysa._test_source}"
  ],
  "Function{closure.taint_propagation}": [
    "Function{closure.wrapper_for_taint_propagation}",
    "Function{pysa._test_source}"
  ],
  "Function{closure.tito_hof}": [ "Function{pysa._test_sink}" ],
  "Function{closure.tito_hof}[formal(f, position=0)=Function{closure.wrapper_for_tito_propagation_hof.inner}]": [
    "Function{closure.wrapper_for_tito_propagation_hof.inner}",
    "Function{pysa._test_sink}"
  ],
  "Function{closure.tito_propagation_hof}": [
    "Function{closure.wrapper_for_tito_propagation_hof}",
    "Function{pysa._test_source}"
  ],
  "Function{closure.tito_propagation}": [
    "Function{closure.wrapper_for_tito_propagation}",
    "Function{pysa._test_source}"
  ],
  "Function{closure.wrapper_for_taint_propagation.inner}": [
    "Function{pysa._test_sink}"
  ],
  "Function{closure.wrapper_for_taint_propagation_hof.inner}": [
    "Function{pysa._test_sink}"
  ],
  "Function{closure.wrapper_for_taint_propagation_hof}": [
    "Function{closure.higher_order_function}[formal(f, position=0)=Function{closure.wrapper_for_taint_propagation_hof.inner}]"
  ],
  "Function{closure.wrapper_for_taint_propagation}": [
    "Function{closure.wrapper_for_taint_propagation.inner}"
  ],
  "Function{closure.wrapper_for_tito_propagation_hof}": [
    "Function{closure.tito_hof}[formal(f, position=0)=Function{closure.wrapper_for_tito_propagation_hof.inner}]"
  ],
  "Function{closure.wrapper_for_tito_propagation}": [
    "Function{closure.wrapper_for_tito_propagation.inner}",
    "Function{pysa._test_sink}"
  ]
}