@generated
Call dependencies
{
  "Function{closure_models.captured_variable_model_both_generation_parameter_source.model_all_captured_as_generation_and_parameter_sources}": [
    "Function{pysa._test_sink}"
  ],
  "Function{closure_models.captured_variable_model_both_generation_parameter_source}": [
    "Function{closure_models.captured_variable_model_both_generation_parameter_source.model_all_captured_as_generation_and_parameter_sources}",
    "Function{pysa._test_sink}"
  ],
  "Function{closure_models.captured_variable_model_generation_source.model_all_captured_as_generation_sources}": [
    "Function{pysa._test_sink}"
  ],
  "Function{closure_models.captured_variable_model_generation_source}": [
    "Function{closure_models.captured_variable_model_generation_source.model_all_captured_as_generation_sources}",
    "Function{pysa._test_sink}"
  ],
  "Function{closure_models.captured_variable_model_parameter_source.model_all_captured_as_parameter_sources}": [
    "Function{pysa._test_sink}"
  ],
  "Function{closure_models.captured_variable_model_parameter_source}": [
    "Function{closure_models.captured_variable_model_parameter_source.model_all_captured_as_parameter_sources}",
    "Function{pysa._test_sink}"
  ],
  "Function{closure_models.captured_variable_model_sink}": [
    "Function{closure_models.captured_variable_model_sink.model_all_captured_as_sinks}",
    "Function{pysa._test_source}"
  ],
  "Function{closure_models.captured_variable_model_tito}": [
    "Function{closure_models.captured_variable_model_tito.model_all_captured_as_tito}",
    "Function{pysa._test_sink}", "Function{pysa._test_source}"
  ],
  "Function{closure_models.inner_sink_wrapper}": [
    "Function{closure_models.inner_sink_wrapper.inner_sink}",
    "Function{pysa._test_source}"
  ],
  "Function{closure_models.test.return_model_query_tito}": [
    "Function{closure_models.use_source}"
  ],
  "Function{closure_models.test.return_model_taint_tito}": [
    "Function{closure_models.use_source}"
  ],
  "Function{closure_models.test.return_taint}": [
    "Function{pysa._test_source}"
  ],
  "Function{closure_models.test_dsl_decorator_source.decorated_local_function_capturing_local_variable@decorated}": [
    "Function{closure_models.some_decorator}[formal(func, position=0)=Function{closure_models.test_dsl_decorator_source.decorated_local_function_capturing_local_variable}]"
  ],
  "Function{closure_models.test_dsl_decorator_source.decorated_local_function_capturing_local_variable}": [
    "Function{pysa._test_sink}"
  ],
  "Function{closure_models.test_dsl_source.local_function_capturing_local_variable}": [
    "Function{pysa._test_sink}"
  ],
  "Function{closure_models.test_tito_transform.return_model_query_tito}": [
    "Function{closure_models.use_source}"
  ],
  "Function{closure_models.test_tito_transform.return_model_taint_tito}": [
    "Function{closure_models.use_source}"
  ],
  "Function{closure_models.test_tito_transform}": [
    "Function{closure_models.reclassify}",
    "Function{closure_models.test_tito_transform.return_model_query_tito}",
    "Function{closure_models.test_tito_transform.return_model_taint_tito}",
    "Function{pysa._test_source}",
    "Method{closure_models.Reclassification.reclassify}"
  ],
  "Function{closure_models.test}": [
    "Function{closure_models.outer}", "Function{closure_models.reclassify}",
    "Function{closure_models.test.return_model_query_tito}",
    "Function{closure_models.test.return_model_taint_tito}",
    "Function{closure_models.test.return_model_taint}",
    "Function{closure_models.test.return_taint}",
    "Function{pysa._test_source}",
    "Method{closure_models.Reclassification.reclassify}"
  ]
}