@generated
Call dependencies
{
  "Function{constructors.SomeAPI.$class_toplevel}": [
    "Method{builtins.str.__format__}"
  ],
  "Function{constructors.test_both_new_and_init_callgraph}": [
    "Method{constructors.BothNewAndInit.__init__}",
    "Method{constructors.BothNewAndInit.__new__}"
  ],
  "Function{constructors.test_class_stub}": [
    "Function{pysa._test_sink}", "Function{pysa._test_source}",
    "Method{builtins.object.__init__}", "Method{builtins.object.__new__}"
  ],
  "Function{constructors.test_construction}": [
    "Method{builtins.dict.__getitem__}",
    "Method{constructors.SomeAPI.async_get_authenticated_user}",
    "Method{constructors.SomeAPI.from_default_keys}"
  ],
  "Function{constructors.test_constructor_with_source_model}": [
    "Function{pysa._test_sink}", "Method{builtins.object.__new__}",
    "Method{constructors.ConstructorWithSourceModel.__init__}"
  ],
  "Function{constructors.test_constructor_with_tito_model_query}": [
    "Function{pysa._test_sink}", "Function{pysa._test_source}",
    "Method{builtins.object.__new__}",
    "Method{constructors.DerivedConstructorTitoModelQuery.__init__}"
  ],
  "Function{constructors.test_constructor_with_tito_model}": [
    "Function{pysa._test_sink}", "Function{pysa._test_source}",
    "Method{builtins.object.__new__}",
    "Method{constructors.DerivedConstructorWithTitoModel.__init__}"
  ],
  "Function{constructors.test_init_model}": [
    "Function{pysa._test_sink}", "Function{pysa._test_source}",
    "Method{builtins.object.__new__}",
    "Method{constructors.InitWithModel.__init__}"
  ],
  "Function{constructors.test_new_model}": [
    "Function{pysa._test_sink}", "Function{pysa._test_source}",
    "Method{builtins.object.__init__}",
    "Method{constructors.NewWithModel.__new__}"
  ],
  "Function{constructors.test_new_thing}": [
    "Function{pysa._test_source}",
    "Method{constructors.ChildWithNew.__new__}",
    "Method{constructors.ParentWithInit.__init__}"
  ],
  "Function{constructors.test_parent_with_no_constructor}": [
    "Function{pysa._test_sink}", "Function{pysa._test_source}",
    "Method{builtins.object.__new__}",
    "Method{constructors.ParentWithNoConstructor.__init__}"
  ],
  "Function{constructors.test_parent_with_obscure_constructor}": [
    "Function{pysa._test_sink}", "Function{pysa._test_source}",
    "Method{builtins.object.__new__}",
    "Method{constructors.ParentWithObscureConstructor.__init__}"
  ],
  "Function{constructors.test_source_in_constructor}": [
    "Function{pysa._test_sink}", "Method{builtins.object.__new__}",
    "Method{constructors.SourceInConstructor.__init__}"
  ],
  "Method{constructors.BaseConstructor.__init__}": [
    "Function{pysa._test_source}"
  ],
  "Method{constructors.BothNewAndInit.__init__}": [
    "Function{pysa._test_sink}"
  ],
  "Method{constructors.BothNewAndInit.__new__}": [
    "Function{pysa._test_source}", "Method{builtins.object.__new__}",
    "Method{builtins.super.__init__}"
  ],
  "Method{constructors.ChildWithNew.__new__}": [
    "Function{pysa._test_sink}", "Method{builtins.object.__new__}"
  ],
  "Method{constructors.DerivedConstructor.__init__}": [
    "Method{builtins.object.__new__}", "Method{builtins.super.__init__}",
    "Method{constructors.BaseConstructor.__init__}"
  ],
  "Method{constructors.DerivedConstructorTitoModelQuery.__init__}": [
    "Method{builtins.object.__new__}", "Method{builtins.super.__init__}",
    "Method{constructors.ConstructorTitoModelQuery.__init__}"
  ],
  "Method{constructors.DerivedConstructorWithTitoModel.__init__}": [
    "Method{builtins.object.__new__}", "Method{builtins.super.__init__}",
    "Method{constructors.ConstructorWithTitoModel.__init__}"
  ],
  "Method{constructors.ParentWithNoConstructor.__init__}": [
    "Method{builtins.object.__new__}", "Method{builtins.super.__init__}"
  ],
  "Method{constructors.ParentWithObscureConstructor.__init__}": [
    "Method{builtins.object.__new__}", "Method{builtins.super.__init__}",
    "Method{constructors.ConstructorObscure.__init__}"
  ],
  "Method{constructors.SanitizeReturn.__init__}": [
    "Function{pysa._test_source}"
  ],
  "Method{constructors.SanitizeSingleTraceSource.__init__}": [
    "Function{pysa._test_source}"
  ],
  "Method{constructors.SanitizeTitoKindSpecific.__init__}": [
    "Function{pysa._test_source}"
  ],
  "Method{constructors.SomeAPI.async_get_authenticated_user}": [
    "Function{builtins.eval}"
  ],
  "Method{constructors.SomeAPI.from_default_keys}": [
    "Method{builtins.object.__new__}",
    "Method{constructors.SomeAPI.__init__}"
  ],
  "Method{constructors.SourceInConstructor.__init__}": [
    "Function{pysa._test_source}"
  ]
}