@generated
Call dependencies
{
  "Function{constant_fields.test_untracked_constant}": [
    "Function{pysa._test_source}", "Method{builtins.dict.__getitem__}",
    "Method{builtins.dict.__setitem__}"
  ],
  "Function{constant_fields.tracked_constant_A}": [
    "Function{pysa._test_source}", "Method{builtins.dict.__getitem__}",
    "Method{builtins.dict.__setitem__}"
  ],
  "Function{constant_fields.tracked_constant_B}": [
    "Function{pysa._test_source}", "Method{builtins.dict.__getitem__}",
    "Method{builtins.dict.__setitem__}"
  ],
  "Function{constant_fields.tracked_index}": [
    "Function{pysa._test_source}", "Method{builtins.dict.__getitem__}",
    "Method{builtins.dict.__setitem__}"
  ],
  "Function{constant_fields.untracked_index_a}": [
    "Function{pysa._test_source}", "Method{builtins.dict.__getitem__}",
    "Method{builtins.dict.__setitem__}"
  ],
  "Function{constant_fields.untracked_index_b}": [
    "Function{pysa._test_source}", "Method{builtins.dict.__getitem__}",
    "Method{builtins.dict.__setitem__}"
  ]
}