@generated
Call dependencies
{
  "Function{context_manager.source_on_enter_and_sink_on_exit}": [
    "Function{pysa._test_sink}", "Function{pysa._test_source}"
  ],
  "Function{context_manager.test_generator_sink_on_exit}": [
    "Function{context_manager.source_on_enter_and_sink_on_exit}",
    "Function{pysa._test_sink}", "Function{pysa._test_source}",
    "Method{contextlib.AbstractContextManager.__enter__}"
  ],
  "Function{context_manager.test_generator_source_on_enter}": [
    "Function{context_manager.source_on_enter_and_sink_on_exit}",
    "Function{pysa._test_sink}",
    "Method{contextlib.AbstractContextManager.__enter__}"
  ],
  "Function{context_manager.test_sink_on_enter}": [
    "Method{builtins.object.__new__}",
    "Method{context_manager.SinkOnEnter.__enter__}",
    "Method{context_manager.SinkOnEnter.__init__}"
  ],
  "Function{context_manager.test_source_on_enter_as}": [
    "Function{pysa._test_sink}", "Method{builtins.object.__new__}",
    "Method{context_manager.SourceOnEnter.__enter__}",
    "Method{context_manager.SourceOnEnter.__init__}"
  ],
  "Function{context_manager.test_source_on_enter_clear}": [
    "Function{pysa._test_sink}", "Method{builtins.object.__new__}",
    "Method{context_manager.SourceOnEnter.__enter__}",
    "Method{context_manager.SourceOnEnter.__init__}"
  ],
  "Function{context_manager.test_source_on_enter}": [
    "Function{pysa._test_sink}", "Method{builtins.object.__new__}",
    "Method{context_manager.SourceOnEnter.__enter__}",
    "Method{context_manager.SourceOnEnter.__init__}"
  ],
  "Function{context_manager.test_source_on_exit}": [
    "Function{pysa._test_sink}", "Method{builtins.object.__new__}",
    "Method{context_manager.SourceOnExit.__enter__}",
    "Method{context_manager.SourceOnExit.__init__}"
  ],
  "Method{context_manager.SinkOnEnter.__enter__}": [
    "Function{pysa._test_sink}"
  ],
  "Method{context_manager.SourceOnEnter.__enter__}": [
    "Function{pysa._test_source}"
  ],
  "Method{context_manager.SourceOnExit.__exit__}": [
    "Function{pysa._test_source}"
  ]
}