@generated
Call dependencies
{
  "Function{cross_repository.cross_repository_source}": [
    "Function{pysa._test_sink}"
  ],
  "Function{cross_repository.test_cross_repository_anchor}": [
    "Function{cross_repository.cross_repository_anchor_sink}",
    "Function{pysa._test_source}"
  ],
  "Function{cross_repository.test_propagate_cross_repository_sink_once}": [
    "Function{cross_repository.reaches_crtex_sink}"
  ],
  "Function{cross_repository.test_propagate_cross_repository_sink_twice}": [
    "Function{cross_repository.test_propagate_cross_repository_sink_once}"
  ],
  "Function{cross_repository.test_propagate_cross_repository_source_once}": [
    "Function{cross_repository.returns_crtex_source}"
  ],
  "Function{cross_repository.test_propagate_cross_repository_source_twice}": [
    "Function{cross_repository.test_propagate_cross_repository_source_once}"
  ],
  "Function{cross_repository.test}": [
    "Function{cross_repository.returns_crtex_source}",
    "Function{pysa._test_sink}"
  ]
}