@generated
Call dependencies
{
  "Function{custom_dictionary_model.sink_dictionary_key}": [
    "Function{custom_dictionary_model._test_source_2}",
    "Method{builtins.dict.__setitem__}"
  ],
  "Function{custom_dictionary_model.sink_dictionary_value}": [
    "Function{custom_dictionary_model._test_source_2}",
    "Method{builtins.dict.__setitem__}"
  ],
  "Function{custom_dictionary_model.tainted_dictionary_key_sink}": [
    "Function{pysa._test_sink}", "Function{pysa._test_source}",
    "Method{builtins.dict.__setitem__}"
  ],
  "Function{custom_dictionary_model.tainted_dictionary_value_sink}": [
    "Function{pysa._test_sink}", "Function{pysa._test_source}",
    "Method{builtins.dict.__setitem__}"
  ],
  "Function{custom_dictionary_model.untainted_dictionary}": [
    "Function{pysa._test_sink}", "Method{builtins.dict.__setitem__}"
  ]
}