@generated
Call dependencies
{
  "Function{dataclass_taint.$toplevel}": [
    "Function{dataclasses.dataclass}"
  ],
  "Function{dataclass_taint.bad_is_tainted}": [
    "Function{pysa._test_sink}", "Function{pysa._test_source}",
    "Method{builtins.object.__new__}",
    "Method{dataclass_taint.DataClass.__init__}"
  ],
  "Function{dataclass_taint.benign_is_untainted}": [
    "Function{pysa._test_sink}", "Function{pysa._test_source}",
    "Method{builtins.object.__new__}",
    "Method{dataclass_taint.DataClass.__init__}"
  ],
  "Function{dataclass_taint.issue_in_dataclass_constructor}": [
    "Function{pysa._test_source}", "Method{builtins.object.__new__}",
    "Method{dataclass_taint.DataClassWIthInit.__init__}"
  ],
  "Function{dataclass_taint.issue_with_weird_dataclass}": [
    "Function{pysa._test_sink}", "Method{builtins.object.__new__}",
    "Method{dataclass_taint.WeirdDataClass.__init__}"
  ],
  "Function{dataclass_taint.test_class_attr_model_tainted_directly}": [
    "ClassInstanceAttribute{dataclass_taint.DataClassWithClassAttributeTaintedDirectly.bad}",
    "Function{pysa._test_source}", "Method{builtins.object.__new__}",
    "Method{dataclass_taint.DataClassWithClassAttributeTaintedDirectly.__init__}"
  ],
  "Function{dataclass_taint.test_class_attr_model_tainted_in_constructor}": [
    "Function{pysa._test_source}", "Method{builtins.object.__new__}",
    "Method{dataclass_taint.DataClassWithClassAttributeTaintedInConstructor.__init__}"
  ],
  "Function{dataclass_taint.test_constructor_tito}": [
    "Method{builtins.object.__new__}",
    "Method{dataclass_taint.DataClass.__init__}"
  ],
  "Function{dataclass_taint.test_dataclass_parameter_path}": [
    "Function{pysa._test_sink}"
  ],
  "Function{dataclass_taint.test_dataclass_positional_parameter}": [
    "Function{pysa._test_sink}", "Method{builtins.object.__new__}",
    "Method{dataclass_taint.DataClass.__init__}"
  ],
  "Function{dataclass_taint.test_dataclass_with_other_source}": [
    "ClassInstanceAttribute{dataclass_taint.DataClassWithOtherSource.tainted}",
    "Function{pysa._test_sink}"
  ],
  "Function{dataclass_taint.test_dataclass_with_source}": [
    "ClassInstanceAttribute{dataclass_taint.DataClassWithSource.tainted}",
    "Function{pysa._test_sink}"
  ],
  "Function{dataclass_taint.test_weird_dataclass_taint}": [
    "Method{builtins.object.__new__}",
    "Method{dataclass_taint.WeirdDataClass.__init__}"
  ],
  "Method{dataclass_taint.DataClassWIthInit.__init__}": [
    "Function{pysa._test_sink}"
  ],
  "Method{dataclass_taint.WeirdDataClass.__init__}": [
    "ClassInstanceAttribute{dataclass_taint.WeirdDataClass.bad_sink}",
    "Method{builtins.object.__setattr__}"
  ]
}