@generated
Call dependencies
{
  "Function{deadcode.dead_code_by_type_refinement}": [
    "Function{builtins.isinstance}", "Function{builtins.print}",
    "Function{pysa._test_sink}", "Method{deadcode.MyCallable.__call__}"
  ],
  "Function{deadcode.early_break_no_issue_for}": [
    "Function{pysa._test_sink}", "Function{pysa._test_source}",
    "Method{builtins.object.__init__}", "Method{builtins.range.__iter__}",
    "Method{builtins.range.__new__}", "Method{typing.Iterator.__next__}"
  ],
  "Function{deadcode.early_break_no_issue_while}": [
    "Function{pysa._test_sink}", "Function{pysa._test_source}"
  ],
  "Function{deadcode.early_continue_no_issue_for}": [
    "Function{pysa._test_sink}", "Function{pysa._test_source}",
    "Method{builtins.object.__init__}", "Method{builtins.range.__iter__}",
    "Method{builtins.range.__new__}", "Method{typing.Iterator.__next__}"
  ],
  "Function{deadcode.early_raise_no_issue}": [
    "Function{pysa._test_sink}", "Function{pysa._test_source}",
    "Method{builtins.BaseException.__init__}",
    "Method{builtins.BaseException.__new__}"
  ],
  "Function{deadcode.early_return_no_issue_class}": [
    "Function{pysa._test_sink}", "Function{pysa._test_source}",
    "Method{builtins.object.__new__}",
    "Method{deadcode.EarlyReturns.__init__}"
  ],
  "Function{deadcode.early_return_no_issue_for_else}": [
    "Function{pysa._test_sink}", "Function{pysa._test_source}"
  ],
  "Function{deadcode.early_return_no_issue_if}": [
    "Function{pysa._test_sink}", "Function{pysa._test_source}"
  ],
  "Function{deadcode.early_return_no_issue_while}": [
    "Function{pysa._test_sink}", "Function{pysa._test_source}"
  ],
  "Function{deadcode.early_return_no_issue}": [
    "Function{pysa._test_sink}", "Function{pysa._test_source}"
  ],
  "Function{deadcode.early_return_no_sink}": [ "Function{pysa._test_sink}" ],
  "Function{deadcode.early_return_no_source}": [
    "Function{pysa._test_source}"
  ],
  "Method{deadcode.EarlyReturns.__init__}": [
    "Function{pysa._test_sink}", "Function{pysa._test_source}"
  ]
}