@generated
Call dependencies
{
  "Function{decorator._strip_first_parameter_.inner}[captured_variable(f, decorator._strip_first_parameter_)=Function{decorator.decorated}]": [
    "Function{decorator.decorated}"
  ],
  "Function{decorator.add_return_source.inner}": [
    "Function{pysa._test_source}", "Method{_random.Random.random}",
    "Method{builtins.float.__gt__}"
  ],
  "Function{decorator.add_return_source.inner}[captured_variable(callable, decorator.add_return_source)=Function{decorator.return_source_via_decorator}]": [
    "Function{decorator.return_source_via_decorator}",
    "Function{pysa._test_source}", "Method{_random.Random.random}",
    "Method{builtins.float.__gt__}"
  ],
  "Function{decorator.conditional_decorator_factory.add_sink.inner}": [
    "Function{pysa._test_sink}"
  ],
  "Function{decorator.conditional_decorator_factory.add_sink.inner}[captured_variable(f, decorator.conditional_decorator_factory.add_sink)=Function{decorator.sink_via_conditional_decorator_factory}]": [
    "Function{decorator.sink_via_conditional_decorator_factory}",
    "Function{pysa._test_sink}"
  ],
  "Function{decorator.decorated@decorated}": [
    "Function{decorator._strip_first_parameter_}[formal(f, position=0)=Function{decorator.decorated}]"
  ],
  "Function{decorator.decorated}": [ "Function{pysa._test_sink}" ],
  "Function{decorator.doubly_decorated_logging@decorated}": [
    "Function{decorator.simple_wrapper}[formal(f, position=0)=Function{decorator.doubly_decorated_logging}]"
  ],
  "Function{decorator.foo@decorated}": [
    "Function{decorator.with_logging}[formal(f, position=0)=Function{decorator.foo}]"
  ],
  "Function{decorator.foo_args_kwargs@decorated}": [
    "Function{decorator.with_logging_args_kwargs}[formal(f, position=0)=Function{decorator.foo_args_kwargs}]"
  ],
  "Function{decorator.foo_args_kwargs_with_sink@decorated}": [
    "Function{decorator.with_logging_args_kwargs_no_sink}[formal(f, position=0)=Function{decorator.foo_args_kwargs_with_sink}]"
  ],
  "Function{decorator.foo_args_kwargs_with_sink}": [
    "Function{pysa._test_sink}"
  ],
  "Function{decorator.foo_args_kwargs}": [ "Function{builtins.print}" ],
  "Function{decorator.foo_async@decorated}": [
    "Function{decorator.with_logging_async}[formal(f, position=0)=Function{decorator.foo_async}]"
  ],
  "Function{decorator.foo_async}": [ "Function{builtins.print}" ],
  "Function{decorator.foo_log_first_parameter@decorated}": [
    "Function{decorator.with_logging_first_parameter}[formal(f, position=0)=Function{decorator.foo_log_first_parameter}]"
  ],
  "Function{decorator.foo_log_first_parameter}": [
    "Function{builtins.print}"
  ],
  "Function{decorator.foo_using_decorator_factory@decorated}": [
    "Function{decorator.with_named_logger._inner_decorator}[formal(f, position=0)=Function{decorator.foo_using_decorator_factory}]",
    "Function{decorator.with_named_logger}"
  ],
  "Function{decorator.foo_using_decorator_factory}": [
    "Function{builtins.print}"
  ],
  "Function{decorator.foo_with_helper_function@decorated}": [
    "Function{decorator.with_logging_helper_functions}[formal(f, position=0)=Function{decorator.foo_with_helper_function}]"
  ],
  "Function{decorator.foo_with_helper_function}": [
    "Function{builtins.print}"
  ],
  "Function{decorator.foo_with_shady_decorators@decorated}": [
    "Function{decorator.fails_to_apply}[formal(f, position=0)=Function{decorator.foo_with_shady_decorators}]",
    "Function{decorator.fails_to_apply}[formal(f, position=0)=Function{decorator.with_logging_sink.inner}[captured_variable(callable, decorator.with_logging_sink)=Function{decorator.foo_with_shady_decorators}]]",
    "Function{decorator.fails_to_apply}[formal(f, position=0)=Function{decorator.with_logging_source.inner}[captured_variable(callable, decorator.with_logging_source)=Function{decorator.with_logging_sink.inner}[captured_variable(callable, decorator.with_logging_sink)=Function{decorator.foo_with_shady_decorators}]]]",
    "Function{decorator.with_logging_sink}[formal(callable, position=0)=Function{decorator.foo_with_shady_decorators}]",
    "Function{decorator.with_logging_source}[formal(callable, position=0)=Function{decorator.with_logging_sink.inner}[captured_variable(callable, decorator.with_logging_sink)=Function{decorator.foo_with_shady_decorators}]]"
  ],
  "Function{decorator.foo_with_shady_decorators}": [
    "Function{builtins.print}"
  ],
  "Function{decorator.foo_with_sink@decorated}": [
    "Function{decorator.with_logging_no_sink}[formal(f, position=0)=Function{decorator.foo_with_sink}]"
  ],
  "Function{decorator.foo_with_sink}": [
    "Function{builtins.print}", "Function{pysa._test_sink}"
  ],
  "Function{decorator.foo}": [ "Function{builtins.print}" ],
  "Function{decorator.issue_str_wrapper}": [
    "Function{pysa._test_source}", "Method{builtins.object.__new__}",
    "Method{decorator.StringWrapper.__add__}",
    "Method{decorator.StringWrapper.__init__}"
  ],
  "Function{decorator.issue_via_conditional_decorator_factory}": [
    "Function{decorator.conditional_decorator_factory.add_sink.inner}[captured_variable(f, decorator.conditional_decorator_factory.add_sink)=Function{decorator.sink_via_conditional_decorator_factory}]",
    "Function{decorator.sink_via_conditional_decorator_factory}",
    "Function{pysa._test_source}"
  ],
  "Function{decorator.issue_via_conditional_no_op_decorator_factory}": [
    "Function{decorator.sink_via_conditional_no_op_decorator_factory}",
    "Function{pysa._test_source}"
  ],
  "Function{decorator.issue_via_no_op_decorator_factory}": [
    "Function{decorator.sink_via_no_op_decorator_factory}",
    "Function{pysa._test_source}"
  ],
  "Function{decorator.issue_via_no_op_decorator}": [
    "Function{decorator.sink_via_no_op_decorator}",
    "Function{pysa._test_source}"
  ],
  "Function{decorator.issue_via_trivial_decorator}": [
    "Function{decorator.trivial_decorator.inner}[captured_variable(f, decorator.trivial_decorator)=Function{decorator.sink_via_trivial_decorator}]",
    "Function{pysa._test_source}"
  ],
  "Function{decorator.main}": [
    "Function{decorator.foo_using_decorator_factory}",
    "Function{decorator.with_logging.inner}[captured_variable(f, decorator.with_logging)=Function{decorator.foo}]",
    "Function{decorator.with_logging_args_kwargs.inner}[captured_variable(f, decorator.with_logging_args_kwargs)=Function{decorator.foo_args_kwargs}]",
    "Function{decorator.with_logging_args_kwargs_no_sink.inner}[captured_variable(f, decorator.with_logging_args_kwargs_no_sink)=Function{decorator.foo_args_kwargs_with_sink}]",
    "Function{decorator.with_logging_args_kwargs_no_sink.inner}[captured_variable(f, decorator.with_logging_args_kwargs_no_sink)=Function{decorator.with_logging_args_kwargs.inner}[captured_variable(f, decorator.with_logging_args_kwargs)=Method{decorator.Foo.bar}]]",
    "Function{decorator.with_logging_args_kwargs_no_sink.inner}[captured_variable(f, decorator.with_logging_args_kwargs_no_sink)=Method{decorator.Foo.foo}]",
    "Function{decorator.with_logging_args_kwargs_no_sink.inner}[captured_variable(f, decorator.with_logging_args_kwargs_no_sink)=Method{decorator.Foo.self_has_generic_type}]",
    "Function{decorator.with_logging_args_kwargs_no_sink.inner}[captured_variable(f, decorator.with_logging_args_kwargs_no_sink)=Method{decorator.Foo.some_class_method}]",
    "Function{decorator.with_logging_async.inner}[captured_variable(f, decorator.with_logging_async)=Function{decorator.foo_async}]",
    "Function{decorator.with_logging_first_parameter.inner}[captured_variable(f, decorator.with_logging_first_parameter)=Function{decorator.foo_log_first_parameter}]",
    "Function{decorator.with_logging_helper_functions.inner}[captured_variable(f, decorator.with_logging_helper_functions)=Function{decorator.foo_with_helper_function}]",
    "Function{decorator.with_logging_no_sink.inner}[captured_variable(f, decorator.with_logging_no_sink)=Function{decorator.foo_with_sink}]",
    "Function{decorator.with_logging_source.inner}[captured_variable(callable, decorator.with_logging_source)=Function{decorator.with_logging_sink.inner}[captured_variable(callable, decorator.with_logging_sink)=Function{decorator.foo_with_shady_decorators}]]",
    "Function{decorator.with_named_logger._inner_decorator.inner}[captured_variable(f, decorator.with_named_logger._inner_decorator)=Function{decorator.foo_using_decorator_factory}]",
    "Function{pysa._test_source}", "Method{builtins.object.__init__}",
    "Method{builtins.object.__new__}"
  ],
  "Function{decorator.return_source_via_decorator@decorated}": [
    "Function{decorator.add_return_source}[formal(callable, position=0)=Function{decorator.return_source_via_decorator}]"
  ],
  "Function{decorator.returns_function_decorator.replacement}": [
    "Function{pysa._test_sink}"
  ],
  "Function{decorator.second_parameter_source_inlineable_decorator@decorated}": [
    "Function{decorator.trivial_decorator}[formal(f, position=0)=Function{decorator.second_parameter_source_inlineable_decorator}]"
  ],
  "Function{decorator.second_parameter_source_inlineable_decorator_with_inner.inner}": [
    "Function{pysa._test_sink}"
  ],
  "Function{decorator.second_parameter_source_inlineable_decorator_with_inner@decorated}": [
    "Function{decorator.trivial_decorator}[formal(f, position=0)=Function{decorator.second_parameter_source_inlineable_decorator_with_inner}]"
  ],
  "Function{decorator.second_parameter_source_inlineable_decorator_with_inner}": [
    "Function{decorator.second_parameter_source_inlineable_decorator_with_inner.inner}"
  ],
  "Function{decorator.second_parameter_source_inlineable_decorator}": [
    "Function{pysa._test_sink}"
  ],
  "Function{decorator.second_parameter_source_with_non_inlineable_decorator@decorated}": [
    "Function{decorator.discard_second_parameter_non_inlineable}[formal(f, position=0)=Function{decorator.second_parameter_source_with_non_inlineable_decorator}]"
  ],
  "Function{decorator.second_parameter_source_with_non_inlineable_decorator}": [
    "Function{pysa._test_sink}"
  ],
  "Function{decorator.simple_wrapper.inner}[captured_variable(f, decorator.simple_wrapper)=Function{decorator.doubly_decorated_logging}]": [
    "Function{decorator.doubly_decorated_logging}"
  ],
  "Function{decorator.simple_wrapper.inner}[captured_variable(f, decorator.simple_wrapper)=Method{decorator.Foo.sink_method} (bound)]": [
    "Method{decorator.Foo.sink_method}"
  ],
  "Function{decorator.simple_wrapper.inner}[captured_variable(f, decorator.simple_wrapper)=Method{decorator.Foo.sink_method}]": [
    "Method{decorator.Foo.sink_method}"
  ],
  "Function{decorator.sink_via_conditional_decorator_factory@decorated}": [
    "Function{decorator.conditional_decorator_factory.add_sink}[formal(f, position=0)=Function{decorator.sink_via_conditional_decorator_factory}]",
    "Function{decorator.conditional_decorator_factory.identity}[formal(f, position=0)=Function{decorator.sink_via_conditional_decorator_factory}]",
    "Function{decorator.conditional_decorator_factory}"
  ],
  "Function{decorator.sink_via_conditional_decorator_factory}": [
    "Function{builtins.print}"
  ],
  "Function{decorator.sink_via_conditional_no_op_decorator_factory@decorated}": [
    "Function{decorator.conditional_no_op_decorator_factory.inner_false}[formal(f, position=0)=Function{decorator.sink_via_conditional_no_op_decorator_factory}]",
    "Function{decorator.conditional_no_op_decorator_factory.inner_true}[formal(f, position=0)=Function{decorator.sink_via_conditional_no_op_decorator_factory}]",
    "Function{decorator.conditional_no_op_decorator_factory}"
  ],
  "Function{decorator.sink_via_conditional_no_op_decorator_factory}": [
    "Function{pysa._test_sink}"
  ],
  "Function{decorator.sink_via_doubly_decorated@decorated}": [
    "Function{decorator.simple_wrapper.inner}[captured_variable(f, decorator.simple_wrapper)=Function{decorator.doubly_decorated_logging}]"
  ],
  "Function{decorator.sink_via_doubly_decorated}": [
    "Function{pysa._test_sink}"
  ],
  "Function{decorator.sink_via_no_op_decorator@decorated}": [
    "Function{decorator.no_op_decorator}[formal(f, position=0)=Function{decorator.sink_via_no_op_decorator}]"
  ],
  "Function{decorator.sink_via_no_op_decorator_factory@decorated}": [
    "Function{decorator.no_op_decorator_factory.inner}[formal(f, position=0)=Function{decorator.sink_via_no_op_decorator_factory}]",
    "Function{decorator.no_op_decorator_factory}"
  ],
  "Function{decorator.sink_via_no_op_decorator_factory}": [
    "Function{pysa._test_sink}"
  ],
  "Function{decorator.sink_via_no_op_decorator}": [
    "Function{pysa._test_sink}"
  ],
  "Function{decorator.sink_via_trivial_decorator@decorated}": [
    "Function{decorator.trivial_decorator}[formal(f, position=0)=Function{decorator.sink_via_trivial_decorator}]"
  ],
  "Function{decorator.sink_via_trivial_decorator}": [
    "Function{pysa._test_sink}"
  ],
  "Function{decorator.test_add_decorated_returns_function}": [
    "Function{decorator.returns_function_decorator.replacement}",
    "Function{pysa._test_source}", "Method{builtins.object.__init__}",
    "Method{builtins.object.__new__}"
  ],
  "Function{decorator.test_add_decorated_returns_staticmethod}": [
    "Function{pysa._test_source}", "Method{builtins.object.__init__}",
    "Method{builtins.object.__new__}",
    "Method{decorator.StaticAddHolder.static_add}"
  ],
  "Function{decorator.test_decorated_call_in_assign_target}": [
    "Function{decorator.trivial_decorator.inner}[captured_variable(f, decorator.trivial_decorator)=Function{decorator.sink_via_trivial_decorator}]"
  ],
  "Function{decorator.test_decorated_call_in_lambda_default}": [
    "Function{decorator.trivial_decorator.inner}[captured_variable(f, decorator.trivial_decorator)=Function{decorator.sink_via_trivial_decorator}]",
    "Function{pysa._test_source}"
  ],
  "Function{decorator.test_decorated_call_in_tuple_assignment}": [
    "Function{decorator.trivial_decorator.inner}[captured_variable(f, decorator.trivial_decorator)=Function{decorator.sink_via_trivial_decorator}]",
    "Function{pysa._test_source}"
  ],
  "Function{decorator.test_decorated_higher_order_parameter.inner@decorated}": [
    "Function{decorator.with_logging_args_kwargs_no_sink}[formal(f, position=0)=Function{decorator.test_decorated_higher_order_parameter.inner}]"
  ],
  "Function{decorator.test_decorated_higher_order_parameter.inner}": [
    "Function{pysa._test_source}"
  ],
  "Function{decorator.test_decorated_higher_order_parameter}": [
    "Function{decorator.stub_callee}",
    "Function{decorator.with_logging_args_kwargs_no_sink.inner}[captured_variable(f, decorator.with_logging_args_kwargs_no_sink)=Function{decorator.test_decorated_higher_order_parameter.inner}]"
  ],
  "Function{decorator.test_decorator_bound}": [
    "Function{decorator.simple_wrapper.inner}[captured_variable(f, decorator.simple_wrapper)=Method{decorator.Foo.sink_method} (bound)]",
    "Function{decorator.simple_wrapper}[formal(f, position=0)=Method{decorator.Foo.sink_method} (bound)]",
    "Function{pysa._test_source}", "Method{builtins.object.__init__}",
    "Method{builtins.object.__new__}"
  ],
  "Function{decorator.test_decorator_unbound}": [
    "Function{decorator.simple_wrapper.inner}[captured_variable(f, decorator.simple_wrapper)=Method{decorator.Foo.sink_method}]",
    "Function{decorator.simple_wrapper}[formal(f, position=0)=Method{decorator.Foo.sink_method}]",
    "Function{pysa._test_source}", "Method{builtins.object.__init__}",
    "Method{builtins.object.__new__}"
  ],
  "Function{decorator.test_issue_via_doubly_decorated}": [
    "Function{decorator.sink_via_doubly_decorated}",
    "Function{pysa._test_source}"
  ],
  "Function{decorator.test_parameter_default_value}": [
    "Function{decorator.add_return_source.inner}[captured_variable(callable, decorator.add_return_source)=Function{decorator.return_source_via_decorator}]",
    "Function{pysa._test_sink}"
  ],
  "Function{decorator.trivial_decorator.inner}[captured_variable(f, decorator.trivial_decorator)=Function{decorator.sink_via_trivial_decorator}]": [
    "Function{decorator.sink_via_trivial_decorator}"
  ],
  "Function{decorator.using_decorated}": [
    "Function{decorator._strip_first_parameter_.inner}[captured_variable(f, decorator._strip_first_parameter_)=Function{decorator.decorated}]"
  ],
  "Function{decorator.with_logging.inner}": [ "Function{pysa._test_sink}" ],
  "Function{decorator.with_logging.inner}[captured_variable(f, decorator.with_logging)=Function{decorator.foo}]": [
    "Function{decorator.foo}", "Function{pysa._test_sink}"
  ],
  "Function{decorator.with_logging_args_kwargs.inner}": [
    "Function{pysa._test_sink}"
  ],
  "Function{decorator.with_logging_args_kwargs.inner}[captured_variable(f, decorator.with_logging_args_kwargs)=Function{decorator.foo_args_kwargs}]": [
    "Function{decorator.foo_args_kwargs}", "Function{pysa._test_sink}"
  ],
  "Function{decorator.with_logging_args_kwargs.inner}[captured_variable(f, decorator.with_logging_args_kwargs)=Method{decorator.Foo.bar}]": [
    "Function{pysa._test_sink}", "Method{decorator.Foo.bar}"
  ],
  "Function{decorator.with_logging_args_kwargs_no_sink.inner}[captured_variable(f, decorator.with_logging_args_kwargs_no_sink)=Function{decorator.foo_args_kwargs_with_sink}]": [
    "Function{decorator.foo_args_kwargs_with_sink}"
  ],
  "Function{decorator.with_logging_args_kwargs_no_sink.inner}[captured_variable(f, decorator.with_logging_args_kwargs_no_sink)=Function{decorator.test_decorated_higher_order_parameter.inner}]": [
    "Function{decorator.test_decorated_higher_order_parameter.inner}"
  ],
  "Function{decorator.with_logging_args_kwargs_no_sink.inner}[captured_variable(f, decorator.with_logging_args_kwargs_no_sink)=Function{decorator.with_logging_args_kwargs.inner}[captured_variable(f, decorator.with_logging_args_kwargs)=Method{decorator.Foo.bar}]]": [
    "Function{decorator.with_logging_args_kwargs.inner}[captured_variable(f, decorator.with_logging_args_kwargs)=Method{decorator.Foo.bar}]"
  ],
  "Function{decorator.with_logging_args_kwargs_no_sink.inner}[captured_variable(f, decorator.with_logging_args_kwargs_no_sink)=Method{decorator.Foo.foo}]": [
    "Method{decorator.Foo.foo}"
  ],
  "Function{decorator.with_logging_args_kwargs_no_sink.inner}[captured_variable(f, decorator.with_logging_args_kwargs_no_sink)=Method{decorator.Foo.self_has_generic_type}]": [
    "Method{decorator.Foo.self_has_generic_type}"
  ],
  "Function{decorator.with_logging_args_kwargs_no_sink.inner}[captured_variable(f, decorator.with_logging_args_kwargs_no_sink)=Method{decorator.Foo.some_class_method}]": [
    "Method{decorator.Foo.some_class_method}"
  ],
  "Function{decorator.with_logging_async.inner}": [
    "Function{builtins.isinstance}", "Function{pysa._test_sink}"
  ],
  "Function{decorator.with_logging_async.inner}[captured_variable(f, decorator.with_logging_async)=Function{decorator.foo_async}]": [
    "Function{builtins.isinstance}", "Function{decorator.foo_async}",
    "Function{pysa._test_sink}"
  ],
  "Function{decorator.with_logging_first_parameter.inner}": [
    "Function{pysa._test_sink}", "Method{builtins.int.__ne__}"
  ],
  "Function{decorator.with_logging_first_parameter.inner}[captured_variable(f, decorator.with_logging_first_parameter)=Function{decorator.foo_log_first_parameter}]": [
    "Function{decorator.foo_log_first_parameter}",
    "Function{pysa._test_sink}", "Method{builtins.int.__ne__}"
  ],
  "Function{decorator.with_logging_helper_functions.after}": [
    "Function{builtins.print}", "Function{pysa._test_sink}"
  ],
  "Function{decorator.with_logging_helper_functions.before}": [
    "Function{builtins.print}"
  ],
  "Function{decorator.with_logging_helper_functions.inner}": [
    "Function{builtins.isinstance}", "Function{builtins.print}",
    "Function{decorator.with_logging_helper_functions.after}",
    "Function{decorator.with_logging_helper_functions.before}"
  ],
  "Function{decorator.with_logging_helper_functions.inner}[captured_variable(f, decorator.with_logging_helper_functions)=Function{decorator.foo_with_helper_function}]": [
    "Function{builtins.isinstance}", "Function{builtins.print}",
    "Function{decorator.foo_with_helper_function}",
    "Function{decorator.with_logging_helper_functions.after}",
    "Function{decorator.with_logging_helper_functions.before}"
  ],
  "Function{decorator.with_logging_no_sink.inner}[captured_variable(f, decorator.with_logging_no_sink)=Function{decorator.foo_with_sink}]": [
    "Function{decorator.foo_with_sink}"
  ],
  "Function{decorator.with_logging_sink.inner}": [
    "Function{pysa._test_sink}"
  ],
  "Function{decorator.with_logging_sink.inner}[captured_variable(callable, decorator.with_logging_sink)=Function{decorator.foo_with_shady_decorators}]": [
    "Function{decorator.foo_with_shady_decorators}",
    "Function{pysa._test_sink}"
  ],
  "Function{decorator.with_logging_source.inner}": [
    "Function{pysa._test_source}", "Method{builtins.str.__add__}"
  ],
  "Function{decorator.with_logging_source.inner}[captured_variable(callable, decorator.with_logging_source)=Function{decorator.with_logging_sink.inner}[captured_variable(callable, decorator.with_logging_sink)=Function{decorator.foo_with_shady_decorators}]]": [
    "Function{decorator.with_logging_sink.inner}[captured_variable(callable, decorator.with_logging_sink)=Function{decorator.foo_with_shady_decorators}]",
    "Function{pysa._test_source}", "Method{builtins.str.__add__}"
  ],
  "Function{decorator.with_named_logger._inner_decorator.inner}": [
    "Function{builtins.print}", "Function{pysa._test_sink}"
  ],
  "Function{decorator.with_named_logger._inner_decorator.inner}[captured_variable(f, decorator.with_named_logger._inner_decorator)=Function{decorator.foo_using_decorator_factory}]": [
    "Function{builtins.print}",
    "Function{decorator.foo_using_decorator_factory}",
    "Function{pysa._test_sink}"
  ],
  "Method{decorator.AddReturnsFunction.__add__@decorated}": [
    "Function{decorator.returns_function_decorator}[formal(f, position=0)=Method{decorator.AddReturnsFunction.__add__}]"
  ],
  "Method{decorator.AddReturnsStaticmethod.__add__@decorated}": [
    "Function{decorator.returns_staticmethod_decorator}[formal(f, position=0)=Method{decorator.AddReturnsStaticmethod.__add__}]"
  ],
  "Method{decorator.Foo.bar@decorated}": [
    "Function{decorator.with_logging_args_kwargs_no_sink}[formal(f, position=0)=Function{decorator.with_logging_args_kwargs.inner}[captured_variable(f, decorator.with_logging_args_kwargs)=Method{decorator.Foo.bar}]]",
    "Function{decorator.with_logging_args_kwargs}[formal(f, position=0)=Method{decorator.Foo.bar}]"
  ],
  "Method{decorator.Foo.bar}": [ "Function{builtins.print}" ],
  "Method{decorator.Foo.foo@decorated}": [
    "Function{decorator.with_logging_args_kwargs_no_sink}[formal(f, position=0)=Method{decorator.Foo.foo}]"
  ],
  "Method{decorator.Foo.foo}": [ "Method{decorator.Foo.sink_method}" ],
  "Method{decorator.Foo.self_has_generic_type@decorated}": [
    "Function{decorator.with_logging_args_kwargs_no_sink}[formal(f, position=0)=Method{decorator.Foo.self_has_generic_type}]"
  ],
  "Method{decorator.Foo.self_has_generic_type}": [
    "Function{decorator.with_logging_args_kwargs_no_sink.inner}[captured_variable(f, decorator.with_logging_args_kwargs_no_sink)=Function{decorator.with_logging_args_kwargs.inner}[captured_variable(f, decorator.with_logging_args_kwargs)=Method{decorator.Foo.bar}]]"
  ],
  "Method{decorator.Foo.sink_method}": [
    "Function{builtins.print}", "Function{pysa._test_sink}"
  ],
  "Method{decorator.Foo.some_class_method@decorated}": [
    "Function{decorator.with_logging_args_kwargs_no_sink}[formal(f, position=0)=Method{decorator.Foo.some_class_method}]",
    "Method{builtins.classmethod.__init__}",
    "Method{builtins.object.__new__}"
  ],
  "Method{decorator.Foo.some_class_method}": [
    "Method{builtins.object.__init__}", "Method{builtins.object.__new__}",
    "Method{decorator.Foo.sink_method}"
  ],
  "Method{decorator.StaticAddHolder.static_add}": [
    "Function{pysa._test_sink}"
  ],
  "Method{decorator.StringWrapper.__add__@decorated}": [
    "Function{decorator.no_op_decorator}[formal(f, position=0)=Method{decorator.StringWrapper.__add__}]"
  ],
  "Method{decorator.StringWrapper.__add__}": [
    "Function{pysa._test_sink}", "Method{builtins.object.__new__}",
    "Method{builtins.str.__add__}",
    "Method{decorator.StringWrapper.__init__}"
  ]
}