@generated
Call dependencies
{
  "Function{decorator_location.call_return_foo}": [
    "Function{decorator_location.identity.inner}[captured_variable(f, decorator_location.identity)=Function{decorator_location.return_foo}]",
    "Function{pysa._test_sink}"
  ],
  "Function{decorator_location.decorated_ignore_then_skip_decorator}": [
    "Function{pysa._test_sink}"
  ],
  "Function{decorator_location.decorated_ignore_this_decorator_class}": [
    "Function{pysa._test_sink}"
  ],
  "Function{decorator_location.decorated_ignore_this_decorator_factory}": [
    "Function{pysa._test_sink}"
  ],
  "Function{decorator_location.decorated_ignore_this_decorator}": [
    "Function{pysa._test_sink}"
  ],
  "Function{decorator_location.decorated_logging2_skip_this_decorator@decorated}": [
    "Function{decorator_location.skip_this_decorator}",
    "Function{decorator_location.with_logging2}[formal(f, position=0)=Function{decorator_location.decorated_logging2_skip_this_decorator}]"
  ],
  "Function{decorator_location.decorated_logging2_skip_this_decorator}": [
    "Function{pysa._test_sink}"
  ],
  "Function{decorator_location.decorated_logging_ignore_this_decorator@decorated}": [
    "Function{decorator_location.ignore_this_decorator}",
    "Function{decorator_location.with_logging}[formal(f, position=0)=Function{decorator_location.decorated_logging_ignore_this_decorator}]"
  ],
  "Function{decorator_location.decorated_logging_ignore_this_decorator}": [
    "Function{pysa._test_sink}"
  ],
  "Function{decorator_location.decorated_logging_logging2@decorated}": [
    "Function{decorator_location.with_logging2}[formal(f, position=0)=Function{decorator_location.decorated_logging_logging2}]",
    "Function{decorator_location.with_logging}[formal(f, position=0)=Function{decorator_location.with_logging2.inner}[captured_variable(f, decorator_location.with_logging2)=Function{decorator_location.decorated_logging_logging2}]]"
  ],
  "Function{decorator_location.decorated_logging_logging2}": [
    "Function{pysa._test_sink}"
  ],
  "Function{decorator_location.decorated_skip_this_decorator}": [
    "Function{pysa._test_sink}"
  ],
  "Function{decorator_location.handle_request@decorated}": [
    "Function{decorator_location.pass_local_variable_to_x}[formal(f, position=0)=Function{decorator_location.handle_request}]"
  ],
  "Function{decorator_location.handle_request}": [
    "Function{pysa._test_sink}"
  ],
  "Function{decorator_location.identity.inner}[captured_variable(f, decorator_location.identity)=Function{decorator_location.return_foo}]": [
    "Function{decorator_location.return_foo}"
  ],
  "Function{decorator_location.ignore_this_decorator_factory.decorator.inner}": [
    "Method{builtins.int.__add__}"
  ],
  "Function{decorator_location.main}": [
    "Function{decorator_location.call_return_foo}",
    "Function{decorator_location.decorated_ignore_then_skip_decorator}",
    "Function{decorator_location.decorated_ignore_this_decorator_class}",
    "Function{decorator_location.decorated_ignore_this_decorator_factory}",
    "Function{decorator_location.decorated_ignore_this_decorator}",
    "Function{decorator_location.decorated_skip_this_decorator}",
    "Function{decorator_location.pass_local_variable_to_x.inner}[captured_variable(f, decorator_location.pass_local_variable_to_x)=Function{decorator_location.handle_request}]",
    "Function{decorator_location.with_logging.inner}[captured_variable(f, decorator_location.with_logging)=Function{decorator_location.decorated_logging_ignore_this_decorator}]",
    "Function{decorator_location.with_logging.inner}[captured_variable(f, decorator_location.with_logging)=Function{decorator_location.with_logging2.inner}[captured_variable(f, decorator_location.with_logging2)=Function{decorator_location.decorated_logging_logging2}]]",
    "Function{decorator_location.with_logging2.inner}[captured_variable(f, decorator_location.with_logging2)=Function{decorator_location.decorated_logging2_skip_this_decorator}]",
    "Function{pysa._test_source}"
  ],
  "Function{decorator_location.pass_local_variable_to_x.inner}": [
    "Function{pysa._test_sink}"
  ],
  "Function{decorator_location.pass_local_variable_to_x.inner}[captured_variable(f, decorator_location.pass_local_variable_to_x)=Function{decorator_location.handle_request}]": [
    "Function{decorator_location.handle_request}",
    "Function{pysa._test_sink}"
  ],
  "Function{decorator_location.return_foo@decorated}": [
    "Function{decorator_location.identity}[formal(f, position=0)=Function{decorator_location.return_foo}]"
  ],
  "Function{decorator_location.return_foo}": [
    "Method{builtins.object.__init__}", "Method{builtins.object.__new__}"
  ],
  "Function{decorator_location.skip_this_decorator.inner}": [
    "Function{pysa._test_sink}"
  ],
  "Function{decorator_location.with_logging.inner}": [
    "Function{decorator_location.with_logging.some_helper}",
    "Function{pysa._test_sink}"
  ],
  "Function{decorator_location.with_logging.inner}[captured_variable(f, decorator_location.with_logging)=Function{decorator_location.decorated_logging_ignore_this_decorator}]": [
    "Function{decorator_location.decorated_logging_ignore_this_decorator}",
    "Function{decorator_location.with_logging.some_helper}",
    "Function{pysa._test_sink}"
  ],
  "Function{decorator_location.with_logging.inner}[captured_variable(f, decorator_location.with_logging)=Function{decorator_location.with_logging2.inner}[captured_variable(f, decorator_location.with_logging2)=Function{decorator_location.decorated_logging_logging2}]]": [
    "Function{decorator_location.with_logging.some_helper}",
    "Function{decorator_location.with_logging2.inner}[captured_variable(f, decorator_location.with_logging2)=Function{decorator_location.decorated_logging_logging2}]",
    "Function{pysa._test_sink}"
  ],
  "Function{decorator_location.with_logging.some_helper}": [
    "Function{builtins.print}", "Function{pysa._test_sink}"
  ],
  "Function{decorator_location.with_logging2.inner}": [
    "Function{pysa._test_sink}"
  ],
  "Function{decorator_location.with_logging2.inner}[captured_variable(f, decorator_location.with_logging2)=Function{decorator_location.decorated_logging2_skip_this_decorator}]": [
    "Function{decorator_location.decorated_logging2_skip_this_decorator}",
    "Function{pysa._test_sink}"
  ],
  "Function{decorator_location.with_logging2.inner}[captured_variable(f, decorator_location.with_logging2)=Function{decorator_location.decorated_logging_logging2}]": [
    "Function{decorator_location.decorated_logging_logging2}",
    "Function{pysa._test_sink}"
  ],
  "Method{decorator_location.Foo.return_source}": [
    "Function{pysa._test_source}"
  ]
}