@generated
Call dependencies
{
  "Function{dictionary.analyze_getitem_index_backward}": [
    "Function{pysa._test_sink}", "Method{builtins.dict.__getitem__}"
  ],
  "Function{dictionary.analyze_getitem_index_issue}": [
    "Function{pysa._test_sink}", "Function{pysa._test_source}",
    "Method{builtins.dict.__getitem__}"
  ],
  "Function{dictionary.backward_weak_update}": [
    "Function{pysa._test_sink}", "Method{builtins.dict.__setitem__}",
    "Method{builtins.dict.keys}"
  ],
  "Function{dictionary.backwards_field_assignment}": [
    "Method{builtins.dict.__setitem__}"
  ],
  "Function{dictionary.backwards_model_for_dictionary_comprehension}": [
    "Function{dictionary.sink_dictionary_through_keys}"
  ],
  "Function{dictionary.big_dict_update_arg}": [
    "Function{pysa._test_source}", "Method{builtins.dict.__setitem__}",
    "Method{builtins.object.__init__}", "Method{builtins.range.__iter__}",
    "Method{builtins.range.__new__}", "Method{typing.Iterator.__next__}",
    "Method{typing.MutableMapping.update}"
  ],
  "Function{dictionary.copy_untainted_values_with_tainted_keys}": [
    "Function{pysa._test_source}", "Method{builtins.dict.__getitem__}",
    "Method{builtins.dict.__iter__}", "Method{builtins.dict.__setitem__}",
    "Method{typing.Iterator.__next__}"
  ],
  "Function{dictionary.dict_get_foo_with_default}": [
    "Method{builtins.dict.get}"
  ],
  "Function{dictionary.dict_get_foo}": [ "Method{builtins.dict.get}" ],
  "Function{dictionary.dict_getitem_mutate}": [
    "Method{builtins.dict.__getitem__}", "Method{builtins.dict.__setitem__}",
    "Method{builtins.object.__init__}", "Method{builtins.range.__iter__}",
    "Method{builtins.range.__new__}", "Method{builtins.str.__add__}",
    "Method{typing.Iterator.__next__}"
  ],
  "Function{dictionary.dict_only_key_of_parameter_sink}": [
    "Function{pysa._test_sink}", "Method{builtins.dict.__getitem__}",
    "Method{typing.MutableMapping.update}"
  ],
  "Function{dictionary.dict_update_keys}": [
    "Method{builtins.dict.items}", "Method{typing.ItemsView.__iter__}",
    "Method{typing.Iterator.__next__}"
  ],
  "Function{dictionary.dict_update_sinks_cycle}": [
    "Function{pysa._test_sink}", "Method{builtins.dict.__getitem__}",
    "Method{typing.MutableMapping.update}"
  ],
  "Function{dictionary.dict_update_source_cycle}": [
    "Function{pysa._test_source}", "Method{builtins.dict.__getitem__}",
    "Method{typing.MutableMapping.update}"
  ],
  "Function{dictionary.dict_update_with_expression_add_source}": [
    "Function{pysa._test_source}", "Method{typing.MutableMapping.update}"
  ],
  "Function{dictionary.dict_update_with_expression_erase_source}": [
    "Function{pysa._test_source}", "Method{typing.MutableMapping.update}"
  ],
  "Function{dictionary.dict_update_with_expression_tito}": [
    "Method{typing.MutableMapping.update}"
  ],
  "Function{dictionary.dict_update_with_literal_flows_to_sink}": [
    "Function{pysa._test_sink}", "Method{builtins.dict.__getitem__}",
    "Method{typing.MutableMapping.update}"
  ],
  "Function{dictionary.dict_update_with_literal_multiple}": [
    "Function{pysa._test_source}", "Method{typing.MutableMapping.update}"
  ],
  "Function{dictionary.dict_update_with_literal_safe_source}": [
    "Function{pysa._test_source}", "Method{typing.MutableMapping.update}"
  ],
  "Function{dictionary.dict_update_with_literal_source}": [
    "Function{pysa._test_source}", "Method{typing.MutableMapping.update}"
  ],
  "Function{dictionary.dict_with_tainted_key_flows_to_sink_via_setitem}": [
    "Function{pysa._test_sink}", "Function{pysa._test_source}",
    "Method{builtins.dict.__setitem__}"
  ],
  "Function{dictionary.dict_with_tainted_key_flows_to_sink}": [
    "Function{pysa._test_sink}", "Function{pysa._test_source}"
  ],
  "Function{dictionary.dictionary_assign_to_index}": [
    "Function{pysa._test_source}", "Method{builtins.dict.__setitem__}"
  ],
  "Function{dictionary.dictionary_assignment_source}": [
    "Function{pysa._test_source}", "Method{builtins.dict.__getitem__}",
    "Method{builtins.dict.__setitem__}"
  ],
  "Function{dictionary.dictionary_bool_key}": [
    "Function{pysa._test_sink}", "Function{pysa._test_source}",
    "Method{builtins.dict.__getitem__}"
  ],
  "Function{dictionary.dictionary_entry_sink}": [
    "Function{pysa._test_sink}"
  ],
  "Function{dictionary.dictionary_int_key}": [
    "Function{pysa._test_sink}", "Function{pysa._test_source}",
    "Method{builtins.dict.__getitem__}"
  ],
  "Function{dictionary.dictionary_keys_and_any_index_bug}": [
    "Function{dictionary.dict_update_keys}", "Function{pysa._test_sink}",
    "Method{builtins.dict.keys}"
  ],
  "Function{dictionary.dictionary_nested_assignment_1}": [
    "Function{pysa._test_source}", "Method{builtins.dict.__getitem__}"
  ],
  "Function{dictionary.dictionary_nested_assignment_2}": [
    "Function{pysa._test_source}", "Method{builtins.dict.__getitem__}"
  ],
  "Function{dictionary.dictionary_nested_non_source_assignment}": [
    "Function{pysa._test_source}", "Method{builtins.dict.__getitem__}"
  ],
  "Function{dictionary.dictionary_non_source}": [
    "Function{pysa._test_source}", "Method{builtins.dict.__getitem__}",
    "Method{builtins.dict.__setitem__}"
  ],
  "Function{dictionary.dictionary_source}": [ "Function{pysa._test_source}" ],
  "Function{dictionary.dictionary_tito_any_index}": [
    "Method{builtins.object.__init__}", "Method{builtins.range.__iter__}",
    "Method{builtins.range.__new__}", "Method{typing.Iterator.__next__}"
  ],
  "Function{dictionary.dictionary_update_iterable}": [
    "Function{pysa._test_sink}", "Function{pysa._test_source}",
    "Method{builtins.dict.__getitem__}",
    "Method{typing.MutableMapping.update}"
  ],
  "Function{dictionary.dictionary_update_keyword}": [
    "Function{pysa._test_sink}", "Function{pysa._test_source}",
    "Method{builtins.dict.__getitem__}",
    "Method{typing.MutableMapping.update}"
  ],
  "Function{dictionary.flow_through_keywords}": [
    "Function{pysa._test_sink}", "Function{pysa._test_source}",
    "Method{builtins.dict.__getitem__}"
  ],
  "Function{dictionary.forward_comprehension_key_sink}": [
    "Function{pysa._test_sink}", "Method{builtins.list.__iter__}",
    "Method{typing.Iterator.__next__}"
  ],
  "Function{dictionary.forward_comprehension_key_source}": [
    "Function{pysa._test_source}", "Method{builtins.list.__iter__}",
    "Method{typing.Iterator.__next__}"
  ],
  "Function{dictionary.forward_comprehension_value_sink}": [
    "Function{pysa._test_sink}", "Method{builtins.list.__iter__}",
    "Method{typing.Iterator.__next__}"
  ],
  "Function{dictionary.forward_comprehension_value_source}": [
    "Function{pysa._test_source}", "Method{builtins.list.__iter__}",
    "Method{typing.Iterator.__next__}"
  ],
  "Function{dictionary.forward_weak_update}": [
    "Function{pysa._test_source}", "Method{builtins.dict.__setitem__}"
  ],
  "Function{dictionary.get_keys}": [
    "Method{builtins.dict.__iter__}", "Method{typing.Iterator.__next__}"
  ],
  "Function{dictionary.indirect_flow_from_source_to_global_dictionary}": [
    "Function{dictionary.update_dictionary_indirectly}",
    "Function{pysa._test_source}"
  ],
  "Function{dictionary.issue_in_keys}": [
    "Function{dictionary.backward_weak_update}", "Function{pysa._test_sink}",
    "Function{pysa._test_source}", "Method{builtins.dict.__setitem__}",
    "Method{builtins.dict.keys}"
  ],
  "Function{dictionary.lists_of_dictionary_iteration_is_precise}": [
    "Function{pysa._test_sink}", "Function{pysa._test_source}",
    "Method{builtins.dict.__getitem__}", "Method{builtins.list.__iter__}",
    "Method{typing.Iterator.__next__}"
  ],
  "Function{dictionary.reassignment_removes_backwards_taint}": [
    "Function{pysa._test_sink}"
  ],
  "Function{dictionary.return_comprehension_with_tained_keys}": [
    "Function{pysa._test_source}", "Method{builtins.dict.__iter__}",
    "Method{typing.Iterator.__next__}"
  ],
  "Function{dictionary.return_comprehension_with_untainted_keys}": [
    "Function{pysa._test_source}", "Method{builtins.dict.__iter__}",
    "Method{typing.Iterator.__next__}"
  ],
  "Function{dictionary.setitem_models}": [
    "Method{builtins.dict.__init__}", "Method{builtins.dict.__new__}",
    "Method{builtins.dict.__setitem__}",
    "Method{dictionary.MyDict.__setitem__}"
  ],
  "Function{dictionary.sink_dictionary_through_keys}": [
    "Function{pysa._test_sink}", "Method{builtins.dict.__iter__}",
    "Method{typing.Iterator.__next__}"
  ],
  "Function{dictionary.taint_dict_keys_no_issue}": [
    "Function{dictionary.taint_dict_keys}", "Function{pysa._test_source}"
  ],
  "Function{dictionary.taint_dict_keys}": [
    "Function{pysa._test_sink}", "Method{builtins.dict.keys}"
  ],
  "Function{dictionary.tainted_setitem}": [
    "Function{pysa._test_source}",
    "Method{dictionary.SpecialSetitemDict.__setitem__}"
  ],
  "Function{dictionary.test_dict_get_foo_tito}": [
    "Function{dictionary.dict_get_foo}", "Function{pysa._test_sink}",
    "Function{pysa._test_source}"
  ],
  "Function{dictionary.test_dict_get_source}": [
    "Function{pysa._test_sink}", "Function{pysa._test_source}",
    "Method{builtins.dict.get}"
  ],
  "Function{dictionary.test_dict_getitem_mutate}": [
    "Function{dictionary.dict_getitem_mutate}", "Function{pysa._test_sink}",
    "Function{pysa._test_source}"
  ],
  "Function{dictionary.test_dict_multiple_targets}": [
    "Function{pysa._test_sink}", "Function{pysa._test_source}",
    "Method{builtins.dict.__getitem__}"
  ],
  "Function{dictionary.test_dict_sanitize_getitem}": [
    "Function{pysa._test_sink}", "Function{pysa._test_source}",
    "Method{builtins.dict.__getitem__}"
  ],
  "Function{dictionary.test_dict_sanitize_get}": [
    "Function{pysa._test_sink}", "Function{pysa._test_source}",
    "Method{builtins.dict.get}"
  ],
  "Function{dictionary.test_index_from_tito}": [
    "Function{dictionary.tito_with_index}", "Function{pysa._test_sink}",
    "Function{pysa._test_source}"
  ],
  "Function{dictionary.test_items_backward_keys}": [
    "Function{pysa._test_sink}", "Method{builtins.dict.items}",
    "Method{typing.ItemsView.__iter__}", "Method{typing.Iterator.__next__}"
  ],
  "Function{dictionary.test_items_backward_values}": [
    "Function{pysa._test_sink}", "Method{builtins.dict.items}",
    "Method{typing.ItemsView.__iter__}", "Method{typing.Iterator.__next__}"
  ],
  "Function{dictionary.test_items}": [
    "Function{pysa._test_sink}", "Function{pysa._test_source}",
    "Method{builtins.dict.items}", "Method{typing.ItemsView.__iter__}",
    "Method{typing.Iterator.__next__}"
  ],
  "Function{dictionary.test_keys_and_values}": [
    "Function{pysa._test_sink}", "Function{pysa._test_source}",
    "Method{builtins.dict.keys}", "Method{builtins.dict.values}",
    "Method{builtins.tuple.__getitem__}", "Method{typing.Iterator.__next__}",
    "Method{typing.KeysView.__iter__}", "Method{typing.ValuesView.__iter__}"
  ],
  "Function{dictionary.test_mapping_sanitize_getitem}": [
    "Function{pysa._test_sink}", "Function{pysa._test_source}",
    "Method{typing.Mapping.__getitem__}"
  ],
  "Function{dictionary.test_mapping_sanitize_get}": [
    "Function{pysa._test_sink}", "Function{pysa._test_source}",
    "Method{typing.Mapping.get}"
  ],
  "Function{dictionary.test_service_with_dict}": [
    "Function{pysa._test_sink}", "Function{pysa._test_source}",
    "Method{builtins.object.__init__}", "Method{builtins.object.__new__}",
    "Method{dictionary.Service.async_get_dict}"
  ],
  "Function{dictionary.test_service_with_mapping}": [
    "Function{pysa._test_sink}", "Function{pysa._test_source}",
    "Method{builtins.object.__init__}", "Method{builtins.object.__new__}",
    "Method{dictionary.Service.async_get_mapping}"
  ],
  "Function{dictionary.test_setitem_with_parenthesized_target}": [
    "Method{builtins.dict.__setitem__}"
  ],
  "Function{dictionary.test_type_comments}": [
    "Method{builtins.dict.__setitem__}"
  ],
  "Function{dictionary.test_with_issue_in_dict_comprehension}": [
    "Function{pysa._test_sink}", "Function{pysa._test_source}",
    "Method{builtins.list.__iter__}", "Method{typing.Iterator.__next__}"
  ],
  "Function{dictionary.test_with_issue_in_dict_items_comprehension}": [
    "Function{pysa._test_source}", "Method{builtins.dict.items}",
    "Method{typing.ItemsView.__iter__}", "Method{typing.Iterator.__next__}"
  ],
  "Function{dictionary.tito_with_index}": [
    "Method{builtins.dict.__getitem__}"
  ],
  "Function{dictionary.update_dictionary_indirectly}": [
    "Method{typing.MutableMapping.update}"
  ],
  "Function{dictionary.update_parameter}": [ "Function{pysa._test_source}" ],
  "Function{dictionary.update_tainted_dictionary_sink}": [
    "Function{pysa._test_sink}", "Method{typing.MutableMapping.update}"
  ],
  "Function{dictionary.update_tainted_dictionary}": [
    "Function{pysa._test_source}", "Method{typing.MutableMapping.update}"
  ],
  "Function{dictionary.walrus_operator}": [
    "Function{pysa._test_source}", "Method{builtins.dict.__setitem__}"
  ],
  "Method{dictionary.Service.async_get_dict}": [
    "Method{builtins.dict.get}",
    "Method{dictionary.Service.async_get_many_dict}"
  ],
  "Method{dictionary.Service.async_get_many_dict}": [
    "Function{typing.cast}", "Method{typing.Iterable.__iter__}",
    "Method{typing.Iterator.__next__}"
  ],
  "Method{dictionary.Service.async_get_mapping}": [
    "Function{dictionary.to_map}",
    "Method{dictionary.Service.async_get_many_dict}",
    "Method{typing.Mapping.get}"
  ],
  "Method{dictionary.SpecialSetitemDict.__setitem__}": [
    "Function{pysa._test_sink}"
  ]
}