@generated
Call dependencies
{
  "Function{dictionary_delete.dict_into_sink}": [
    "Function{pysa._test_sink}", "Method{builtins.dict.__getitem__}"
  ],
  "Function{dictionary_delete.pop_dict_with_bad_key}": [
    "Method{builtins.dict.__getitem__}", "Method{builtins.dict.pop}"
  ],
  "Function{dictionary_delete.pop_key}": [ "Method{builtins.dict.pop}" ],
  "Function{dictionary_delete.return_dict_with_bad_key}": [
    "Function{pysa._test_source}", "Method{builtins.dict.__getitem__}"
  ],
  "Function{dictionary_delete.take_dict_with_bad_key}": [
    "Method{builtins.dict.__getitem__}"
  ],
  "Function{dictionary_delete.test_del_keyword}": [
    "Function{pysa._test_sink}", "Function{pysa._test_source}",
    "Method{builtins.dict.__getitem__}"
  ],
  "Function{dictionary_delete.test_pop_method}": [
    "Function{pysa._test_sink}", "Function{pysa._test_source}",
    "Method{builtins.dict.__getitem__}", "Method{builtins.dict.pop}"
  ]
}