@generated
Call dependencies
{
  "Function{entrypoint.$toplevel}": [
    "Function{entrypoint.main}", "Method{builtins.str.__eq__}"
  ],
  "Function{entrypoint.entrypoint_into_lambda.lambda_entrypoint_with_decorator@decorated}": [
    "Function{entrypoint.MyEntrypoint}[formal(f, position=0)=Function{entrypoint.entrypoint_into_lambda.lambda_entrypoint_with_decorator}]"
  ],
  "Function{entrypoint.entrypoint_into_lambda.lambda_entrypoint_with_decorator}": [
    "Method{builtins.list.append}"
  ],
  "Function{entrypoint.entrypoint_into_lambda}": [
    "Function{entrypoint.entrypoint_into_lambda.lambda_entrypoint_with_decorator}"
  ],
  "Function{entrypoint.function_entrypoint_with_decorator@decorated}": [
    "Function{entrypoint.MyEntrypoint}[formal(f, position=0)=Function{entrypoint.function_entrypoint_with_decorator}]"
  ],
  "Function{entrypoint.function_entrypoint_with_decorator}": [
    "Method{builtins.list.append}"
  ],
  "Function{entrypoint.get_these}": [
    "Function{entrypoint.immediate_examples}",
    "Function{entrypoint.leak_globals_by_passing_in}",
    "Function{entrypoint.leak_globals_by_transitive_call}",
    "Function{entrypoint.nested_run}"
  ],
  "Function{entrypoint.immediate_examples}": [
    "Method{builtins.list.append}"
  ],
  "Function{entrypoint.leak_globals_by_passing_in}": [
    "Function{entrypoint.transitive_call_with_globals_passed_in}"
  ],
  "Function{entrypoint.leak_globals_by_transitive_call}": [
    "Function{entrypoint.transitive_call_accessing_globals}"
  ],
  "Function{entrypoint.main}": [
    "Function{entrypoint.get_these}",
    "Function{entrypoint.this_one_shouldnt_be_found}",
    "Method{builtins.object.__init__}", "Method{builtins.object.__new__}",
    "Method{entrypoint.MyClass.some_entrypoint_function}"
  ],
  "Function{entrypoint.nested_run.do_the_thing}": [
    "Method{builtins.list.append}"
  ],
  "Function{entrypoint.nested_run}": [
    "Function{entrypoint.nested_run.do_the_thing}"
  ],
  "Function{entrypoint.this_one_shouldnt_be_found}": [
    "Method{builtins.list.append}"
  ],
  "Function{entrypoint.transitive_call_accessing_globals}": [
    "Method{builtins.list.append}"
  ],
  "Function{entrypoint.transitive_call_with_globals_passed_in}": [
    "Method{builtins.list.append}"
  ],
  "Method{entrypoint.MyClass.method_entrypoint_with_decorator@decorated}": [
    "Function{entrypoint.MyEntrypoint}[formal(f, position=0)=Method{entrypoint.MyClass.method_entrypoint_with_decorator}]"
  ],
  "Method{entrypoint.MyClass.method_entrypoint_with_decorator}": [
    "Method{builtins.list.append}"
  ],
  "Method{entrypoint.MyClass.some_entrypoint_function}": [
    "Method{builtins.list.append}"
  ]
}