@generated
Call dependencies
{
  "Function{exception_test.none_throws}": [
    "Method{builtins.BaseException.__init__}",
    "Method{builtins.BaseException.__new__}"
  ],
  "Function{exception_test.test_before_try_to_finally}": [
    "Function{exception_test.none_throws}", "Function{pysa._test_sink}",
    "Function{pysa._test_source}"
  ],
  "Function{exception_test.test_caught_exception}": [
    "Function{builtins.isinstance}",
    "Method{builtins.BaseException.__str__}",
    "Method{builtins.object.__init__}", "Method{builtins.str.__new__}"
  ],
  "Function{exception_test.test_constructed_exception}": [
    "Method{builtins.BaseException.__init__}",
    "Method{builtins.BaseException.__new__}",
    "Method{builtins.BaseException.__str__}",
    "Method{builtins.object.__init__}", "Method{builtins.str.__new__}"
  ],
  "Function{exception_test.test_except_to_finally}": [
    "Function{exception_test.none_throws}", "Function{pysa._test_sink}",
    "Function{pysa._test_source}"
  ],
  "Function{exception_test.test_parameter_flow}": [
    "Method{builtins.BaseException.__str__}",
    "Method{builtins.object.__init__}", "Method{builtins.str.__new__}"
  ],
  "Function{exception_test.test_return_finally}": [
    "Function{builtins.print}", "Function{pysa._test_source}"
  ],
  "Function{exception_test.test_return_overrides_finally}": [
    "Function{pysa._test_source}"
  ],
  "Function{exception_test.test_return_twice_finally}": [
    "Function{pysa._test_source}"
  ],
  "Function{exception_test.test_sink_in_finally}": [
    "Function{exception_test.none_throws}", "Function{pysa._test_sink}"
  ],
  "Function{exception_test.test_within_try_to_finally}": [
    "Function{exception_test.none_throws}", "Function{pysa._test_sink}",
    "Function{pysa._test_source}"
  ]
}