@generated
Call dependencies
{
  "Function{extra_trace.branch_tito_backward}": [
    "Function{extra_trace.nested_transform_x}",
    "Function{extra_trace.transform_y}", "Function{pysa._test_sink}"
  ],
  "Function{extra_trace.branch_tito_forward}": [
    "Function{extra_trace.nested_transform_x}",
    "Function{extra_trace.transform_y}", "Function{pysa._test_source}"
  ],
  "Function{extra_trace.double_nested_transform_x}": [
    "Function{extra_trace.nested_transform_x}"
  ],
  "Function{extra_trace.extra_trace_sink_as_origin}": [
    "Function{extra_trace.transform_x}", "Function{pysa._test_sink}",
    "Function{pysa._test_source}"
  ],
  "Function{extra_trace.extra_trace_through_override}": [
    "Function{pysa._test_sink}", "Function{pysa._test_source}",
    "Override{extra_trace.TransformBase.transform}"
  ],
  "Function{extra_trace.issue_via_transfom_captured_variable}": [
    "Function{extra_trace.issue_via_transfom_captured_variable.nested_function}",
    "Function{pysa._test_sink}", "Function{pysa._test_source}"
  ],
  "Function{extra_trace.loop_tito_backward}": [
    "Function{extra_trace.non_deterministic_int}",
    "Function{extra_trace.transform_x}", "Function{pysa._test_sink}",
    "Method{builtins.int.__gt__}"
  ],
  "Function{extra_trace.loop_tito_forward}": [
    "Function{extra_trace.non_deterministic_int}",
    "Function{extra_trace.transform_x}", "Function{pysa._test_source}",
    "Method{builtins.int.__gt__}"
  ],
  "Function{extra_trace.mismatching_tito_extra_sink}": [
    "Function{extra_trace.non_deterministic_int}",
    "Function{extra_trace.tito_transform_attribute}",
    "Method{builtins.int.__gt__}"
  ],
  "Function{extra_trace.nested_transform_x}": [
    "Function{extra_trace.transform_x}"
  ],
  "Function{extra_trace.no_issue_via_transform_tito_with_missing_extra_sink}": [
    "Function{extra_trace.transform_tito_with_missing_extra_sink}",
    "Function{pysa._test_sink}", "Function{pysa._test_source}"
  ],
  "Function{extra_trace.sequential_tito_backward}": [
    "Function{extra_trace.nested_transform_x}", "Function{extra_trace.tito}",
    "Function{extra_trace.transform_yz}", "Function{pysa._test_sink}"
  ],
  "Function{extra_trace.sequential_tito_forward}": [
    "Function{extra_trace.nested_transform_x}", "Function{extra_trace.tito}",
    "Function{extra_trace.transform_yz}", "Function{pysa._test_source}"
  ],
  "Function{extra_trace.source_transform_nested_x_y}": [
    "Function{extra_trace.transform_nested_x_y}",
    "Function{pysa._test_source}"
  ],
  "Function{extra_trace.tito_transform_attribute}": [
    "Function{extra_trace.non_deterministic_int}",
    "Function{extra_trace.tito_collapse}",
    "Function{extra_trace.transform_x}", "Method{builtins.int.__gt__}"
  ],
  "Function{extra_trace.transform_nested_x_y}": [
    "Function{extra_trace.nested_transform_x}",
    "Function{extra_trace.transform_y}"
  ],
  "Function{extra_trace.transform_tito_with_missing_extra_sink}": [
    "Function{extra_trace.mismatching_tito_extra_sink}"
  ],
  "Function{extra_trace.transform_yz}": [
    "Function{extra_trace.tito}", "Function{extra_trace.transform_y}",
    "Function{extra_trace.transform_z}"
  ],
  "Method{extra_trace.OverrideTransform.transform}": [
    "Function{extra_trace.transform_x}"
  ]
}