@generated
Call dependencies
{
  "Function{features.async_issue_bools}": [
    "Function{features.async_tuple_of_bools}", "Function{pysa._test_sink}"
  ],
  "Function{features.async_tuple_of_bools}": [
    "Function{pysa._test_source}"
  ],
  "Function{features.issue_from_tuple}": [
    "Function{features.return_tuple_of_bools}", "Function{pysa._test_sink}"
  ],
  "Function{features.issue_via_bool}": [
    "Function{pysa._test_sink}", "Function{pysa._test_source}",
    "Method{builtins.bool.__new__}", "Method{builtins.object.__init__}"
  ],
  "Function{features.issue_via_equality}": [
    "Function{features.returns_tainted_object}", "Function{pysa._test_sink}",
    "Method{builtins.str.__eq__}"
  ],
  "Function{features.issue_via_in}": [
    "Function{pysa._test_sink}", "Function{pysa._test_source}"
  ],
  "Function{features.no_always_when_calling_setitem}": [
    "Function{pysa._test_source}", "Method{builtins.object.__init__}",
    "Method{builtins.object.__new__}",
    "Method{features.SetItemClass.__setitem__}"
  ],
  "Function{features.return_tuple_of_bools}": [
    "Function{pysa._test_source}"
  ],
  "Function{features.returns_tainted_object}": [
    "Function{pysa._test_source}"
  ],
  "Function{features.tito_via_constructor}": [
    "Method{builtins.int.__new__}", "Method{builtins.object.__init__}"
  ],
  "Function{features.tito_via_len}": [ "Function{features.len}" ],
  "Function{features.tito_via_min_left}": [ "Function{features.min}" ],
  "Function{features.tito_via_min_or_not}": [ "Function{features.min}" ],
  "Function{features.tito_via_min_right}": [ "Function{features.min}" ],
  "Function{features.tito_via_named}": [ "Function{features.named}" ],
  "Function{features.tito_via_optional}": [
    "Function{features.optional_scalar}"
  ],
  "Function{features.tito_with_tuple}": [ "Function{features.min}" ]
}