@generated
Call dependencies
{
  "Function{first_index.alternate_fields}": [
    "Function{pysa._test_sink}", "Function{pysa._test_source}",
    "Method{_random.Random.random}", "Method{builtins.dict.__getitem__}",
    "Method{builtins.float.__gt__}"
  ],
  "Function{first_index.local_fields_hop}": [
    "Function{first_index.local_fields}", "Method{_random.Random.random}",
    "Method{builtins.float.__gt__}"
  ],
  "Function{first_index.local_fields}": [
    "Function{first_index.alternate_fields}",
    "Method{_random.Random.random}", "Method{builtins.float.__gt__}"
  ]
}