@generated
Call dependencies
{
  "Function{format.issue_in_format_specifier}": [
    "Function{pysa._test_sink}", "Function{pysa._test_source}",
    "Method{builtins.str.__format__}"
  ],
  "Function{format.issue_in_format}": [
    "Function{pysa._test_sink}", "Function{pysa._test_source}",
    "Method{builtins.object.__repr__}"
  ],
  "Function{format.sink_in_format_specifier}": [
    "Function{pysa._test_sink}"
  ],
  "Function{format.sink_in_format}": [
    "Function{pysa._test_sink}", "Method{builtins.object.__repr__}"
  ],
  "Function{format.sink_via_format}": [ "Function{pysa._test_sink}" ],
  "Function{format.source_in_format_specifier}": [
    "Function{pysa._test_source}", "Method{builtins.str.__format__}"
  ],
  "Function{format.source_in_format}": [ "Function{pysa._test_source}" ],
  "Function{format.source_via_format}": [ "Function{pysa._test_source}" ]
}