@generated
Call dependencies
{
  "Function{format_stringify_redefinition.$toplevel}": [
    "Method{builtins.str.__eq__}"
  ],
  "Function{format_stringify_redefinition.source_via_str}": [
    "Function{pysa._test_source}", "Method{builtins.object.__init__}",
    "Method{builtins.str.__new__}"
  ],
  "Function{format_stringify_redefinition.str_of_base}": [
    "Method{builtins.object.__init__}", "Method{builtins.str.__new__}",
    "Method{format_stringify_redefinition.Base.__str__$2}",
    "Method{format_stringify_redefinition.Base.__unicode__}"
  ],
  "Function{format_stringify_redefinition.str_of_sub}": [
    "Method{builtins.object.__init__}", "Method{builtins.str.__new__}",
    "Method{format_stringify_redefinition.Base.__str__$2}",
    "Method{format_stringify_redefinition.Base.__unicode__}"
  ]
}