@generated
Call dependencies
{
  "Function{functions_as_locals.a_or_b}": [
    "Function{functions_as_locals.barA}",
    "Function{functions_as_locals.barB}", "Function{pysa._test_source}",
    "Method{_random.Random.random}", "Method{builtins.float.__gt__}"
  ],
  "Function{functions_as_locals.barA}": [ "Function{pysa._test_sink}" ],
  "Function{functions_as_locals.barB}": [ "Function{pysa._test_sink}" ],
  "Function{functions_as_locals.foo_as_local}": [
    "Function{functions_as_locals.foo}", "Function{pysa._test_source}"
  ],
  "Function{functions_as_locals.foo}": [ "Function{pysa._test_sink}" ],
  "Function{functions_as_locals.local_function_with_method_sink}": [
    "Function{pysa._test_source}", "Method{functions_as_locals.C.m}"
  ],
  "Function{functions_as_locals.local_tito}": [
    "Function{functions_as_locals.foo}"
  ],
  "Function{functions_as_locals.method_tito}": [
    "Method{functions_as_locals.C.m}"
  ],
  "Method{functions_as_locals.C.m}": [ "Function{pysa._test_sink}" ]
}