@generated
Call dependencies
{
  "Function{global_flows.append_argument}": [
    "Method{global_flows.MyList.append}"
  ],
  "Function{global_flows.append_directly}": [
    "Function{pysa._test_source}", "Method{global_flows.MyList.append}"
  ],
  "Function{global_flows.append_indirectly}": [
    "Function{global_flows.append_argument}", "Function{pysa._test_source}"
  ],
  "Function{global_flows.global_source}": [ "Function{pysa._test_sink}" ],
  "Function{global_flows.indirectly_update_x_arg1}": [
    "Function{global_flows.update_arg1}"
  ],
  "Function{global_flows.indirectly_update_x_arg2}": [
    "Function{global_flows.update_arg2}"
  ],
  "Function{global_flows.unaffected_x_at_arg1}": [
    "Function{global_flows.update_arg1}"
  ],
  "Function{global_flows.unaffected_x_at_arg2}": [
    "Function{global_flows.update_arg2}"
  ],
  "Function{global_flows.update_x_at_arg1}": [
    "Function{global_flows.update_arg1}", "Function{pysa._test_source}"
  ],
  "Function{global_flows.update_x_at_arg2}": [
    "Function{global_flows.update_arg2}", "Function{pysa._test_source}"
  ],
  "Function{global_flows.x_not_tainted}": [
    "Function{global_flows.indirectly_update_x_arg1}"
  ],
  "Function{global_flows.x_tainted_indirectly_arg1}": [
    "Function{global_flows.indirectly_update_x_arg1}",
    "Function{pysa._test_source}"
  ],
  "Function{global_flows.x_tainted_indirectly_arg2}": [
    "Function{global_flows.indirectly_update_x_arg2}",
    "Function{pysa._test_source}"
  ]
}