@generated
Call dependencies
{
  "Function{global.$toplevel}": [
    "Function{global.create_global_source}", "Function{pysa._test_source}",
    "Method{builtins.object.__new__}", "Method{global.Object.__init__}"
  ],
  "Function{global.create_global_source}": [ "Function{pysa._test_source}" ],
  "Function{global.obj1_flow}": [
    "Function{global.obj1_sink}", "Function{global.obj1_source}"
  ],
  "Function{global.obj1_no_flow}": [
    "Function{global.obj1_sink}", "Function{global.obj1_source}"
  ],
  "Function{global.obj1_sink}": [ "Function{pysa._test_sink}" ],
  "Function{global.obj1_source}": [ "Function{pysa._test_source}" ],
  "Function{global.obj2_sink}": [ "Function{pysa._test_sink}" ],
  "Function{global.obj3_flow}": [
    "Function{global.obj3_return}", "Function{global.obj3_set}",
    "Function{pysa._test_sink}", "Function{pysa._test_source}"
  ],
  "Function{global.obj4_flow}": [ "Function{pysa._test_sink}" ],
  "Function{global.obj6_flow}": [
    "Function{global.obj6_sink}", "Function{global.obj6_source}"
  ],
  "Function{global.obj6_sink}": [ "Function{pysa._test_sink}" ],
  "Function{global.obj6_source}": [ "Function{pysa._test_source}" ],
  "Function{global.obj7_flow}": [
    "Function{global.obj7_sink}", "Function{global.obj7_source}"
  ],
  "Function{global.obj7_sink}": [ "Function{pysa._test_sink}" ],
  "Function{global.obj7_source}": [ "Function{pysa._test_source}" ],
  "Function{global.obj8_flow}": [
    "Function{global.obj8_return}", "Function{global.obj8_set}",
    "Function{pysa._test_sink}", "Function{pysa._test_source}"
  ]
}