@generated
Call dependencies
{
  "Function{graphql_callees.return_graphql_entrypoint_1@decorated}": [
    "Function{graphql_callees.entrypoint_decorator}[formal(callable, position=0)=Function{graphql_callees.return_graphql_entrypoint_1}]"
  ],
  "Function{graphql_callees.return_graphql_entrypoint_1}": [
    "Function{pysa._test_source}", "Method{builtins.object.__new__}",
    "Method{graphql_callees.GraphQLEntrypoint.__init__}",
    "Method{graphql_callees.GraphQLEntrypoint.callee}"
  ],
  "Function{graphql_callees.return_graphql_entrypoint_2@decorated}": [
    "Function{graphql_callees.entrypoint_decorator}[formal(callable, position=0)=Function{graphql_callees.return_graphql_entrypoint_2}]"
  ],
  "Function{graphql_callees.return_graphql_entrypoint_2}": [
    "Function{pysa._test_source}", "Method{builtins.object.__new__}",
    "Method{graphql_callees.GraphQLEntrypoint.__init__}",
    "Method{graphql_callees.GraphQLEntrypoint.callee}"
  ],
  "Function{graphql_callees.return_graphql_entrypoint_3@decorated}": [
    "Function{graphql_callees.entrypoint_decorator}[formal(callable, position=0)=Function{graphql_callees.return_graphql_entrypoint_3}]"
  ],
  "Function{graphql_callees.return_graphql_entrypoint_3}": [
    "Method{graphql_callees.GraphQLEntrypoint.callee}"
  ],
  "Function{graphql_callees.return_graphql_entrypoint_strip_list@decorated}": [
    "Function{graphql_callees.entrypoint_decorator}[formal(callable, position=0)=Function{graphql_callees.return_graphql_entrypoint_strip_list}]"
  ],
  "Function{graphql_callees.return_graphql_entrypoint_strip_list_with_sink@decorated}": [
    "Function{graphql_callees.entrypoint_decorator}[formal(callable, position=0)=Function{graphql_callees.return_graphql_entrypoint_strip_list_with_sink}]"
  ],
  "Function{graphql_callees.return_graphql_entrypoint_strip_list_with_sink}": [
    "Method{graphql_callees.GraphQLEntrypoint.callee}"
  ],
  "Function{graphql_callees.return_graphql_entrypoint_strip_list}": [
    "Function{pysa._test_source}", "Method{builtins.object.__new__}",
    "Method{graphql_callees.GraphQLEntrypoint.__init__}",
    "Method{graphql_callees.GraphQLEntrypoint.callee}"
  ],
  "Method{graphql_callees.GraphQLEntrypoint.callee@decorated}": [
    "Function{graphql_callees.method_decorator}[formal(callable, position=0)=Method{graphql_callees.GraphQLEntrypoint.callee}]"
  ],
  "Method{graphql_callees.GraphQLEntrypoint.callee}": [
    "Function{pysa._test_sink}"
  ],
  "Method{graphql_callees.GraphQLEntrypoint.not_callee}": [
    "Function{pysa._test_sink}"
  ]
}