@generated
Call dependencies
{
  "Function{http_request.request_get_flows_to_sink}": [
    "ClassInstanceAttribute{django.http.request.HttpRequest.GET}",
    "Function{pysa._test_sink}"
  ],
  "Function{http_request.test_hop_is_cut_off}": [
    "ClassInstanceAttribute{django.http.request.HttpRequest.GET}",
    "Function{http_request.request_get_flows_to_sink}",
    "Function{pysa._test_source}"
  ],
  "Function{http_request.test_trace_has_no_tito}": [
    "ClassInstanceAttribute{django.http.request.HttpRequest.GET}",
    "Function{pysa._test_sink}", "Function{pysa._test_source}"
  ],
  "Function{http_request.test_untainted_assign}": [
    "ClassInstanceAttribute{django.http.request.HttpRequest.GET}",
    "Function{pysa._test_sink}"
  ]
}