@generated
Call dependencies
{
  "Function{implicit_sinks.conditional_literal_sink}": [
    "Function{implicit_sinks.format_wrapper}", "Function{pysa._test_source}"
  ],
  "Function{implicit_sinks.implicit_sink_before_parameter}": [
    "Method{builtins.str.format}"
  ],
  "Function{implicit_sinks.implicit_sink_before_source}": [
    "Function{pysa._test_source}", "Method{builtins.str.format}"
  ],
  "Function{implicit_sinks.inline_issue_dot_format}": [
    "Function{pysa._test_source}", "Method{builtins.str.format}"
  ],
  "Function{implicit_sinks.inline_issue_format_string_proper_tito}": [
    "Function{pysa._test_source}", "Method{builtins.str.__format__}"
  ],
  "Function{implicit_sinks.inline_issue_format_string}": [
    "Function{pysa._test_source}"
  ],
  "Function{implicit_sinks.inline_issue_lhs_add_literal}": [
    "Function{pysa._test_source}"
  ],
  "Function{implicit_sinks.inline_issue_percent_format}": [
    "Function{pysa._test_source}", "Method{builtins.str.__mod__}"
  ],
  "Function{implicit_sinks.inline_issue_rhs_add_literal}": [
    "Function{pysa._test_source}", "Method{builtins.str.__add__}"
  ],
  "Function{implicit_sinks.propagate_sink_add_global}": [
    "Method{builtins.str.__add__}"
  ],
  "Function{implicit_sinks.propagate_sink_dot_format}": [
    "Method{builtins.str.format}"
  ],
  "Function{implicit_sinks.propagate_sink_percent_format}": [
    "Method{builtins.str.__mod__}"
  ],
  "Function{implicit_sinks.propagate_sink_rhs_add_literal}": [
    "Method{builtins.str.__add__}"
  ],
  "Function{implicit_sinks.string_literal_arguments_issue}": [
    "Function{implicit_sinks.string_literal_arguments_sink}",
    "Function{pysa._test_source}"
  ],
  "Function{implicit_sinks.string_literal_arguments_sink}": [
    "Function{pysa._test_source}", "Method{_random.Random.random}",
    "Method{builtins.float.__gt__}", "Method{builtins.str.__mod__}",
    "Method{builtins.str.format}"
  ]
}