@generated
Call dependencies
{
  "Function{implicit_sources.bar_dot_format}": [
    "Method{builtins.str.format}"
  ],
  "Function{implicit_sources.bar_format_strings}": [
    "Method{builtins.int.__format__}"
  ],
  "Function{implicit_sources.bar_percent_format}": [
    "Method{builtins.str.__mod__}"
  ],
  "Function{implicit_sources.string_literal_arguments_source}": [
    "Method{_random.Random.random}", "Method{builtins.float.__gt__}",
    "Method{builtins.str.__mod__}", "Method{builtins.str.format}"
  ],
  "Function{implicit_sources.toplevel_simultaneous_assignment}": [
    "Method{builtins.str.__add__}"
  ]
}