@generated
Call dependencies
{
  "Function{iterators.test_custom_getitem}": [
    "Function{builtins.iter}", "Function{builtins.next}",
    "Function{pysa._test_sink}", "Method{builtins.object.__init__}",
    "Method{builtins.object.__new__}", "Method{typing.Iterator.__next__}"
  ],
  "Function{iterators.test_custom_iter}": [
    "Function{builtins.iter}", "Function{builtins.next}",
    "Function{pysa._test_sink}", "Method{builtins.object.__init__}",
    "Method{builtins.object.__new__}",
    "Method{iterators.CustomIter.__iter__}",
    "Method{typing.Iterator.__next__}"
  ],
  "Function{iterators.test_next_iter}": [
    "Function{builtins.iter}", "Function{builtins.next}",
    "Function{pysa._test_sink}", "Function{pysa._test_source}",
    "Method{builtins.dict.__getitem__}", "Method{builtins.dict.__iter__}",
    "Method{builtins.list.__iter__}", "Method{typing.Iterator.__next__}"
  ],
  "Method{iterators.CustomGetItem.__getitem__}": [
    "Function{pysa._test_source}"
  ],
  "Method{iterators.CustomIter.__iter__}": [
    "Function{builtins.iter}", "Function{pysa._test_source}",
    "Method{builtins.list.__iter__}"
  ]
}