@generated
Call dependencies
{
  "Function{kwargs_and_args.args_sink}": [
    "Function{pysa._test_sink}", "Method{builtins.tuple.__getitem__}"
  ],
  "Function{kwargs_and_args.async_distillery_render}": [
    "Function{kwargs_and_args.async_render_to_response}",
    "Function{pysa._test_source}", "Method{builtins.dict.__setitem__}",
    "Method{builtins.dict.pop}"
  ],
  "Function{kwargs_and_args.async_render_to_response}": [
    "Function{pysa._test_sink}"
  ]
}