@generated
Call dependencies
{
  "Function{lists.create_zipped_source_with_all_tainted}": [
    "Function{pysa._test_source}", "Method{builtins.object.__init__}",
    "Method{builtins.zip.__new__}"
  ],
  "Function{lists.create_zipped_source}": [
    "Function{pysa._test_source}", "Method{builtins.object.__init__}",
    "Method{builtins.zip.__new__}"
  ],
  "Function{lists.inconsistent_redirect_expressions_in_condition}": [
    "Method{builtins.list.__iter__}", "Method{builtins.object.__init__}",
    "Method{builtins.str.__eq__}", "Method{builtins.str.__new__}",
    "Method{lists.HasRepr.__repr__}", "Method{typing.Iterator.__next__}"
  ],
  "Function{lists.inconsistent_type_context}": [
    "Function{lists.returns_list_repr}", "Method{builtins.list.__iter__}",
    "Method{builtins.object.__init__}", "Method{builtins.str.__new__}",
    "Method{lists.HasRepr.__repr__}", "Method{lists.HasStr.__str__}",
    "Method{typing.Iterator.__next__}"
  ],
  "Function{lists.list_append_wrapper}": [ "Method{builtins.list.append}" ],
  "Function{lists.list_setitem_local}": [
    "Function{pysa._test_source}", "Method{builtins.list.__setitem__}"
  ],
  "Function{lists.list_setitem_source}": [
    "Function{pysa._test_source}", "Method{builtins.list.__setitem__}"
  ],
  "Function{lists.list_setitem_wrapper}": [
    "Method{builtins.list.__setitem__}"
  ],
  "Function{lists.push_pop_no_taint}": [
    "Function{pysa._test_source}", "Method{builtins.list.append}",
    "Method{builtins.list.pop}"
  ],
  "Function{lists.push_pop_taint}": [
    "Function{pysa._test_source}", "Method{builtins.list.append}",
    "Method{builtins.list.pop}"
  ],
  "Function{lists.test_list_append_wrapper}": [
    "Function{lists.list_append_wrapper}", "Function{pysa._test_sink}",
    "Function{pysa._test_source}", "Method{builtins.list.__getitem__}",
    "Method{builtins.list.append}"
  ],
  "Function{lists.test_list_setitem_wrapper}": [
    "Function{lists.list_setitem_wrapper}", "Function{pysa._test_sink}",
    "Function{pysa._test_source}", "Method{builtins.list.__getitem__}"
  ],
  "Function{lists.test_setitem_source}": [
    "Function{lists.list_setitem_source}", "Function{pysa._test_sink}",
    "Method{builtins.list.__getitem__}"
  ],
  "Function{lists.test_setitem}": [
    "Function{pysa._test_sink}", "Function{pysa._test_source}",
    "Method{builtins.list.__getitem__}", "Method{builtins.list.__mul__}",
    "Method{builtins.list.__setitem__}"
  ],
  "Function{lists.zipped_element_not_flowing_to_sink}": [
    "Function{pysa._test_sink}", "Method{builtins.object.__init__}",
    "Method{builtins.zip.__iter__}", "Method{builtins.zip.__new__}",
    "Method{builtins.zip.__next__}"
  ],
  "Function{lists.zipped_element_to_sink}": [
    "Function{pysa._test_sink}", "Method{builtins.object.__init__}",
    "Method{builtins.zip.__iter__}", "Method{builtins.zip.__new__}",
    "Method{builtins.zip.__next__}"
  ],
  "Function{lists.zipped_source_access_path}": [
    "Function{pysa._test_source}", "Method{builtins.list.__getitem__}",
    "Method{builtins.list.__init__}", "Method{builtins.object.__init__}",
    "Method{builtins.object.__new__}", "Method{builtins.tuple.__getitem__}",
    "Method{builtins.zip.__new__}"
  ]
}