@generated
Call dependencies
{
  "Function{locals.locals_to_sink}": [
    "Function{builtins.locals}", "Function{locals.named_sink}",
    "Function{pysa._test_sink}", "Function{pysa._test_source}",
    "Method{builtins.dict.__getitem__}"
  ],
  "Function{locals.named_sink}": [ "Function{pysa._test_sink}" ],
  "Function{locals.source_parameter_to_sink}": [
    "Function{builtins.locals}", "Function{pysa._test_sink}",
    "Method{builtins.dict.__getitem__}"
  ]
}