@generated
Call dependencies
{
  "Function{long_access_path_taint.test}": [
    "Function{pysa._test_sink}", "Function{pysa._test_source}",
    "Method{long_access_path_taint.C.async_create}"
  ],
  "Method{long_access_path_taint.C.__init__}": [
    "Method{builtins.dict.get}"
  ],
  "Method{long_access_path_taint.C.async_create}": [
    "Method{builtins.object.__init__}", "Method{builtins.object.__new__}",
    "Method{builtins.object.__repr__}", "Method{builtins.str.__eq__}",
    "Method{builtins.str.__new__}",
    "Method{long_access_path_taint.C.__init__}"
  ]
}