@generated
Call dependencies
{
  "Function{match.test_match_class_pattern}": [
    "Function{pysa._test_sink}", "Function{pysa._test_source}",
    "Method{builtins.object.__new__}", "Method{match.MyClass.__init__}"
  ],
  "Function{match.test_match_equality}": [
    "Function{pysa._test_sink}", "Function{pysa._test_source}"
  ],
  "Function{match.test_match_list_pattern_with_condition}": [
    "Function{match.condition}", "Function{pysa._test_sink}",
    "Function{pysa._test_source}"
  ],
  "Function{match.test_match_list_pattern}": [
    "Function{pysa._test_sink}", "Function{pysa._test_source}"
  ],
  "Function{match.test_match_mapping_pattern}": [
    "Function{pysa._test_sink}", "Function{pysa._test_source}"
  ]
}