@generated
Call dependencies
{
  "Function{maximum_tito_depth.issue}": [
    "Function{maximum_tito_depth.tito_three}", "Function{pysa._test_sink}",
    "Function{pysa._test_source}"
  ],
  "Function{maximum_tito_depth.non_issue}": [
    "Function{maximum_tito_depth.tito_four}", "Function{pysa._test_sink}",
    "Function{pysa._test_source}"
  ],
  "Function{maximum_tito_depth.tito_four}": [
    "Function{maximum_tito_depth.tito_three}"
  ],
  "Function{maximum_tito_depth.tito_max_consecutive}": [
    "Function{maximum_tito_depth.tito_one}",
    "Function{maximum_tito_depth.tito_two}",
    "Function{maximum_tito_depth.tito_zero}"
  ],
  "Function{maximum_tito_depth.tito_min_disjoint_max_consecutive}": [
    "Function{maximum_tito_depth.tito_one}",
    "Function{maximum_tito_depth.tito_two}",
    "Function{maximum_tito_depth.tito_zero}"
  ],
  "Function{maximum_tito_depth.tito_min_disjoint}": [
    "Function{maximum_tito_depth.tito_one}",
    "Function{maximum_tito_depth.tito_zero}"
  ],
  "Function{maximum_tito_depth.tito_obscure}": [
    "Method{builtins.object.__init__}", "Method{builtins.object.__new__}",
    "Method{maximum_tito_depth.C.tito}"
  ],
  "Function{maximum_tito_depth.tito_one}": [
    "Function{maximum_tito_depth.tito_zero}"
  ],
  "Function{maximum_tito_depth.tito_three}": [
    "Function{maximum_tito_depth.tito_two}"
  ],
  "Function{maximum_tito_depth.tito_two}": [
    "Function{maximum_tito_depth.tito_one}"
  ]
}