@generated
Call dependencies
{
  "Function{maximum_trace_length.issue_source_one_sink_one}": [
    "Function{maximum_trace_length.sink_distance_one}",
    "Function{maximum_trace_length.source_distance_one}"
  ],
  "Function{maximum_trace_length.issue_source_one_sink_two}": [
    "Function{maximum_trace_length.sink_distance_two}",
    "Function{maximum_trace_length.source_distance_one}"
  ],
  "Function{maximum_trace_length.issue_source_one_sink_zero}": [
    "Function{maximum_trace_length.sink_distance_zero}",
    "Function{maximum_trace_length.source_distance_one}"
  ],
  "Function{maximum_trace_length.issue_source_two_sink_one}": [
    "Function{maximum_trace_length.sink_distance_one}",
    "Function{maximum_trace_length.source_distance_two}"
  ],
  "Function{maximum_trace_length.issue_source_zero_sink_zero}": [
    "Function{maximum_trace_length.sink_distance_zero}",
    "Function{maximum_trace_length.source_distance_zero}"
  ],
  "Function{maximum_trace_length.multi_sink}": [
    "Function{maximum_trace_length.sink_distance_one}",
    "Function{pysa._tito}"
  ],
  "Function{maximum_trace_length.sink_distance_one}": [
    "Function{maximum_trace_length.sink_distance_zero}"
  ],
  "Function{maximum_trace_length.sink_distance_two}": [
    "Function{maximum_trace_length.sink_distance_one}"
  ],
  "Function{maximum_trace_length.sink_distance_zero}": [
    "Function{pysa._test_sink}"
  ],
  "Function{maximum_trace_length.source_distance_one}": [
    "Function{maximum_trace_length.source_distance_zero}"
  ],
  "Function{maximum_trace_length.source_distance_two}": [
    "Function{maximum_trace_length.source_distance_one}"
  ],
  "Function{maximum_trace_length.source_distance_zero}": [
    "Function{pysa._test_source}"
  ]
}