@generated
Call dependencies
{
  "Function{missing_type.test_unknown_sink_attribute}": [
    "Function{pysa._test_source}",
    "Method{missing_type.UnknownSinkAttribute.sink}"
  ],
  "Function{missing_type.test_unknown_sink_def}": [
    "Function{pysa._test_source}", "Method{missing_type.UnknownSinkDef.sink}"
  ],
  "Function{missing_type.test_unknown_source_attribute}": [
    "Function{pysa._test_sink}",
    "Method{missing_type.UnknownSourceAttribute.source}"
  ],
  "Function{missing_type.test_unknown_source_def}": [
    "Function{pysa._test_sink}",
    "Method{missing_type.UnknownSourceDef.source}"
  ]
}