@generated
Call dependencies
{
  "Function{model_query_global_variable.$toplevel}": [
    "Function{model_query_global_variable.fun}",
    "Function{model_query_global_variable.returns_any}",
    "Function{pysa._test_sink}", "Function{pysa._test_source}",
    "Method{builtins.int.__add__}", "Method{builtins.int.__new__}",
    "Method{builtins.object.__init__}"
  ],
  "Function{model_query_global_variable.fun}": [
    "Method{builtins.int.__add__}", "Method{builtins.int.__new__}",
    "Method{builtins.object.__init__}"
  ],
  "Function{model_query_global_variable.f}": [ "Function{pysa._test_sink}" ],
  "Function{model_query_global_variable.g}": [
    "Method{builtins.list.append}"
  ],
  "Function{model_query_global_variable.h}": [ "Function{pysa._test_sink}" ],
  "Function{model_query_global_variable.returns_any}": [
    "Method{builtins.object.__init__}", "Method{builtins.object.__new__}"
  ]
}