@generated
Call dependencies
{
  "Function{model_query_parent_decorator.setup}": [
    "Method{builtins.object.__new__}",
    "Method{model_query_parent_decorator.TestC_1.__init__}",
    "Method{model_query_parent_decorator.TestC_2.__init__}",
    "Method{model_query_parent_decorator.TestC_3.__init__}"
  ],
  "Method{model_query_parent_decorator.TestC_1.__init__}": [
    "Function{pysa._test_sink}"
  ],
  "Method{model_query_parent_decorator.TestC_2.__init__}": [
    "Function{pysa._test_sink}"
  ],
  "Method{model_query_parent_decorator.TestC_3.__init__}": [
    "Function{pysa._test_sink}"
  ]
}