@generated
Call dependencies
{
  "Function{model_query.alarm_10}": [
    "ClassInstanceAttribute{model_query.AttributeTestClass5.foo_instance}",
    "Function{pysa._test_sink}"
  ],
  "Function{model_query.alarm_11}": [
    "ClassInstanceAttribute{model_query.AttributeTestClass6.foo_attribute}",
    "Function{pysa._test_sink}"
  ],
  "Function{model_query.alarm_12}": [
    "ClassInstanceAttribute{model_query.AttributeTestClass6.foo_instance}",
    "Function{pysa._test_sink}"
  ],
  "Function{model_query.alarm_1}": [
    "ClassInstanceAttribute{model_query.AttributeTestClass1.attribute}",
    "Function{pysa._test_sink}"
  ],
  "Function{model_query.alarm_2}": [
    "ClassInstanceAttribute{model_query.AttributeTestClass1.instance}",
    "Function{pysa._test_sink}"
  ],
  "Function{model_query.alarm_3}": [
    "ClassInstanceAttribute{model_query.AttributeTestClass2.attribute}",
    "Function{pysa._test_sink}"
  ],
  "Function{model_query.alarm_4}": [
    "ClassInstanceAttribute{model_query.AttributeTestClass2.instance}",
    "Function{pysa._test_sink}"
  ],
  "Function{model_query.alarm_5}": [
    "ClassInstanceAttribute{model_query.AttributeTestClass3.attribute}"
  ],
  "Function{model_query.alarm_6}": [
    "ClassInstanceAttribute{model_query.AttributeTestClass3.instance}",
    "Function{pysa._test_source}"
  ],
  "Function{model_query.alarm_7}": [
    "ClassInstanceAttribute{model_query.AttributeTestClass4.attribute}"
  ],
  "Function{model_query.alarm_8}": [
    "ClassInstanceAttribute{model_query.AttributeTestClass4.instance}",
    "Function{pysa._test_sink}"
  ],
  "Function{model_query.alarm_9}": [
    "ClassInstanceAttribute{model_query.AttributeTestClass5.foo_attribute}",
    "Function{pysa._test_sink}"
  ],
  "Function{model_query.no_alarm_1}": [ "Function{pysa._test_sink}" ],
  "Function{model_query.no_alarm_2}": [ "Function{pysa._test_sink}" ],
  "Method{model_query.AttributeTestClass1.__init__}": [
    "ClassInstanceAttribute{model_query.AttributeTestClass1.instance}"
  ],
  "Method{model_query.AttributeTestClass2.__init__}": [
    "ClassInstanceAttribute{model_query.AttributeTestClass2.instance}"
  ],
  "Method{model_query.AttributeTestClass3.__init__}": [
    "ClassInstanceAttribute{model_query.AttributeTestClass3.instance}"
  ],
  "Method{model_query.AttributeTestClass4.__init__}": [
    "ClassInstanceAttribute{model_query.AttributeTestClass4.instance}"
  ],
  "Method{model_query.AttributeTestClass5.__init__}": [
    "ClassInstanceAttribute{model_query.AttributeTestClass5.foo_instance}"
  ],
  "Method{model_query.AttributeTestClass6.__init__}": [
    "ClassInstanceAttribute{model_query.AttributeTestClass6.foo_instance}"
  ]
}