@generated
Call dependencies
{
  "Function{model_query_transitive_extends.misc_noalarm1}": [
    "Function{pysa._test_sink}"
  ],
  "Function{model_query_transitive_extends.misc_noalarm2}": [
    "Function{pysa._test_sink}"
  ],
  "Function{model_query_transitive_extends.misc_noalarm3}": [
    "Function{pysa._test_source}",
    "Method{model_query_transitive_extends.UnrelatedClass.foo}"
  ],
  "Function{model_query_transitive_extends.test1_alarm1}": [
    "ClassInstanceAttribute{model_query_transitive_extends.Test1_C.attribute}",
    "ClassInstanceAttribute{model_query_transitive_extends.Test1_C1.attribute}",
    "Function{pysa._test_sink}"
  ],
  "Function{model_query_transitive_extends.test1_alarm2}": [
    "ClassInstanceAttribute{model_query_transitive_extends.Test1_C.instance}",
    "ClassInstanceAttribute{model_query_transitive_extends.Test1_C1.instance}",
    "Function{pysa._test_sink}"
  ],
  "Function{model_query_transitive_extends.test1_alarm3}": [
    "ClassInstanceAttribute{model_query_transitive_extends.Test1_C.attribute}",
    "ClassInstanceAttribute{model_query_transitive_extends.Test1_C1.attribute}",
    "ClassInstanceAttribute{model_query_transitive_extends.Test1_C2.attribute}",
    "Function{pysa._test_sink}"
  ],
  "Function{model_query_transitive_extends.test1_alarm4}": [
    "ClassInstanceAttribute{model_query_transitive_extends.Test1_C.instance}",
    "ClassInstanceAttribute{model_query_transitive_extends.Test1_C1.instance}",
    "ClassInstanceAttribute{model_query_transitive_extends.Test1_C2.instance}",
    "Function{pysa._test_sink}"
  ],
  "Function{model_query_transitive_extends.test1_alarm5}": [
    "ClassInstanceAttribute{model_query_transitive_extends.Test1_C.attribute}",
    "Function{pysa._test_sink}"
  ],
  "Function{model_query_transitive_extends.test1_alarm6}": [
    "ClassInstanceAttribute{model_query_transitive_extends.Test1_C.instance}",
    "Function{pysa._test_sink}"
  ],
  "Function{model_query_transitive_extends.test1_noalarm1}": [
    "Function{pysa._test_sink}"
  ],
  "Function{model_query_transitive_extends.test1_noalarm2}": [
    "Function{pysa._test_sink}"
  ],
  "Function{model_query_transitive_extends.test2_alarm1}": [
    "Function{pysa._test_source}",
    "Method{model_query_transitive_extends.Test2_D.foo}"
  ],
  "Function{model_query_transitive_extends.test2_noalarm1}": [
    "Function{pysa._test_source}",
    "Override{model_query_transitive_extends.Test2_C1.foo}"
  ],
  "Function{model_query_transitive_extends.test2_noalarm2}": [
    "Function{pysa._test_source}",
    "Method{model_query_transitive_extends.Test2_C2.foo}"
  ],
  "Function{model_query_transitive_extends.test2_noalarm3}": [
    "Function{pysa._test_source}",
    "Override{model_query_transitive_extends.Test2_C.foo}"
  ],
  "Method{model_query_transitive_extends.Test1_C.__init__}": [
    "ClassInstanceAttribute{model_query_transitive_extends.Test1_C.instance}"
  ],
  "Method{model_query_transitive_extends.Test1_C1.__init__}": [
    "ClassInstanceAttribute{model_query_transitive_extends.Test1_C.instance}",
    "ClassInstanceAttribute{model_query_transitive_extends.Test1_C1.instance}"
  ],
  "Method{model_query_transitive_extends.Test1_C2.__init__}": [
    "ClassInstanceAttribute{model_query_transitive_extends.Test1_C.instance}",
    "ClassInstanceAttribute{model_query_transitive_extends.Test1_C1.instance}",
    "ClassInstanceAttribute{model_query_transitive_extends.Test1_C2.instance}"
  ]
}