@generated
Call dependencies
{
  "Function{model_query_return_annotation_extends.test1_alarm1}": [
    "Function{pysa._test_source}"
  ],
  "Function{model_query_return_annotation_extends.test1_alarm2}": [
    "Function{pysa._test_source}"
  ],
  "Function{model_query_return_annotation_extends.test1_alarm3}": [
    "Function{pysa._test_source}"
  ],
  "Function{model_query_return_annotation_extends.test1_alarm4}": [
    "Function{pysa._test_source}"
  ],
  "Function{model_query_return_annotation_extends.test1_noalarm1}": [
    "Function{pysa._test_source}"
  ],
  "Function{model_query_return_annotation_extends.test3_alarm1}": [
    "Function{pysa._test_source}"
  ],
  "Function{model_query_return_annotation_extends.test3_alarm2}": [
    "Function{pysa._test_source}"
  ],
  "Function{model_query_return_annotation_extends.test3_alarm3}": [
    "Function{pysa._test_source}"
  ],
  "Function{model_query_return_annotation_extends.test3_alarm4}": [
    "Function{pysa._test_source}"
  ],
  "Function{model_query_return_annotation_extends.test3_noalarm1}": [
    "Function{pysa._test_source}"
  ],
  "Method{model_query_return_annotation_extends.Test2.test2_alarm1}": [
    "Function{pysa._test_source}"
  ],
  "Method{model_query_return_annotation_extends.Test2.test2_alarm2}": [
    "Function{pysa._test_source}"
  ],
  "Method{model_query_return_annotation_extends.Test2.test2_noalarm1}": [
    "Function{pysa._test_source}"
  ],
  "Method{model_query_return_annotation_extends.Test2.test2_noalarm2}": [
    "Function{pysa._test_source}"
  ]
}