@generated
Call dependencies
{
  "Function{model_query_annotated.test1_alarm1}": [
    "ClassInstanceAttribute{model_query_annotated.Test1_C.a}",
    "ClassInstanceAttribute{model_query_annotated.Test1_C.b}",
    "Function{pysa._test_sink}"
  ],
  "Function{model_query_annotated.test1_alarm2}": [
    "ClassInstanceAttribute{model_query_annotated.Test1_C.a}",
    "ClassInstanceAttribute{model_query_annotated.Test1_C.b}",
    "Function{pysa._test_sink}"
  ],
  "Function{model_query_annotated.test1_alarm3}": [
    "ClassInstanceAttribute{model_query_annotated.Test1_C.x}",
    "Function{pysa._test_sink}"
  ],
  "Function{model_query_annotated.test1_alarm4}": [
    "ClassInstanceAttribute{model_query_annotated.Test1_C.y}",
    "Function{pysa._test_sink}"
  ],
  "Function{model_query_annotated.test2_alarm1}": [
    "ClassInstanceAttribute{model_query_annotated.Test2_C.a}",
    "Function{pysa._test_sink}"
  ],
  "Function{model_query_annotated.test2_alarm2}": [
    "ClassInstanceAttribute{model_query_annotated.Test2_C.x}",
    "Function{pysa._test_sink}"
  ],
  "Function{model_query_annotated.test2_noalarm1}": [
    "Function{pysa._test_sink}"
  ],
  "Function{model_query_annotated.test3_noalarm1}": [
    "Function{pysa._test_sink}"
  ],
  "Function{model_query_annotated.test3_noalarm2}": [
    "Function{pysa._test_sink}"
  ]
}