@generated
Call dependencies
{
  "Function{model_shaping._asdict_inner}": [
    "Function{builtins.getattr}", "Function{builtins.isinstance}",
    "Function{model_shaping._asdict_inner}",
    "Function{model_shaping._is_dataclass_instance}",
    "Function{model_shaping.fields}", "Function{typing.cast}",
    "Method{builtins.dict.items}", "Method{builtins.list.__iter__}",
    "Method{builtins.list.append}", "Method{builtins.tuple.__iter__}",
    "Method{builtins.type.__init__}", "Method{builtins.type.__new__}",
    "Method{typing.ItemsView.__iter__}", "Method{typing.Iterator.__next__}"
  ],
  "Function{model_shaping.asdict_test}": [ "Function{model_shaping.asdict}" ],
  "Function{model_shaping.asdict}": [
    "Function{model_shaping._asdict_inner}"
  ],
  "Function{model_shaping.obscure_test}": [
    "Function{pysa._test_source}", "Method{builtins.type.__init__}",
    "Method{builtins.type.__new__}"
  ],
  "Function{model_shaping.shape_multi_sink}": [
    "Function{pysa._rce}", "Function{pysa._sql}"
  ],
  "Function{model_shaping.shape_multi_source}": [
    "Function{pysa._cookies}", "Function{pysa._user_controlled}",
    "Method{_random.Random.random}", "Method{builtins.float.__gt__}"
  ],
  "Function{model_shaping.test_tito_shaping}": [
    "Function{model_shaping.tito_shaping}", "Function{pysa._test_sink}",
    "Function{pysa._test_source}", "Method{builtins.dict.__getitem__}"
  ],
  "Function{model_shaping.tito_shaping}": [
    "Method{builtins.dict.get}", "Method{builtins.object.__init__}",
    "Method{builtins.object.__repr__}", "Method{builtins.str.__new__}"
  ]
}