@generated
Call dependencies
{
  "Function{model_query_any_decorator.$toplevel}": [
    "Method{builtins.object.__init__}", "Method{builtins.object.__new__}"
  ],
  "Function{model_query_any_decorator.test1_alarm1@decorated}": [
    "Function{model_query_any_decorator.test1_d1}[formal(f, position=0)=Function{model_query_any_decorator.test1_alarm1}]"
  ],
  "Function{model_query_any_decorator.test1_noalarm1@decorated}": [
    "Function{model_query_any_decorator.test1_d2}[formal(f, position=0)=Function{model_query_any_decorator.test1_noalarm1}]"
  ],
  "Function{model_query_any_decorator.test2_alarm1@decorated}": [
    "Function{model_query_any_decorator.test2_d1}[formal(f, position=0)=Function{model_query_any_decorator.test2_alarm1}]"
  ],
  "Function{model_query_any_decorator.test2_noalarm1@decorated}": [
    "Function{model_query_any_decorator.test2_d2}[formal(f, position=0)=Function{model_query_any_decorator.test2_noalarm1}]"
  ],
  "Function{model_query_any_decorator.test3_alarm1@decorated}": [
    "Function{model_query_any_decorator.test3_d1}"
  ],
  "Function{model_query_any_decorator.test3_alarm2@decorated}": [
    "Function{model_query_any_decorator.test3_d1}"
  ],
  "Function{model_query_any_decorator.test3_alarm3@decorated}": [
    "Function{model_query_any_decorator.test3_d1}"
  ],
  "Function{model_query_any_decorator.test3_noalarm1@decorated}": [
    "Function{model_query_any_decorator.test3_d1}"
  ],
  "Function{model_query_any_decorator.test3_noalarm2@decorated}": [
    "Function{model_query_any_decorator.test3_d1}"
  ],
  "Function{model_query_any_decorator.test4_alarm1@decorated}": [
    "Function{model_query_any_decorator.test4_d1}"
  ],
  "Function{model_query_any_decorator.test4_noalarm1@decorated}": [
    "Function{model_query_any_decorator.test4_d1}"
  ],
  "Function{model_query_any_decorator.test4_noalarm2@decorated}": [
    "Function{model_query_any_decorator.test4_d1}"
  ],
  "Function{model_query_any_decorator.test4_noalarm3@decorated}": [
    "Function{model_query_any_decorator.test4_d1}"
  ],
  "Function{model_query_any_decorator.test5_alarm1@decorated}": [
    "Function{model_query_any_decorator.test5_d1}"
  ],
  "Function{model_query_any_decorator.test5_alarm2@decorated}": [
    "Function{model_query_any_decorator.test5_d1}"
  ],
  "Function{model_query_any_decorator.test5_noalarm1@decorated}": [
    "Function{model_query_any_decorator.test5_d1}"
  ],
  "Function{model_query_any_decorator.test5_noalarm2@decorated}": [
    "Function{model_query_any_decorator.test5_d1}"
  ],
  "Function{model_query_any_decorator.test_local_variable_method_decorator@decorated}": [
    "Method{model_query_any_decorator.Application.decorator}[formal(f, position=1)=Function{model_query_any_decorator.test_local_variable_method_decorator}]"
  ]
}