@generated
Call dependencies
{
  "Function{model_query_type_annotation.test5_no_taint_1}": [
    "Method{builtins.object.__init__}", "Method{builtins.object.__new__}"
  ],
  "Function{model_query_type_annotation.test5_taint_1}": [
    "Method{builtins.object.__init__}", "Method{builtins.object.__new__}"
  ],
  "Function{model_query_type_annotation.test5_taint_2}": [
    "Method{builtins.object.__init__}", "Method{builtins.object.__new__}"
  ]
}