@generated
Call dependencies
{
  "Function{model_query_parameters_viatypeof.test1_alarm1}": [
    "Function{model_query_parameters_viatypeof.test1_f1}",
    "Function{pysa._test_source}"
  ],
  "Function{model_query_parameters_viatypeof.test1_alarm2}": [
    "Function{model_query_parameters_viatypeof.test1_f1}",
    "Function{pysa._test_source}"
  ],
  "Function{model_query_parameters_viatypeof.test1_alarm3}": [
    "Function{model_query_parameters_viatypeof.test1_f1}",
    "Function{pysa._test_source}"
  ],
  "Function{model_query_parameters_viatypeof.test1_noalarm1}": [
    "Function{model_query_parameters_viatypeof.test1_f1}"
  ],
  "Function{model_query_parameters_viatypeof.test2_alarm1}": [
    "Function{pysa._test_source}",
    "Method{model_query_parameters_viatypeof.Test2_C.f1}"
  ],
  "Function{model_query_parameters_viatypeof.test2_alarm2}": [
    "Function{pysa._test_source}",
    "Method{model_query_parameters_viatypeof.Test2_C.f1}"
  ],
  "Function{model_query_parameters_viatypeof.test2_alarm3}": [
    "Function{pysa._test_source}",
    "Method{model_query_parameters_viatypeof.Test2_C.f1}"
  ],
  "Function{model_query_parameters_viatypeof.test2_alarm4}": [
    "Function{pysa._test_source}",
    "Method{model_query_parameters_viatypeof.Test2_C.f2}"
  ],
  "Function{model_query_parameters_viatypeof.test2_alarm5}": [
    "Function{pysa._test_source}",
    "Method{model_query_parameters_viatypeof.Test2_C.f2}"
  ],
  "Function{model_query_parameters_viatypeof.test2_alarm6}": [
    "Function{pysa._test_source}",
    "Method{model_query_parameters_viatypeof.Test2_C.f2}"
  ],
  "Function{model_query_parameters_viatypeof.test2_noalarm1}": [
    "Method{model_query_parameters_viatypeof.Test2_C.f1}"
  ],
  "Function{model_query_parameters_viatypeof.test2_noalarm2}": [
    "Method{builtins.object.__init__}", "Method{builtins.object.__new__}",
    "Method{model_query_parameters_viatypeof.Test2_C.f2}"
  ],
  "Function{model_query_parameters_viatypeof.test3_alarm1}": [
    "Function{model_query_parameters_viatypeof.test3_f1}",
    "Function{pysa._test_source}"
  ],
  "Function{model_query_parameters_viatypeof.test3_alarm2}": [
    "Function{model_query_parameters_viatypeof.test3_f1}",
    "Function{pysa._test_source}"
  ],
  "Function{model_query_parameters_viatypeof.test3_alarm3}": [
    "Function{model_query_parameters_viatypeof.test3_f1}",
    "Function{pysa._test_source}"
  ],
  "Function{model_query_parameters_viatypeof.test3_noalarm1}": [
    "Function{model_query_parameters_viatypeof.test3_f1}"
  ]
}