@generated
Call dependencies
{
  "Function{multiple_sources_string_operations.format_string_issue_string_literal}": [
    "Function{multiple_sources_string_operations.user_controlled_input}",
    "Method{builtins.str.__format__}"
  ],
  "Function{multiple_sources_string_operations.format_string_issue_with_multiple_triggered_user_controlled}": [
    "Function{multiple_sources_string_operations.format_string_multiple_triggered_user_controlled}",
    "Function{multiple_sources_string_operations.user_controlled_input}"
  ],
  "Function{multiple_sources_string_operations.format_string_issue_with_triggered_sql}": [
    "Function{multiple_sources_string_operations.format_string_triggered_sql}"
  ],
  "Function{multiple_sources_string_operations.format_string_issue_with_triggered_user_controlled}": [
    "Function{multiple_sources_string_operations.format_string_triggered_user_controlled}",
    "Function{multiple_sources_string_operations.user_controlled_input}"
  ],
  "Function{multiple_sources_string_operations.format_string_issue}": [
    "Function{multiple_sources_string_operations.user_controlled_input}",
    "Method{builtins.int.__format__}", "Method{builtins.str.__format__}"
  ],
  "Function{multiple_sources_string_operations.format_string_multiple_issues_string_literal}": [
    "Function{multiple_sources_string_operations.user_controlled_input}",
    "Method{builtins.str.__format__}"
  ],
  "Function{multiple_sources_string_operations.format_string_no_issue_when_single_sink_parameter}": [
    "Function{multiple_sources_string_operations.user_controlled_input}",
    "Method{_random.Random.random}", "Method{builtins.float.__gt__}",
    "Method{builtins.str.__format__}"
  ],
  "Function{multiple_sources_string_operations.format_string_triggered_sql}": [
    "Function{multiple_sources_string_operations.user_controlled_input}",
    "Method{builtins.str.__format__}"
  ],
  "Function{multiple_sources_string_operations.format_string_triggered_user_controlled}": [
    "Method{builtins.str.__format__}"
  ],
  "Function{multiple_sources_string_operations.nested_stradd_and_fstring}": [
    "Function{multiple_sources_string_operations.user_controlled_input}",
    "Method{builtins.str.__add__}", "Method{builtins.str.__format__}"
  ],
  "Function{multiple_sources_string_operations.stradd_tito_triggered_user_controlled}": [
    "Function{multiple_sources_string_operations.tito}",
    "Function{multiple_sources_string_operations.user_controlled_input}",
    "Method{builtins.str.__add__}"
  ],
  "Function{multiple_sources_string_operations.stradd_triggered_user_controlled}": [
    "Function{multiple_sources_string_operations.user_controlled_input}",
    "Method{builtins.str.__add__}"
  ],
  "Function{multiple_sources_string_operations.string_operations}": [
    "Function{multiple_sources_string_operations.user_controlled_input}",
    "Method{builtins.str.__add__}", "Method{builtins.str.__mod__}",
    "Method{builtins.str.format}"
  ],
  "Function{multiple_sources_string_operations.test_large_string_add}": [
    "Method{builtins.int.__mul__}", "Method{builtins.int.__new__}",
    "Method{builtins.object.__init__}", "Method{builtins.object.__repr__}",
    "Method{builtins.str.__add__}", "Method{builtins.str.__new__}"
  ],
  "Method{multiple_sources_string_operations.DatabaseSchemaEditor.string_operations}": [
    "Function{multiple_sources_string_operations.user_controlled_input}",
    "Method{builtins.str.format}"
  ]
}