@generated
Call dependencies
{
  "Function{multiple_sources_with_filters.first_source_distance_one}": [
    "Function{multiple_sources_with_filters.first_source_distance_zero}"
  ],
  "Function{multiple_sources_with_filters.first_source_distance_zero}": [
    "Function{multiple_sources_with_filters.first_source}"
  ],
  "Function{multiple_sources_with_filters.second_source_distance_one}": [
    "Function{multiple_sources_with_filters.second_source_distance_zero}"
  ],
  "Function{multiple_sources_with_filters.second_source_distance_zero}": [
    "Function{multiple_sources_with_filters.second_source}"
  ],
  "Function{multiple_sources_with_filters.sink_distance_one}": [
    "Function{multiple_sources_with_filters.sink_distance_zero}"
  ],
  "Function{multiple_sources_with_filters.sink_distance_zero}": [
    "Function{multiple_sources_with_filters.first_source}",
    "Function{multiple_sources_with_filters.multi_sink}"
  ],
  "Function{multiple_sources_with_filters.test_first_source_one_second_source_one}": [
    "Function{multiple_sources_with_filters.first_source_distance_zero}",
    "Function{multiple_sources_with_filters.multi_sink}",
    "Function{multiple_sources_with_filters.second_source_distance_zero}"
  ],
  "Function{multiple_sources_with_filters.test_first_source_two_second_source_two}": [
    "Function{multiple_sources_with_filters.first_source_distance_one}",
    "Function{multiple_sources_with_filters.multi_sink}",
    "Function{multiple_sources_with_filters.second_source_distance_one}"
  ],
  "Function{multiple_sources_with_filters.test_first_source_zero_second_source_zero}": [
    "Function{multiple_sources_with_filters.first_source}",
    "Function{multiple_sources_with_filters.multi_sink}",
    "Function{multiple_sources_with_filters.second_source}"
  ],
  "Function{multiple_sources_with_filters.test_sink_distance_one_second_source_two}": [
    "Function{multiple_sources_with_filters.second_source_distance_one}",
    "Function{multiple_sources_with_filters.sink_distance_zero}"
  ],
  "Function{multiple_sources_with_filters.test_sink_distance_one}": [
    "Function{multiple_sources_with_filters.second_source}",
    "Function{multiple_sources_with_filters.sink_distance_zero}"
  ],
  "Function{multiple_sources_with_filters.test_sink_distance_two}": [
    "Function{multiple_sources_with_filters.second_source}",
    "Function{multiple_sources_with_filters.sink_distance_one}"
  ]
}