@generated
Call dependencies
{
  "Function{multiple_sources_string_operations_with_filters.first_source_distance_one}": [
    "Function{multiple_sources_string_operations_with_filters.first_source_distance_zero}"
  ],
  "Function{multiple_sources_string_operations_with_filters.first_source_distance_zero}": [
    "Function{multiple_sources_string_operations_with_filters.first_source}"
  ],
  "Function{multiple_sources_string_operations_with_filters.second_source_distance_one}": [
    "Function{multiple_sources_string_operations_with_filters.second_source_distance_zero}"
  ],
  "Function{multiple_sources_string_operations_with_filters.sink_distance_one}": [
    "Function{multiple_sources_string_operations_with_filters.sink_distance_zero}"
  ],
  "Function{multiple_sources_string_operations_with_filters.sink_distance_zero}": [
    "Method{builtins.str.__add__}"
  ],
  "Function{multiple_sources_string_operations_with_filters.test_first_source_one_second_source_one}": [
    "Function{multiple_sources_string_operations_with_filters.first_source_distance_zero}",
    "Function{multiple_sources_string_operations_with_filters.second_source_distance_zero}",
    "Method{builtins.str.__add__}"
  ],
  "Function{multiple_sources_string_operations_with_filters.test_first_source_one_second_source_zero}": [
    "Function{multiple_sources_string_operations_with_filters.first_source_distance_zero}",
    "Method{builtins.str.__add__}"
  ],
  "Function{multiple_sources_string_operations_with_filters.test_first_source_two_second_source_two}": [
    "Function{multiple_sources_string_operations_with_filters.first_source_distance_one}",
    "Function{multiple_sources_string_operations_with_filters.second_source_distance_one}",
    "Method{builtins.str.__add__}"
  ],
  "Function{multiple_sources_string_operations_with_filters.test_first_source_zero_second_source_one}": [
    "Function{multiple_sources_string_operations_with_filters.first_source}",
    "Function{multiple_sources_string_operations_with_filters.second_source_distance_zero}",
    "Method{builtins.str.__add__}"
  ],
  "Function{multiple_sources_string_operations_with_filters.test_first_source_zero_second_source_zero}": [
    "Function{multiple_sources_string_operations_with_filters.first_source}",
    "Method{builtins.str.__add__}"
  ],
  "Function{multiple_sources_string_operations_with_filters.test_sink_one_first_source_zero}": [
    "Function{multiple_sources_string_operations_with_filters.first_source}",
    "Function{multiple_sources_string_operations_with_filters.sink_distance_one}"
  ],
  "Function{multiple_sources_string_operations_with_filters.test_sink_zero_first_source_zero}": [
    "Function{multiple_sources_string_operations_with_filters.first_source}",
    "Function{multiple_sources_string_operations_with_filters.sink_distance_zero}"
  ]
}