@generated
Call dependencies
{
  "Function{multiple_sources.combine_c_d_and_c_e}": [
    "Function{multiple_sources.c_source}",
    "Function{multiple_sources.d_source}",
    "Function{multiple_sources.e_source}",
    "Function{multiple_sources.multi_sink_share_both_sinks}"
  ],
  "Function{multiple_sources.combine_tainted_user_and_dangerous_vc}": [
    "Function{multiple_sources.permissive_context}",
    "Function{multiple_sources.user_controlled_input}",
    "Method{multiple_sources.Node.get}", "Method{multiple_sources.Node.send}"
  ],
  "Function{multiple_sources.demonstrate_triggered_c_from_d_and_e}": [
    "Function{multiple_sources.d_source}",
    "Function{multiple_sources.e_source}",
    "Function{multiple_sources.multi_sink_share_both_sinks}"
  ],
  "Function{multiple_sources.demonstrate_triggered_c_from_d_or_e}": [
    "Function{multiple_sources.d_source}",
    "Function{multiple_sources.e_source}",
    "Function{multiple_sources.multi_sink_share_both_sinks}",
    "Method{_random.Random.random}", "Method{builtins.float.__gt__}"
  ],
  "Function{multiple_sources.demonstrate_triggered_c_from_d}": [
    "Function{multiple_sources.d_source}",
    "Function{multiple_sources.multi_sink_share_both_sinks}"
  ],
  "Function{multiple_sources.demonstrate_triggered_context_more_hops}": [
    "Function{multiple_sources.user_controlled_input_wrapper}",
    "Method{multiple_sources.Node.get}", "Method{multiple_sources.Node.send}"
  ],
  "Function{multiple_sources.demonstrate_triggered_context}": [
    "Function{multiple_sources.user_controlled_input}",
    "Method{multiple_sources.Node.get}", "Method{multiple_sources.Node.send}"
  ],
  "Function{multiple_sources.demonstrate_triggered_d_and_e}": [
    "Function{multiple_sources.c_source}",
    "Function{multiple_sources.multi_sink_share_both_sinks}"
  ],
  "Function{multiple_sources.demonstrate_triggered_input}": [
    "Function{multiple_sources.permissive_context}",
    "Method{multiple_sources.Node.get}", "Method{multiple_sources.Node.send}"
  ],
  "Function{multiple_sources.issue_with_sanitizer}": [
    "Function{multiple_sources.a_source}",
    "Function{multiple_sources.combines_tests_and_context}",
    "Function{multiple_sources.permissive_context}",
    "Function{multiple_sources.sanitize_sink_a_tito}"
  ],
  "Function{multiple_sources.issue_with_test_a_and_b}": [
    "Function{multiple_sources.a_source}",
    "Function{multiple_sources.b_source}",
    "Function{multiple_sources.combines_tests_and_context}",
    "Function{multiple_sources.permissive_context}"
  ],
  "Function{multiple_sources.issue_with_triggered_c_from_d_and_e}": [
    "Function{multiple_sources.c_source}",
    "Function{multiple_sources.demonstrate_triggered_c_from_d_and_e}"
  ],
  "Function{multiple_sources.issue_with_triggered_c_from_d_or_e}": [
    "Function{multiple_sources.c_source}",
    "Function{multiple_sources.demonstrate_triggered_c_from_d_or_e}"
  ],
  "Function{multiple_sources.issue_with_triggered_c_from_d}": [
    "Function{multiple_sources.c_source}",
    "Function{multiple_sources.demonstrate_triggered_c_from_d}"
  ],
  "Function{multiple_sources.issue_with_triggered_context_more_hops}": [
    "Function{multiple_sources.demonstrate_triggered_context_more_hops}",
    "Function{multiple_sources.permissive_context}"
  ],
  "Function{multiple_sources.issue_with_triggered_context}": [
    "Function{multiple_sources.demonstrate_triggered_context}",
    "Function{multiple_sources.permissive_context}"
  ],
  "Function{multiple_sources.issue_with_triggered_d_and_e}": [
    "Function{multiple_sources.d_source}",
    "Function{multiple_sources.demonstrate_triggered_d_and_e}",
    "Function{multiple_sources.e_source}"
  ],
  "Function{multiple_sources.issue_with_triggered_input}": [
    "Function{multiple_sources.demonstrate_triggered_input}",
    "Function{multiple_sources.user_controlled_input}"
  ],
  "Function{multiple_sources.issue_with_wrapper_node_get_send_triggered_context}": [
    "Function{multiple_sources.permissive_context}",
    "Function{multiple_sources.wrapper_node_get_send_triggered_context}"
  ],
  "Function{multiple_sources.issue_with_wrapper_node_get_send}": [
    "Function{multiple_sources.permissive_context}",
    "Function{multiple_sources.user_controlled_input}",
    "Function{multiple_sources.wrapper_node_get_send}"
  ],
  "Function{multiple_sources.muliple_main_issues_1}": [
    "Function{multiple_sources.permissive_context}",
    "Function{multiple_sources.user_controlled_input}",
    "Method{multiple_sources.A.multi_sink}",
    "Method{multiple_sources.B.multi_sink}"
  ],
  "Function{multiple_sources.muliple_main_issues_2}": [
    "Function{multiple_sources.multiple_triggered_context}",
    "Function{multiple_sources.permissive_context}"
  ],
  "Function{multiple_sources.multiple_triggered_context}": [
    "Function{multiple_sources.user_controlled_input}",
    "Method{multiple_sources.Node.get}", "Method{multiple_sources.Node.send}"
  ],
  "Function{multiple_sources.no_issue_with_transform}": [
    "Function{multiple_sources.a_source}",
    "Function{multiple_sources.combines_tests_and_context}",
    "Function{multiple_sources.permissive_context}",
    "Function{multiple_sources.transform_t}"
  ],
  "Function{multiple_sources.no_issue_with_wrong_label}": [
    "Function{multiple_sources.demonstrate_triggered_input}",
    "Function{multiple_sources.permissive_context}"
  ],
  "Function{multiple_sources.no_sink_with_sanitizer}": [
    "Function{multiple_sources.combines_tests_and_context}",
    "Function{multiple_sources.permissive_context}",
    "Function{multiple_sources.sanitize_source_a_tito}",
    "Function{multiple_sources.sanitize_source_b_tito}"
  ],
  "Function{multiple_sources.no_sink_with_transform}": [
    "Function{multiple_sources.a_source}",
    "Function{multiple_sources.combines_tests_and_context}",
    "Function{multiple_sources.transform_t}"
  ],
  "Function{multiple_sources.user_controlled_input_wrapper}": [
    "Function{multiple_sources.user_controlled_input}"
  ],
  "Function{multiple_sources.wrapper_combined_node_get_send}": [
    "Method{_random.Random.random}", "Method{builtins.float.__gt__}",
    "Method{multiple_sources.Node.get}", "Method{multiple_sources.Node.send}"
  ],
  "Function{multiple_sources.wrapper_mismatched_partial_sinks}": [
    "Method{multiple_sources.Node.get}", "Method{multiple_sources.Node.send}"
  ],
  "Function{multiple_sources.wrapper_node_get_send_triggered_context}": [
    "Function{multiple_sources.user_controlled_input}",
    "Function{multiple_sources.wrapper_node_get_send}"
  ],
  "Function{multiple_sources.wrapper_node_get_send}": [
    "Method{multiple_sources.Node.get}", "Method{multiple_sources.Node.send}"
  ],
  "Function{multiple_sources.wrapper_node_send}": [
    "Method{multiple_sources.Node.get}", "Method{multiple_sources.Node.send}"
  ],
  "Method{multiple_sources.Node.get}": [
    "Method{builtins.object.__new__}",
    "Method{multiple_sources.Node.__init__}"
  ]
}