@generated
Call dependencies
{
  "Function{multi_sink_ports.issue2}": [
    "Function{multi_sink_ports.source}",
    "Function{multi_sink_ports.wrapper2}",
    "Method{builtins.object.__init__}", "Method{builtins.object.__new__}",
    "Method{multi_sink_ports.Query.params}"
  ],
  "Function{multi_sink_ports.issue}": [
    "Function{multi_sink_ports.source}", "Function{multi_sink_ports.wrapper}"
  ],
  "Function{multi_sink_ports.log_call}": [
    "Function{multi_sink_ports.sinkA}"
  ],
  "Function{multi_sink_ports.splitwrapper}": [
    "Function{multi_sink_ports.split}"
  ],
  "Function{multi_sink_ports.split}": [
    "Function{multi_sink_ports.sinkB}", "Function{multi_sink_ports.sinkC}",
    "Function{multi_sink_ports.sinkD}"
  ],
  "Function{multi_sink_ports.wrapper2}": [
    "Function{builtins.isinstance}", "Function{multi_sink_ports.log_call}",
    "Method{multi_sink_ports.Query.send}"
  ],
  "Function{multi_sink_ports.wrapper}": [
    "Function{multi_sink_ports.sinkA}", "Function{multi_sink_ports.split}"
  ],
  "Method{multi_sink_ports.Query.send}": [
    "Function{multi_sink_ports.splitwrapper}"
  ]
}