@generated
Call dependencies
{
  "Function{mutate_self.free_function_mutates_self}": [
    "Function{pysa._test_source}"
  ],
  "Function{mutate_self.issue_free_function}": [
    "Function{mutate_self.free_function_mutates_self}",
    "Method{builtins.object.__new__}", "Method{mutate_self.Base.__init__}",
    "Method{mutate_self.Base.bar_sink}", "Method{mutate_self.Base.foo_sink}"
  ],
  "Function{mutate_self.issue_mutates_foo_and_returns_instance}": [
    "Method{builtins.object.__new__}", "Method{mutate_self.Base.__init__}",
    "Method{mutate_self.Base.foo_sink}",
    "Method{mutate_self.Base.mutates_foo_and_returns}"
  ],
  "Function{mutate_self.issue_mutates_foo_instance}": [
    "Method{builtins.object.__new__}", "Method{mutate_self.Base.__init__}",
    "Method{mutate_self.Base.bar_sink}", "Method{mutate_self.Base.foo_sink}",
    "Method{mutate_self.Base.mutates_foo}"
  ],
  "Method{mutate_self.Base.bar_sink}": [ "Function{pysa._test_sink}" ],
  "Method{mutate_self.Base.foo_sink}": [ "Function{pysa._test_sink}" ],
  "Method{mutate_self.Base.isssue_mutates_foo}": [
    "Method{mutate_self.Base.bar_sink}", "Method{mutate_self.Base.foo_sink}",
    "Method{mutate_self.Base.mutates_foo}"
  ],
  "Method{mutate_self.Base.issue_mutates_and_returns}": [
    "Method{mutate_self.Base.foo_sink}",
    "Method{mutate_self.Base.mutates_foo_and_returns}"
  ],
  "Method{mutate_self.Base.issue_mutates_foo_self_annotation}": [
    "Method{mutate_self.Base.bar_sink}", "Method{mutate_self.Base.foo_sink}",
    "Method{mutate_self.Base.mutates_foo_self_annotation}"
  ],
  "Method{mutate_self.Base.issue_mutates_foo_self_typevar}": [
    "Method{mutate_self.Base.bar_sink}", "Method{mutate_self.Base.foo_sink}",
    "Method{mutate_self.Base.mutates_foo_self_typevar}"
  ],
  "Method{mutate_self.Base.issue_mutates_foo_with_hop}": [
    "Method{mutate_self.Base.bar_sink}", "Method{mutate_self.Base.foo_sink}",
    "Method{mutate_self.Base.mutates_foo_with_hop}"
  ],
  "Method{mutate_self.Base.mutates_foo_and_returns}": [
    "Function{pysa._test_source}"
  ],
  "Method{mutate_self.Base.mutates_foo_self_annotation}": [
    "Function{pysa._test_source}"
  ],
  "Method{mutate_self.Base.mutates_foo_self_typevar}": [
    "Function{pysa._test_source}"
  ],
  "Method{mutate_self.Base.mutates_foo_with_hop}": [
    "Method{mutate_self.Base.mutates_foo}"
  ],
  "Method{mutate_self.Base.mutates_foo}": [ "Function{pysa._test_source}" ]
}