@generated
Call dependencies
{
  "Function{named_tuples.aliased_indicies_backward_unknown_attribute}": [
    "Function{pysa._test_sink}", "Method{builtins.tuple.__getitem__}"
  ],
  "Function{named_tuples.aliased_indicies_backward}": [
    "Function{pysa._test_sink}", "Method{builtins.tuple.__getitem__}"
  ],
  "Function{named_tuples.aliased_indicies_forward_unknown_attribute}": [
    "Function{named_tuples.tainted_tuple}",
    "Method{builtins.tuple.__getitem__}"
  ],
  "Function{named_tuples.aliased_indicies_forward}": [
    "Function{named_tuples.tainted_tuple}", "Function{pysa._test_sink}",
    "Method{builtins.tuple.__getitem__}"
  ],
  "Function{named_tuples.inherited_tuple_with_all_defaults}": [
    "Function{pysa._test_source}",
    "Method{named_tuples.InheritedNamedTupleWithAllDefaults.__init__}",
    "Method{named_tuples.InheritedNamedTupleWithAllDefaults.__new__}"
  ],
  "Function{named_tuples.inherited_tuple_with_default}": [
    "Function{pysa._test_source}",
    "Method{named_tuples.InheritedNamedTupleWithDefault.__init__}",
    "Method{named_tuples.InheritedNamedTupleWithDefault.__new__}"
  ],
  "Function{named_tuples.inherited_tuple}": [
    "Function{pysa._test_source}",
    "Method{named_tuples.InheritedNamedTuple.__init__}",
    "Method{named_tuples.InheritedNamedTuple.__new__}"
  ],
  "Function{named_tuples.issue_with_bad}": [
    "Function{named_tuples.tainted_tuple}", "Function{pysa._test_sink}"
  ],
  "Function{named_tuples.issue_with_inherited_named_tuple_with_all_defaults}": [
    "Function{named_tuples.inherited_tuple_with_all_defaults}",
    "Function{pysa._test_sink}"
  ],
  "Function{named_tuples.issue_with_inherited_named_tuple_with_default}": [
    "Function{named_tuples.inherited_tuple_with_default}",
    "Function{pysa._test_sink}"
  ],
  "Function{named_tuples.issue_with_inherited_named_tuple}": [
    "Function{named_tuples.inherited_tuple}", "Function{pysa._test_sink}"
  ],
  "Function{named_tuples.issue_with_named_tuple_with_tainted_attribute}": [
    "Function{pysa._test_source}",
    "Method{named_tuples.NamedTupleWithTaintedAttribute.__init__}",
    "Method{named_tuples.NamedTupleWithTaintedAttribute.__new__}"
  ],
  "Function{named_tuples.issue_with_old_school_named_tuples}": [
    "Function{named_tuples.tainted_old_tuple}", "Function{pysa._test_sink}"
  ],
  "Function{named_tuples.no_issue_with_benign_in_inherited_named_tuple}": [
    "Function{named_tuples.inherited_tuple}", "Function{pysa._test_sink}"
  ],
  "Function{named_tuples.no_issue_with_benign}": [
    "Function{named_tuples.tainted_tuple}", "Function{pysa._test_sink}"
  ],
  "Function{named_tuples.no_issue_with_old_school_named_tuples}": [
    "Function{named_tuples.tainted_old_tuple}", "Function{pysa._test_sink}"
  ],
  "Function{named_tuples.tainted_old_tuple}": [
    "Function{pysa._test_source}",
    "Method{named_tuples.OldSchoolNamedTuple.__init__}",
    "Method{named_tuples.OldSchoolNamedTuple.__new__}"
  ],
  "Function{named_tuples.tainted_tuple}": [
    "Function{pysa._test_source}",
    "Method{named_tuples.MyNamedTuple.__init__}",
    "Method{named_tuples.MyNamedTuple.__new__}"
  ]
}