@generated
Call dependencies
{
  "Function{named_tuple_asdict.sink_on_asdict_pop_value}": [
    "Function{pysa._test_sink}",
    "Method{_typeshed._type_checker_internals.NamedTupleFallback._asdict}",
    "Method{builtins.dict.pop}"
  ],
  "Function{named_tuple_asdict.sink_on_charset_direct}": [
    "Function{pysa._test_sink}"
  ],
  "Function{named_tuple_asdict.sink_on_charset_via_asdict_getitem}": [
    "Function{pysa._test_sink}",
    "Method{_typeshed._type_checker_internals.NamedTupleFallback._asdict}",
    "Method{builtins.dict.__getitem__}"
  ],
  "Function{named_tuple_asdict.sink_on_charset_via_asdict_pop}": [
    "Function{pysa._test_sink}",
    "Method{_typeshed._type_checker_internals.NamedTupleFallback._asdict}",
    "Method{builtins.dict.pop}"
  ]
}