@generated
Call dependencies
{
  "Function{nested_callables.access_parameter_in_inner_scope_sink.inner}": [
    "Function{pysa._test_sink}"
  ],
  "Function{nested_callables.access_parameter_in_inner_scope_sink}": [
    "Function{nested_callables.access_parameter_in_inner_scope_sink.inner}"
  ],
  "Function{nested_callables.access_parameter_in_inner_scope_tito}": [
    "Function{nested_callables.access_parameter_in_inner_scope_tito.inner}"
  ],
  "Function{nested_callables.access_variables_in_outer_scope_issue.inner}": [
    "Function{pysa._test_sink}"
  ],
  "Function{nested_callables.access_variables_in_outer_scope_issue}": [
    "Function{nested_callables.access_variables_in_outer_scope_issue.inner}",
    "Function{pysa._test_source}"
  ],
  "Function{nested_callables.access_variables_in_outer_scope_source}": [
    "Function{nested_callables.access_variables_in_outer_scope_source.inner}",
    "Function{pysa._test_source}"
  ],
  "Function{nested_callables.call_outer}": [
    "Function{nested_callables.outer}", "Function{pysa._test_source}"
  ],
  "Function{nested_callables.duplicate_function$2}": [
    "Function{nested_callables.foo}"
  ],
  "Function{nested_callables.duplicate_function}": [
    "Function{nested_callables.foo}"
  ],
  "Function{nested_callables.foo.inner_with_model}": [
    "Function{pysa._test_source}"
  ],
  "Function{nested_callables.foo.inner}": [
    "Function{pysa._test_sink}", "Function{pysa._test_source}"
  ],
  "Function{nested_callables.nested_global_function.g}": [
    "Method{builtins.str.__add__}"
  ],
  "Function{nested_callables.nested_global_function}": [
    "Function{nested_callables.nested_global_function.g}"
  ],
  "Function{nested_callables.outer.inner}": [ "Function{pysa._test_sink}" ],
  "Function{nested_callables.outer_calling_other_function.inner_calling_other_function}": [
    "Function{nested_callables.some_sink}"
  ],
  "Function{nested_callables.outer_calling_other_function}": [
    "Function{nested_callables.outer_calling_other_function.inner_calling_other_function}"
  ],
  "Function{nested_callables.outer}": [
    "Function{nested_callables.outer.inner}"
  ],
  "Function{nested_callables.parameter_function.add}": [
    "Method{builtins.str.__add__}"
  ],
  "Function{nested_callables.parameter_function}": [
    "Function{nested_callables.parameter_function.add}"
  ],
  "Function{nested_callables.some_sink}": [ "Function{pysa._test_sink}" ],
  "Function{nested_callables.test_access_parameter_in_inner_scope_sink}": [
    "Function{nested_callables.access_parameter_in_inner_scope_sink}",
    "Function{pysa._test_source}"
  ],
  "Function{nested_callables.test_access_parameter_in_inner_scope_tito}": [
    "Function{nested_callables.access_parameter_in_inner_scope_tito}",
    "Function{pysa._test_sink}", "Function{pysa._test_source}"
  ],
  "Function{nested_callables.test_access_variables_in_outer_scope_source}": [
    "Function{nested_callables.access_variables_in_outer_scope_source}",
    "Function{pysa._test_sink}"
  ],
  "Function{nested_callables.test_mutation_of_class.set_a}": [
    "Function{pysa._test_source}"
  ],
  "Function{nested_callables.test_mutation_of_class}": [
    "Function{nested_callables.test_mutation_of_class.set_a}",
    "Function{pysa._test_sink}", "Method{builtins.object.__init__}",
    "Method{builtins.object.__new__}"
  ]
}