@generated
Call dependencies
{
  "Function{obscure_models.should_collapse_depth_zero}": [
    "Method{obscure_models.C.obscure}"
  ],
  "Function{obscure_models.test_collapse_depth}": [
    "Function{obscure_models.should_collapse_depth_zero}",
    "Function{pysa._test_sink}", "Function{pysa._test_source}",
    "Method{builtins.object.__init__}", "Method{builtins.object.__new__}"
  ],
  "Function{obscure_models.test_collapse_source}": [
    "Function{pysa._test_sink}", "Function{pysa._test_source}",
    "Method{obscure_models.C.obscure}"
  ],
  "Function{obscure_models.test_issue}": [
    "Function{pysa._test_sink}", "Function{pysa._test_source}",
    "Method{obscure_models.C.obscure}"
  ],
  "Function{obscure_models.test_obscure_from_model}": [
    "Function{obscure_models.obscure_from_model}",
    "Function{pysa._test_sink}", "Function{pysa._test_source}"
  ],
  "Function{obscure_models.test_obscure_with_multiple_models}": [
    "Function{pysa._test_source}",
    "Method{obscure_models.C.obscure_with_multiple_models}"
  ],
  "Function{obscure_models.test_obscure_with_skip_inlining}": [
    "Function{pysa._test_source}",
    "Method{obscure_models.C.obscure_with_skip_inlining}"
  ],
  "Function{obscure_models.test_obscure_with_skip_obscure_and_tito}": [
    "Function{pysa._test_source}",
    "Method{obscure_models.C.obscure_with_skip_obscure_and_tito}"
  ],
  "Function{obscure_models.test_obscure_with_skip_obscure}": [
    "Function{pysa._test_source}",
    "Method{obscure_models.C.obscure_with_skip_obscure}"
  ],
  "Function{obscure_models.test_obscure_with_skip_overrides}": [
    "Function{pysa._test_source}",
    "Method{obscure_models.C.obscure_with_skip_overrides}"
  ],
  "Function{obscure_models.test_obscure_with_source}": [
    "Function{pysa._test_source}",
    "Method{obscure_models.C.obscure_with_source}"
  ],
  "Function{obscure_models.test_obscure_with_tito}": [
    "Function{pysa._test_sink}", "Function{pysa._test_source}",
    "Method{obscure_models.C.obscure_with_tito}"
  ],
  "Function{obscure_models.test_obscure}": [
    "Function{pysa._test_source}", "Method{obscure_models.C.obscure}"
  ],
  "Function{obscure_models.test_sink_collapse}": [
    "Function{pysa._test_sink}", "Method{obscure_models.C.obscure}"
  ]
}