@generated
Call dependencies
{
  "Function{obscure_tito.test_obscure_return}": [
    "Function{pysa._test_source}", "Method{builtins.object.__init__}",
    "Method{builtins.object.__new__}", "Override{obscure_tito.C.update}"
  ],
  "Function{obscure_tito.test_obscure_sink}": [
    "Method{builtins.object.__init__}", "Method{builtins.object.__new__}",
    "Override{obscure_tito.C.taint_parameter}"
  ],
  "Function{obscure_tito.test_obscure_tito}": [
    "Function{pysa._test_source}", "Method{builtins.object.__init__}",
    "Method{builtins.object.__new__}", "Override{obscure_tito.C.update}"
  ]
}