@generated
Call dependencies
{
  "Function{optionals.$toplevel}": [
    "Method{builtins.object.__init__}", "Method{builtins.object.__new__}"
  ],
  "Function{optionals.test}": [
    "Function{pysa._test_source}", "Method{optionals.Client.offer}",
    "Method{optionals.ClientSingleton.get_instance}"
  ],
  "Method{optionals.Client.offer}": [ "Function{pysa._test_sink}" ],
  "Method{optionals.ClientSingleton.get_instance}": [
    "Method{builtins.object.__init__}", "Method{builtins.object.__new__}"
  ]
}