@generated
Call dependencies
{
  "Function{overmatching.issue_source_on_0_and_star_to_sink_on_0_and_star}": [
    "Function{overmatching.sink_on_0_and_star}",
    "Function{pysa._test_source}", "Method{builtins.dict.__setitem__}"
  ],
  "Function{overmatching.issue_source_on_0_and_star_to_sink_on_0}": [
    "Function{overmatching.sink_on_0}", "Function{pysa._test_source}",
    "Method{builtins.dict.__setitem__}"
  ],
  "Function{overmatching.issue_source_on_0_to_sink_on_0_and_star}": [
    "Function{overmatching.sink_on_0_and_star}",
    "Function{pysa._test_source}", "Method{builtins.dict.__setitem__}"
  ],
  "Function{overmatching.issue_source_on_0_to_sink_on_0}": [
    "Function{overmatching.sink_on_0}", "Function{pysa._test_source}",
    "Method{builtins.dict.__setitem__}"
  ],
  "Function{overmatching.issue_source_on_1_to_sink_on_0_and_star}": [
    "Function{overmatching.sink_on_0_and_star}",
    "Function{pysa._test_source}", "Method{builtins.dict.__setitem__}"
  ],
  "Function{overmatching.issue_source_on_star_to_sink_on_0_and_star}": [
    "Function{overmatching.sink_on_0_and_star}",
    "Function{pysa._test_source}", "Method{builtins.dict.__setitem__}"
  ],
  "Function{overmatching.issue_source_on_star_to_sink_on_0}": [
    "Function{overmatching.sink_on_0}", "Function{pysa._test_source}",
    "Method{builtins.dict.__setitem__}"
  ],
  "Function{overmatching.no_issue_source_on_1_to_sink_on_0}": [
    "Function{overmatching.sink_on_0}", "Function{pysa._test_source}",
    "Method{builtins.dict.__setitem__}"
  ],
  "Function{overmatching.sink_on_0_and_star}": [
    "Function{pysa._test_sink}", "Method{builtins.dict.__getitem__}"
  ],
  "Function{overmatching.sink_on_0}": [
    "Function{pysa._test_sink}", "Method{builtins.dict.__getitem__}"
  ]
}