@generated
Call dependencies
{
  "Function{overrides.call_analyze_call_overrides}": [
    "Override{overrides.AnalyzeAllOverrides.return_source}"
  ],
  "Function{overrides.call_too_many_overrides}": [
    "Method{overrides.TooManyOverrides.return_source}"
  ],
  "Function{overrides.constructorTest}": [
    "Function{pysa._test_source}", "Method{builtins.object.__new__}",
    "Method{overrides.D.__init__}"
  ],
  "Function{overrides.testA}": [
    "Method{overrides.A.methodA}", "Method{overrides.Base.classMethod}",
    "Method{overrides.Base.methodB}"
  ],
  "Function{overrides.testBase}": [
    "Override{overrides.Base.classMethod}",
    "Override{overrides.Base.methodA}", "Override{overrides.Base.methodB}"
  ],
  "Function{overrides.testB}": [
    "Method{overrides.Base.methodA}", "Override{overrides.B.classMethod}",
    "Override{overrides.B.methodB}", "Override{overrides.C.methodA}"
  ],
  "Function{overrides.testC}": [
    "Method{overrides.B.methodB}", "Method{overrides.C.classMethod}",
    "Method{overrides.D.methodB}", "Override{overrides.C.methodA}"
  ],
  "Function{overrides.testD}": [
    "Method{overrides.C.classMethod}", "Method{overrides.D.methodB}",
    "Override{overrides.D.methodA}"
  ],
  "Function{overrides.testMakeA}": [
    "Method{builtins.object.__new__}", "Method{overrides.A.__init__}",
    "Method{overrides.Base.methodB}"
  ],
  "Function{overrides.testMakeBase}": [
    "Method{builtins.object.__new__}", "Method{overrides.Base.__init__}",
    "Override{overrides.Base.methodB}"
  ],
  "Function{overrides.testMakeB}": [
    "Method{builtins.object.__new__}", "Method{overrides.B.__init__}",
    "Override{overrides.B.methodB}"
  ],
  "Function{overrides.testMakeC}": [
    "Method{builtins.object.__new__}", "Method{overrides.B.methodB}",
    "Method{overrides.C.__init__}", "Method{overrides.D.methodB}"
  ],
  "Function{overrides.testMakeD}": [
    "Method{builtins.object.__new__}", "Method{overrides.D.__init__}",
    "Method{overrides.D.methodB}"
  ],
  "Function{overrides.testStaticA}": [
    "Method{overrides.Base.classMethod}", "Method{overrides.Base.methodB}"
  ],
  "Function{overrides.testStaticBase}": [
    "Method{overrides.Base.classMethod}", "Override{overrides.Base.methodB}"
  ],
  "Function{overrides.testStaticB}": [
    "Method{overrides.B.classMethod}", "Override{overrides.B.methodB}"
  ],
  "Function{overrides.testStaticC}": [
    "Method{overrides.B.methodB}", "Method{overrides.C.classMethod}",
    "Method{overrides.D.methodB}"
  ],
  "Function{overrides.testStaticD}": [
    "Method{overrides.C.classMethod}", "Method{overrides.D.methodB}"
  ],
  "Function{overrides.test_overrides_with_declaration}": [
    "Function{pysa._test_sink}",
    "Override{overrides.BaseWithDeclaration.return_source}"
  ],
  "Method{overrides.A.__init__}": [
    "Method{builtins.object.__new__}", "Method{builtins.super.__init__}",
    "Method{overrides.Base.__init__}"
  ],
  "Method{overrides.A.methodA}": [ "Function{pysa._test_sink}" ],
  "Method{overrides.AnalyzeAllOverridesChild3.return_source}": [
    "Function{pysa._test_source}"
  ],
  "Method{overrides.B.__init__}": [
    "Method{builtins.object.__new__}", "Method{builtins.super.__init__}",
    "Method{overrides.Base.__init__}"
  ],
  "Method{overrides.B.classMethod}": [ "Function{pysa._test_sink}" ],
  "Method{overrides.B.methodB}": [ "Function{pysa._test_source}" ],
  "Method{overrides.C.__init__}": [
    "Method{builtins.object.__new__}", "Method{builtins.super.__init__}",
    "Method{overrides.Base.__init__}"
  ],
  "Method{overrides.D.__init__}": [
    "Method{builtins.object.__new__}", "Method{builtins.super.__init__}",
    "Method{overrides.B.__init__}"
  ],
  "Method{overrides.D.methodA}": [ "Function{pysa._test_sink}" ],
  "Method{overrides.D.methodB}": [ "Function{pysa._test_source}" ],
  "Method{overrides.ExtendsSkipped.method}": [ "Function{pysa._test_sink}" ],
  "Method{overrides.TooManyOverridesChild3.return_source}": [
    "Function{pysa._test_source}"
  ]
}