@generated
Call dependencies
{
  "Function{parametric_models.f_and_g_to_test}": [
    "Function{parametric_models.f}", "Function{parametric_models.g}",
    "Function{parametric_models.sink}", "Method{_random.Random.random}",
    "Method{builtins.float.__gt__}"
  ],
  "Function{parametric_models.inferred_sink}": [
    "Function{parametric_models.sink_subkind_a}",
    "Function{parametric_models.sink_subkind_b}",
    "Method{_random.Random.random}", "Method{builtins.float.__gt__}"
  ],
  "Function{parametric_models.test_to_subkind_sink}": [
    "Function{parametric_models.inferred_sink}",
    "Function{pysa._test_source}"
  ]
}