@generated
Call dependencies
{
  "Function{parameter_path.issue_complex_tito}": [
    "Function{parameter_path.complex_tito}", "Function{pysa._test_sink}",
    "Function{pysa._test_source}"
  ],
  "Function{parameter_path.issue_only_with_sink_first}": [
    "Function{parameter_path.sink_on_first}", "Function{pysa._test_source}"
  ],
  "Function{parameter_path.issue_only_with_sink_key_a}": [
    "Function{parameter_path.sink_on_key_a}", "Function{pysa._test_source}"
  ],
  "Function{parameter_path.issue_only_with_sink_nested_first}": [
    "Function{parameter_path.sink_on_0_1}", "Function{pysa._test_source}"
  ],
  "Function{parameter_path.issue_only_with_sink_second}": [
    "Function{parameter_path.sink_on_second}", "Function{pysa._test_source}"
  ],
  "Function{parameter_path.issue_only_with_source_first}": [
    "Function{parameter_path.source_on_first}", "Function{pysa._test_sink}"
  ],
  "Function{parameter_path.issue_only_with_source_key_a}": [
    "Function{parameter_path.source_on_key_a}", "Function{pysa._test_sink}",
    "Method{builtins.dict.__getitem__}"
  ],
  "Function{parameter_path.issue_only_with_source_nested_first}": [
    "Function{parameter_path.source_on_0_1}", "Function{pysa._test_sink}"
  ],
  "Function{parameter_path.issue_only_with_source_second}": [
    "Function{parameter_path.source_on_second}", "Function{pysa._test_sink}"
  ],
  "Function{parameter_path.issue_tito_b_to_a}": [
    "Function{parameter_path.tito_from_b_to_a}", "Function{pysa._test_sink}",
    "Function{pysa._test_source}"
  ],
  "Function{parameter_path.issue_tito_first_to_second}": [
    "Function{parameter_path.tito_from_first_to_second}",
    "Function{pysa._test_sink}", "Function{pysa._test_source}"
  ],
  "Function{parameter_path.issue_tito_from_a_to_self_b}": [
    "Function{parameter_path.tito_from_a_to_self_b}",
    "Function{pysa._test_sink}", "Function{pysa._test_source}",
    "Method{builtins.dict.__getitem__}"
  ],
  "Function{parameter_path.issue_tito_from_first}": [
    "Function{parameter_path.tito_from_first}", "Function{pysa._test_sink}",
    "Function{pysa._test_source}"
  ],
  "Function{parameter_path.issue_tito_from_second}": [
    "Function{parameter_path.tito_from_second}", "Function{pysa._test_sink}",
    "Function{pysa._test_source}"
  ],
  "Function{parameter_path.issue_with_sink_member}": [
    "Function{parameter_path.sink_on_member_a}",
    "Function{pysa._test_source}", "Method{builtins.object.__init__}",
    "Method{builtins.object.__new__}"
  ],
  "Function{parameter_path.issue_with_source_member}": [
    "Function{parameter_path.source_on_member_a}",
    "Function{pysa._test_sink}"
  ]
}