@generated
Call dependencies
{
  "Function{partial.NestedDefineDecorator.__get__.wrapper}": [
    "Method{builtins.dict.__setitem__}",
    "Method{partial.NestedDefineDecorator.__call__}"
  ],
  "Function{partial.a_flows_to_sink}": [ "Function{pysa._test_sink}" ],
  "Function{partial.dunder_call_nested_define_constructor}": [
    "Method{builtins.object.__init__}", "Method{builtins.object.__new__}"
  ],
  "Function{partial.dunder_call_partial_constructor}": [
    "Method{builtins.object.__init__}", "Method{builtins.object.__new__}"
  ],
  "Function{partial.multiprocessing_bound_method_issue}": [
    "Function{pysa._test_source}", "Method{builtins.object.__new__}",
    "Method{multiprocessing.process.BaseProcess.__init__}",
    "Method{partial.MyClass.sink_on_foo}"
  ],
  "Function{partial.multiprocessing_bound_method_sink}": [
    "Method{builtins.object.__new__}",
    "Method{multiprocessing.process.BaseProcess.__init__}",
    "Method{partial.MyClass.sink_on_foo}"
  ],
  "Function{partial.multiprocessing_infer_sinks}": [
    "Function{partial.a_flows_to_sink}", "Method{builtins.object.__new__}",
    "Method{multiprocessing.process.BaseProcess.__init__}"
  ],
  "Function{partial.multiprocessing_nested_sink}": [
    "Function{partial.sink_on_foo}", "Method{builtins.dict.__getitem__}",
    "Method{builtins.object.__new__}",
    "Method{multiprocessing.process.BaseProcess.__init__}",
    "Method{partial.MyClass.__init__}"
  ],
  "Function{partial.multiprocessing_no_sink}": [
    "Function{partial.sink_on_foo}", "Method{builtins.dict.__getitem__}",
    "Method{builtins.object.__new__}",
    "Method{multiprocessing.process.BaseProcess.__init__}",
    "Method{partial.MyClass.__init__}"
  ],
  "Function{partial.multiprocessing_not_tainted}": [
    "Function{partial.a_flows_to_sink}", "Function{pysa._test_source}",
    "Method{builtins.object.__new__}",
    "Method{multiprocessing.process.BaseProcess.__init__}"
  ],
  "Function{partial.multiprocessing_shim_fail}": [
    "Function{partial.a_flows_to_sink}", "Function{pysa._test_source}",
    "Method{builtins.object.__new__}",
    "Method{multiprocessing.process.BaseProcess.__init__}"
  ],
  "Function{partial.multiprocessing_tainted_access_path}": [
    "Function{partial.sink_on_foo}", "Function{pysa._test_source}",
    "Method{builtins.object.__new__}",
    "Method{multiprocessing.process.BaseProcess.__init__}",
    "Method{partial.MyClass.__init__}"
  ],
  "Function{partial.multiprocessing_tainted}": [
    "Function{partial.a_flows_to_sink}", "Function{pysa._test_source}",
    "Method{builtins.object.__new__}",
    "Method{multiprocessing.process.BaseProcess.__init__}"
  ],
  "Function{partial.partial_application_bound_method_sink}": [
    "Method{builtins.object.__init__}", "Method{functools.partial.__new__}",
    "Method{partial.MyClass.sink_on_foo}"
  ],
  "Function{partial.partial_application_bound_method_tito}": [
    "Function{pysa._test_source}", "Method{builtins.object.__init__}",
    "Method{functools.partial.__new__}", "Method{partial.MyClass.set_foo}"
  ],
  "Function{partial.partial_application_with_benign}": [
    "Function{partial.a_flows_to_sink}", "Method{builtins.object.__init__}",
    "Method{functools.partial.__new__}"
  ],
  "Function{partial.partial_application_with_named_a}": [
    "Function{partial.a_flows_to_sink}", "Function{pysa._test_source}",
    "Method{builtins.object.__init__}", "Method{functools.partial.__new__}"
  ],
  "Function{partial.partial_application_with_named_b}": [
    "Function{partial.a_flows_to_sink}", "Function{pysa._test_source}",
    "Method{builtins.object.__init__}", "Method{functools.partial.__new__}"
  ],
  "Function{partial.partial_application_with_tainted}": [
    "Function{partial.a_flows_to_sink}", "Function{pysa._test_source}",
    "Method{builtins.object.__init__}", "Method{functools.partial.__new__}"
  ],
  "Function{partial.sink_on_foo}": [ "Function{pysa._test_sink}" ],
  "Method{partial.MyClass.sink_on_foo}": [ "Function{pysa._test_sink}" ],
  "Method{partial.NestedDefineConstructor.__init__@decorated}": [
    "Method{builtins.object.__new__}",
    "Method{partial.NestedDefineDecorator.__init__}[formal(func, position=1)=Method{partial.NestedDefineConstructor.__init__}]"
  ],
  "Method{partial.NestedDefineDecorator.__call__}": [
    "Method{builtins.dict.pop}"
  ],
  "Method{partial.PartialConstructor.__init__@decorated}": [
    "Method{builtins.object.__new__}",
    "Method{partial.PartialDecorator.__init__}[formal(func, position=1)=Method{partial.PartialConstructor.__init__}]"
  ],
  "Method{partial.PartialDecorator.__call__}": [
    "Method{builtins.dict.pop}"
  ],
  "Method{partial.PartialDecorator.__get__}": [
    "Method{builtins.object.__init__}", "Method{functools.partial.__new__}",
    "Method{partial.PartialDecorator.__call__}"
  ]
}