@generated
Call dependencies
{
  "Function{port.match_flows}": [
    "Function{port.sink_field}", "Function{port.source_field}"
  ],
  "Function{port.match_star_arg_directly}": [
    "Function{port.source_field}", "Function{port.star_arg_wrapper}"
  ],
  "Function{port.match_star_arg_with_star}": [
    "Function{port.source_field}", "Function{port.star_arg_wrapper}"
  ],
  "Function{port.match_star_star_arg_directly}": [
    "Function{port.source_field}", "Function{port.star_star_arg_wrapper}"
  ],
  "Function{port.match_star_star_arg_with_star}": [
    "Function{port.source_field}", "Function{port.star_star_arg_wrapper}"
  ],
  "Function{port.refer_to_method_as_field}": [
    "Function{pysa._test_sink}", "Method{port.Foo.some_source}"
  ],
  "Function{port.sink_field}": [ "Function{pysa._test_sink}" ],
  "Function{port.source_field}": [ "Function{pysa._test_source}" ],
  "Function{port.star_arg_wrapper}": [ "Function{port.star_arg}" ],
  "Function{port.star_arg}": [
    "Function{port.sink_field}", "Method{builtins.tuple.__getitem__}"
  ],
  "Function{port.star_star_arg_wrapper}": [ "Function{port.star_star_arg}" ],
  "Function{port.star_star_arg}": [
    "Function{port.sink_field}", "Method{builtins.dict.__getitem__}"
  ],
  "Method{port.Foo.some_source}": [ "Function{pysa._test_source}" ]
}