@generated
Call dependencies
{
  "Function{private_variables.test_access_from_other_class}": [
    "Function{pysa._test_source}", "Method{builtins.object.__new__}",
    "Method{private_variables.Other.private_into_sink}",
    "Method{private_variables.Simple.__init__}"
  ],
  "Function{private_variables.test_access_private_with_explicit_mangled_form}": [
    "Function{pysa._test_sink}"
  ],
  "Function{private_variables.test_bypass_private}": [
    "Function{pysa._test_sink}", "Function{pysa._test_source}",
    "Method{builtins.object.__new__}",
    "Method{private_variables.Simple.__init__}"
  ],
  "Function{private_variables.test_expand_subexpression}": [
    "Function{pysa._test_source}", "Method{builtins.object.__new__}",
    "Method{private_variables.Simple.__init__}",
    "Method{private_variables.Simple.expand_subexpression}"
  ],
  "Function{private_variables.test_getattr}": [
    "Function{pysa._test_sink}", "Function{pysa._test_source}",
    "Method{builtins.object.__new__}",
    "Method{private_variables.Simple.__init__}",
    "Method{private_variables.Simple.getattr_invalid}",
    "Method{private_variables.Simple.getattr_private}",
    "Method{private_variables.Simple.getattr_public}"
  ],
  "Function{private_variables.test_private_attribute_sink_models}": [
    "Function{pysa._test_source}", "Method{builtins.object.__new__}",
    "Method{private_variables.PrivateAttributeSinkModels.__init__}",
    "Method{private_variables.PrivateAttributeSinkModels.set_model_mangled}",
    "Method{private_variables.PrivateAttributeSinkModels.set_model_query}",
    "Method{private_variables.PrivateAttributeSinkModels.set_model_unmangled}"
  ],
  "Function{private_variables.test_private_attribute_source_models}": [
    "Function{pysa._test_sink}", "Method{builtins.object.__new__}",
    "Method{private_variables.PrivateAttributeSourceModels.__init__}",
    "Method{private_variables.PrivateAttributeSourceModels.get_model_mangled}",
    "Method{private_variables.PrivateAttributeSourceModels.get_model_query}",
    "Method{private_variables.PrivateAttributeSourceModels.get_model_unmangled}"
  ],
  "Function{private_variables.test_private_public_different}": [
    "Function{pysa._test_source}", "Method{builtins.object.__new__}",
    "Method{private_variables.Simple.__init__}",
    "Method{private_variables.Simple.private_into_sink}",
    "Method{private_variables.Simple.public_into_sink}"
  ],
  "Function{private_variables.test_simple}": [
    "Function{pysa._test_source}", "Method{builtins.object.__new__}",
    "Method{private_variables.Simple.__init__}",
    "Method{private_variables.Simple.private_into_sink}"
  ],
  "Method{private_variables.Other.private_into_sink}": [
    "Function{pysa._test_sink}"
  ],
  "Method{private_variables.PrivateAttributeSinkModels.__init__}": [
    "ClassInstanceAttribute{private_variables.PrivateAttributeSinkModels._PrivateAttributeSinkModels__model_mangled}",
    "ClassInstanceAttribute{private_variables.PrivateAttributeSinkModels._PrivateAttributeSinkModels__model_query}",
    "ClassInstanceAttribute{private_variables.PrivateAttributeSinkModels._PrivateAttributeSinkModels__model_unmangled}"
  ],
  "Method{private_variables.PrivateAttributeSinkModels.set_model_mangled}": [
    "ClassInstanceAttribute{private_variables.PrivateAttributeSinkModels._PrivateAttributeSinkModels__model_mangled}"
  ],
  "Method{private_variables.PrivateAttributeSinkModels.set_model_query}": [
    "ClassInstanceAttribute{private_variables.PrivateAttributeSinkModels._PrivateAttributeSinkModels__model_query}"
  ],
  "Method{private_variables.PrivateAttributeSinkModels.set_model_unmangled}": [
    "ClassInstanceAttribute{private_variables.PrivateAttributeSinkModels._PrivateAttributeSinkModels__model_unmangled}"
  ],
  "Method{private_variables.PrivateAttributeSourceModels.__init__}": [
    "ClassInstanceAttribute{private_variables.PrivateAttributeSourceModels._PrivateAttributeSourceModels__model_mangled}",
    "ClassInstanceAttribute{private_variables.PrivateAttributeSourceModels._PrivateAttributeSourceModels__model_query}",
    "ClassInstanceAttribute{private_variables.PrivateAttributeSourceModels._PrivateAttributeSourceModels__model_unmangled}"
  ],
  "Method{private_variables.PrivateAttributeSourceModels.get_model_mangled}": [
    "ClassInstanceAttribute{private_variables.PrivateAttributeSourceModels._PrivateAttributeSourceModels__model_mangled}"
  ],
  "Method{private_variables.PrivateAttributeSourceModels.get_model_query}": [
    "ClassInstanceAttribute{private_variables.PrivateAttributeSourceModels._PrivateAttributeSourceModels__model_query}"
  ],
  "Method{private_variables.PrivateAttributeSourceModels.get_model_unmangled}": [
    "ClassInstanceAttribute{private_variables.PrivateAttributeSourceModels._PrivateAttributeSourceModels__model_unmangled}"
  ],
  "Method{private_variables.Simple.expand_subexpression}": [
    "Function{pysa._test_sink}", "Method{builtins.list.__getitem__}"
  ],
  "Method{private_variables.Simple.getattr_invalid}": [
    "Function{builtins.getattr}"
  ],
  "Method{private_variables.Simple.getattr_private}": [
    "Function{builtins.getattr}"
  ],
  "Method{private_variables.Simple.getattr_public}": [
    "Function{builtins.getattr}"
  ],
  "Method{private_variables.Simple.private_into_sink}": [
    "Function{pysa._test_sink}"
  ],
  "Method{private_variables.Simple.public_into_sink}": [
    "Function{pysa._test_sink}"
  ]
}