@generated
Call dependencies
{
  "Function{properties.CollidePropertySetterName.collided_property.setter}": [
    "Method{properties.CollidePropertySetterName.foo}"
  ],
  "Function{properties.PropertyDefinedByAssignment.$class_toplevel}": [
    "Method{builtins.object.__new__}", "Method{builtins.property.__init__}",
    "Method{properties.PropertyDefinedByAssignment._get_my_property}"
  ],
  "Function{properties.function_with_nested_properties.my_property@setter}": [
    "Function{properties.bar}", "Function{pysa._test_sink}",
    "Function{pysa._test_source}"
  ],
  "Function{properties.function_with_nested_properties.my_property}": [
    "Function{properties.foo}"
  ],
  "Function{properties.property_setter_in_constructor}": [
    "Function{pysa._test_sink}", "Function{pysa._test_source}",
    "Method{builtins.object.__new__}",
    "Method{properties.PropertySetterInConstructor.__init__}",
    "Method{properties.PropertySetterInConstructor.x}"
  ],
  "Function{properties.sets_tainted_value}": [
    "Function{pysa._test_source}",
    "Override{properties.TaintedGetterAndSetter.my_property@setter}"
  ],
  "Function{properties.setters_are_simulated}": [
    "Function{pysa._test_sink}", "Function{pysa._test_source}",
    "Method{builtins.object.__new__}",
    "Method{properties.SetterMutatesValue.__init__}",
    "Method{properties.SetterMutatesValue.p@setter}",
    "Method{properties.SetterMutatesValue.p}"
  ],
  "Function{properties.string_source}": [ "Function{pysa._test_source}" ],
  "Function{properties.test_getattr_on_property}": [
    "Function{builtins.getattr}", "Function{pysa._test_sink}",
    "Method{properties.TaintedGetterAndSetter.my_property}"
  ],
  "Function{properties.test_issue_in_class_property}": [
    "Function{pysa._test_sink}",
    "Method{properties.ClassProperty.my_class_property}"
  ],
  "Function{properties.test_object_class}": [
    "Function{properties.string_source}", "Function{pysa._test_sink}"
  ],
  "Function{properties.test_property_augmented_assign}": [
    "Method{builtins.int.__ror__}",
    "Method{properties.PropertySetterTitoModel.my_property@setter}"
  ],
  "Function{properties.test_property_callable}": [
    "Function{pysa._test_source}", "Method{builtins.object.__new__}",
    "Method{properties.PropertyCallable.__init__}",
    "Method{properties.PropertyCallable.attribute}",
    "Method{properties.PropertyCallableReturn.__call__}"
  ],
  "Function{properties.test_type_variable_properties_are_resolved}": [
    "Method{properties.Class.my_property}"
  ],
  "Function{properties.test_union_property_attribute_sink}": [
    "Function{pysa._test_sink}", "Method{_random.Random.random}",
    "Method{builtins.float.__gt__}", "Method{builtins.object.__init__}",
    "Method{builtins.object.__new__}",
    "Method{properties.RegularAttribute.__init__}",
    "Method{properties.TaintedGetterAndSetter.my_property}"
  ],
  "Function{properties.test_union_property_attribute_source}": [
    "Function{pysa._test_source}", "Method{_random.Random.random}",
    "Method{builtins.float.__gt__}", "Method{builtins.object.__init__}",
    "Method{builtins.object.__new__}",
    "Method{properties.RegularAttribute.__init__}",
    "Method{properties.TaintedGetterAndSetter.my_property}"
  ],
  "Method{properties.Class.uses_other}": [
    "Override{properties.Class.my_property}"
  ],
  "Method{properties.Class.uses_property_but_no_tito_taint}": [
    "Function{pysa._test_source}", "Override{properties.Class.my_property}"
  ],
  "Method{properties.Class.uses_property}": [
    "Function{pysa._test_source}", "Override{properties.Class.my_property}"
  ],
  "Method{properties.CollidePropertySetterName.collided_property@setter}": [
    "Method{properties.CollidePropertySetterName.bar}"
  ],
  "Method{properties.CollidePropertySetterName.collided_property}": [
    "Function{properties.CollidePropertySetterName.collided_property.setter}"
  ],
  "Method{properties.Derived.uses_property_but_no_tito_taint}": [
    "Function{pysa._test_source}", "Method{properties.Class.my_property}"
  ],
  "Method{properties.Derived.uses_property}": [
    "Function{pysa._test_source}", "Method{properties.Class.my_property}"
  ],
  "Method{properties.DerivedTaintedSetter.my_property@setter}": [
    "Function{pysa._test_sink}"
  ],
  "Method{properties.OtherDerived.my_property}": [
    "Function{pysa._test_source}"
  ],
  "Method{properties.OtherDerived.uses_property_but_no_tito_taint}": [
    "Function{pysa._test_source}",
    "Method{properties.OtherDerived.my_property}"
  ],
  "Method{properties.PropertyCallable.attribute}": [
    "Function{pysa._test_sink}", "Function{pysa._test_source}",
    "Method{builtins.object.__new__}",
    "Method{properties.PropertyCallableReturn.__init__}"
  ],
  "Method{properties.PropertyCallableReturn.__call__}": [
    "Function{pysa._test_sink}"
  ],
  "Method{properties.PropertyDefinedByAssignment.uses_property}": [
    "Function{pysa._test_source}",
    "Method{properties.PropertyDefinedByAssignment._get_my_property}"
  ],
  "Method{properties.PropertySetterInConstructor.__init__}": [
    "Method{properties.PropertySetterInConstructor.x@setter}"
  ],
  "Method{properties.PropertySetterTitoModel.test_obscure_property}": [
    "Function{pysa._test_sink}", "Function{pysa._test_source}",
    "Method{properties.PropertySetterTitoModel.obscure_property@setter}"
  ],
  "Method{properties.PropertySetterTitoModel.test_tito_property}": [
    "Function{pysa._test_sink}", "Function{pysa._test_source}",
    "Method{properties.PropertySetterTitoModel.my_property@setter}",
    "Method{properties.PropertySetterTitoModel.my_property}"
  ],
  "Method{properties.TaintedGetterAndSetter.my_property}": [
    "Function{pysa._test_sink}"
  ],
  "Method{properties.TaintedGetterAndSetter.uses_property}": [
    "Method{properties.TaintedGetterAndSetter.my_property}"
  ],
  "Method{properties.TaintedGetterAndSetter.writes_to_property}": [
    "Function{pysa._test_source}",
    "Override{properties.TaintedGetterAndSetter.my_property@setter}"
  ],
  "Method{properties.TestTypeInferenceInSetter.my_property@setter}": [
    "Function{builtins.isinstance}", "Method{properties.A.foo}",
    "Override{properties.Base.foo}"
  ]
}