@generated
Call dependencies
{
  "Function{raise.backward}": [ "Function{pysa._test_sink}" ],
  "Function{raise.conditional_unreachability}": [
    "Function{pysa._test_sink}", "Function{pysa._test_source}",
    "Method{builtins.BaseException.__init__}",
    "Method{builtins.BaseException.__new__}"
  ],
  "Function{raise.forward}": [
    "Function{pysa._test_sink}", "Function{pysa._test_source}"
  ],
  "Function{raise.no_sink}": [
    "Function{pysa._test_sink}", "Method{builtins.BaseException.__init__}",
    "Method{builtins.BaseException.__new__}"
  ],
  "Function{raise.no_source}": [
    "Function{pysa._test_source}", "Method{builtins.BaseException.__init__}",
    "Method{builtins.BaseException.__new__}"
  ],
  "Function{raise.unreachable_code_do_to_always_exception}": [
    "Function{pysa._test_sink}", "Function{pysa._test_source}",
    "Function{raise.no_source}"
  ],
  "Function{raise.unreachable_through_function_call_sink}": [
    "Function{pysa._test_source}", "Function{raise.no_sink}"
  ],
  "Function{raise.unreachable_through_function_call_source}": [
    "Function{pysa._test_sink}", "Function{raise.no_source}"
  ],
  "Function{raise.unreachable}": [
    "Function{pysa._test_sink}", "Function{pysa._test_source}",
    "Method{builtins.BaseException.__init__}",
    "Method{builtins.BaseException.__new__}"
  ]
}