@generated
Call dependencies
{
  "Function{readonly.readonly_foo_not_tainted}": [
    "Function{pysa._test_sink}"
  ],
  "Function{readonly.readonly_foo_tainted}": [
    "ClassInstanceAttribute{readonly.Foo.tainted}",
    "Function{pysa._test_sink}"
  ],
  "Function{readonly.readonly_tito}": [
    "Function{pysa._test_sink}", "Function{pysa._test_source}",
    "Method{builtins.object.__new__}", "Method{readonly.A.__init__}",
    "Method{readonly.A.readonly_tito}"
  ],
  "Function{readonly.regular_foo_not_tainted}": [
    "Function{pysa._test_sink}"
  ],
  "Function{readonly.regular_foo_tainted}": [
    "ClassInstanceAttribute{readonly.Foo.tainted}",
    "Function{pysa._test_sink}"
  ],
  "Method{readonly.A.__init__}": [
    "ClassInstanceAttribute{readonly.A.B}",
    "ClassInstanceAttribute{readonly.A.mapping}"
  ],
  "Method{readonly.A.self_readonly_map}": [
    "ClassInstanceAttribute{readonly.A.mapping}",
    "Function{pysa._test_sink}", "Method{typing.Mapping.get}"
  ],
  "Method{readonly.A.self_readonly_str}": [
    "ClassInstanceAttribute{readonly.A.B}", "Function{pysa._test_sink}"
  ],
  "Method{readonly.A.self_untyped_map}": [
    "ClassInstanceAttribute{readonly.A.mapping}",
    "Function{pysa._test_sink}", "Method{typing.Mapping.get}"
  ],
  "Method{readonly.A.self_untyped_str}": [
    "ClassInstanceAttribute{readonly.A.B}", "Function{pysa._test_sink}"
  ]
}