@generated
Call dependencies
{
  "Function{return_sinks.not_propagate_returned_sink_to_arg}": [
    "Function{return_sinks.sink_on_return_and_tito}"
  ],
  "Function{return_sinks.propagate_returned_sink_to_arg}": [
    "Function{return_sinks.sink_on_return_and_tito}"
  ],
  "Function{return_sinks.sink_on_return_not_propagated_to_arg}": [
    "Function{return_sinks.sink_on_return}"
  ],
  "Function{return_sinks.sink_on_return_not_propagated_to_return}": [
    "Function{return_sinks.sink_on_return}"
  ]
}