@generated
Call dependencies
{
  "Function{sanitize_tito_shaping.issue_multiple_titos_different_input_output_paths}": [
    "Function{sanitize_tito_shaping.a_sink}",
    "Function{sanitize_tito_shaping.a_source}",
    "Function{sanitize_tito_shaping.b_sink}",
    "Function{sanitize_tito_shaping.b_source}",
    "Function{sanitize_tito_shaping.multiple_titos_different_input_output_paths}"
  ],
  "Function{sanitize_tito_shaping.issue_multiple_titos_different_input_paths}": [
    "Function{sanitize_tito_shaping.a_sink}",
    "Function{sanitize_tito_shaping.a_source}",
    "Function{sanitize_tito_shaping.b_sink}",
    "Function{sanitize_tito_shaping.b_source}",
    "Function{sanitize_tito_shaping.multiple_titos_different_input_paths}"
  ],
  "Function{sanitize_tito_shaping.issue_multiple_titos_different_output_paths}": [
    "Function{sanitize_tito_shaping.a_sink}",
    "Function{sanitize_tito_shaping.a_source}",
    "Function{sanitize_tito_shaping.b_sink}",
    "Function{sanitize_tito_shaping.b_source}",
    "Function{sanitize_tito_shaping.multiple_titos_different_output_paths}"
  ],
  "Function{sanitize_tito_shaping.issue_multiple_titos_same_path_with_transform}": [
    "Function{sanitize_tito_shaping.a_sink}",
    "Function{sanitize_tito_shaping.a_source}",
    "Function{sanitize_tito_shaping.b_sink}",
    "Function{sanitize_tito_shaping.b_source}",
    "Function{sanitize_tito_shaping.multiple_titos_same_path_with_transform}"
  ],
  "Function{sanitize_tito_shaping.issue_multiple_titos_same_path}": [
    "Function{sanitize_tito_shaping.a_sink}",
    "Function{sanitize_tito_shaping.a_source}",
    "Function{sanitize_tito_shaping.b_sink}",
    "Function{sanitize_tito_shaping.b_source}",
    "Function{sanitize_tito_shaping.multiple_titos_same_path}"
  ],
  "Function{sanitize_tito_shaping.loop_multiple_titos_different_input_output_paths}": [
    "Function{sanitize_tito_shaping.multiple_titos_different_input_output_paths}",
    "Method{builtins.object.__init__}", "Method{builtins.range.__iter__}",
    "Method{builtins.range.__new__}", "Method{typing.Iterator.__next__}"
  ],
  "Function{sanitize_tito_shaping.loop_multiple_titos_different_input_paths}": [
    "Function{sanitize_tito_shaping.multiple_titos_different_input_paths}",
    "Method{builtins.object.__init__}", "Method{builtins.range.__iter__}",
    "Method{builtins.range.__new__}", "Method{typing.Iterator.__next__}"
  ],
  "Function{sanitize_tito_shaping.loop_multiple_titos_different_output_paths}": [
    "Function{sanitize_tito_shaping.multiple_titos_different_output_paths}",
    "Method{builtins.object.__init__}", "Method{builtins.range.__iter__}",
    "Method{builtins.range.__new__}", "Method{typing.Iterator.__next__}"
  ],
  "Function{sanitize_tito_shaping.loop_multiple_titos_same_path}": [
    "Function{sanitize_tito_shaping.multiple_titos_same_path}",
    "Method{builtins.object.__init__}", "Method{builtins.range.__iter__}",
    "Method{builtins.range.__new__}", "Method{typing.Iterator.__next__}"
  ],
  "Function{sanitize_tito_shaping.multiple_titos_different_input_output_paths}": [
    "Function{sanitize_tito_shaping.add_feature}",
    "Function{sanitize_tito_shaping.sanitize_sink_a_depth_two}",
    "Function{sanitize_tito_shaping.sanitize_sink_b}",
    "Function{sanitize_tito_shaping.sanitize_source_a}",
    "Function{sanitize_tito_shaping.sanitize_source_b}",
    "Method{_random.Random.random}", "Method{builtins.float.__gt__}"
  ],
  "Function{sanitize_tito_shaping.multiple_titos_different_input_paths}": [
    "Function{sanitize_tito_shaping.add_feature}",
    "Function{sanitize_tito_shaping.sanitize_sink_a_depth_two}",
    "Function{sanitize_tito_shaping.sanitize_sink_b}",
    "Function{sanitize_tito_shaping.sanitize_source_a}",
    "Function{sanitize_tito_shaping.sanitize_source_b}",
    "Method{_random.Random.random}", "Method{builtins.float.__gt__}"
  ],
  "Function{sanitize_tito_shaping.multiple_titos_different_output_paths}": [
    "Function{sanitize_tito_shaping.add_feature}",
    "Function{sanitize_tito_shaping.sanitize_sink_a_depth_two}",
    "Function{sanitize_tito_shaping.sanitize_sink_b}",
    "Function{sanitize_tito_shaping.sanitize_source_a}",
    "Function{sanitize_tito_shaping.sanitize_source_b}",
    "Method{_random.Random.random}", "Method{builtins.float.__gt__}"
  ],
  "Function{sanitize_tito_shaping.multiple_titos_same_path_different_collapse_depth}": [
    "Function{sanitize_tito_shaping.sanitize_sink_a_depth_two}",
    "Function{sanitize_tito_shaping.sanitize_source_a}",
    "Function{sanitize_tito_shaping.tito_collapse_one}",
    "Function{sanitize_tito_shaping.tito_collapse_zero}",
    "Method{_random.Random.random}", "Method{builtins.float.__gt__}"
  ],
  "Function{sanitize_tito_shaping.multiple_titos_same_path_with_transform}": [
    "Function{sanitize_tito_shaping.sanitize_sink_a_depth_two}",
    "Function{sanitize_tito_shaping.sanitize_source_a}",
    "Function{sanitize_tito_shaping.transform_x}",
    "Function{sanitize_tito_shaping.transform_y}",
    "Method{_random.Random.random}", "Method{builtins.float.__gt__}"
  ],
  "Function{sanitize_tito_shaping.multiple_titos_same_path}": [
    "Function{sanitize_tito_shaping.add_feature}",
    "Function{sanitize_tito_shaping.sanitize_sink_a_depth_two}",
    "Function{sanitize_tito_shaping.sanitize_sink_b}",
    "Function{sanitize_tito_shaping.sanitize_source_a}",
    "Function{sanitize_tito_shaping.sanitize_source_b}",
    "Method{_random.Random.random}", "Method{builtins.float.__gt__}"
  ],
  "Function{sanitize_tito_shaping.sanitize_sink_a_depth_two}": [
    "Function{sanitize_tito_shaping.sanitize_sink_a}"
  ],
  "Function{sanitize_tito_shaping.sanitize_source_a_depth_two}": [
    "Function{sanitize_tito_shaping.sanitize_source_a}"
  ],
  "Function{sanitize_tito_shaping.tito_collapse_one}": [
    "Function{sanitize_tito_shaping.tito_collapse_one_append_a_b_c}",
    "Method{builtins.dict.__getitem__}"
  ]
}