@generated
Call dependencies
{
  "Function{sanitize_obscure.no_propagation_of_a_sink_via_parameter_tito}": [
    "Function{sanitize_obscure.a_sink}",
    "Function{sanitize_obscure.sanitize_parameter_sink_a_tito}"
  ],
  "Function{sanitize_obscure.no_propagation_of_a_sink_via_parameter}": [
    "Function{sanitize_obscure.a_sink}",
    "Function{sanitize_obscure.sanitize_parameter_sink_a}"
  ],
  "Function{sanitize_obscure.no_propagation_of_a_sink_via_return_tito}": [
    "Function{sanitize_obscure.a_sink}",
    "Function{sanitize_obscure.sanitize_return_sink_a_tito}"
  ],
  "Function{sanitize_obscure.no_propagation_of_a_sink_via_return}": [
    "Function{sanitize_obscure.a_sink}",
    "Function{sanitize_obscure.sanitize_return_sink_a}"
  ],
  "Function{sanitize_obscure.no_propagation_of_a_sink}": [
    "Function{sanitize_obscure.a_sink}",
    "Function{sanitize_obscure.sanitize_a_sink_tito}"
  ],
  "Function{sanitize_obscure.no_propagation_of_a_source_via_parameter_tito}": [
    "Function{sanitize_obscure.a_source}",
    "Function{sanitize_obscure.sanitize_parameter_source_a_tito}"
  ],
  "Function{sanitize_obscure.no_propagation_of_a_source_via_parameter}": [
    "Function{sanitize_obscure.a_source}",
    "Function{sanitize_obscure.sanitize_parameter_source_a}"
  ],
  "Function{sanitize_obscure.no_propagation_of_a_source_via_return_tito}": [
    "Function{sanitize_obscure.a_source}",
    "Function{sanitize_obscure.sanitize_return_source_a_tito}"
  ],
  "Function{sanitize_obscure.no_propagation_of_a_source_via_return}": [
    "Function{sanitize_obscure.a_source}",
    "Function{sanitize_obscure.sanitize_return_source_a}"
  ],
  "Function{sanitize_obscure.no_propagation_of_a_source}": [
    "Function{sanitize_obscure.a_source}",
    "Function{sanitize_obscure.sanitize_a_source_tito}"
  ],
  "Function{sanitize_obscure.no_propagation_with_sanitize_a_tito}": [
    "Function{sanitize_obscure.a_source}",
    "Function{sanitize_obscure.sanitize_a_tito}"
  ],
  "Function{sanitize_obscure.propagation_of_a_sink_via_other_parameter_tito}": [
    "Function{sanitize_obscure.a_sink}",
    "Function{sanitize_obscure.sanitize_parameter_sink_a_tito}"
  ],
  "Function{sanitize_obscure.propagation_of_a_source_via_other_parameter_tito}": [
    "Function{sanitize_obscure.a_source}",
    "Function{sanitize_obscure.sanitize_parameter_source_a_tito}"
  ],
  "Function{sanitize_obscure.propagation_of_b_sink_via_parameter_tito}": [
    "Function{sanitize_obscure.b_sink}",
    "Function{sanitize_obscure.sanitize_parameter_sink_a_tito}"
  ],
  "Function{sanitize_obscure.propagation_of_b_sink_via_parameter}": [
    "Function{sanitize_obscure.b_sink}",
    "Function{sanitize_obscure.sanitize_parameter_sink_a}"
  ],
  "Function{sanitize_obscure.propagation_of_b_sink_via_return_tito}": [
    "Function{sanitize_obscure.b_sink}",
    "Function{sanitize_obscure.sanitize_return_sink_a_tito}"
  ],
  "Function{sanitize_obscure.propagation_of_b_sink_via_return}": [
    "Function{sanitize_obscure.b_sink}",
    "Function{sanitize_obscure.sanitize_return_sink_a}"
  ],
  "Function{sanitize_obscure.propagation_of_b_sink}": [
    "Function{sanitize_obscure.b_sink}",
    "Function{sanitize_obscure.sanitize_a_sink_tito}"
  ],
  "Function{sanitize_obscure.propagation_of_b_source_via_parameter_tito}": [
    "Function{sanitize_obscure.b_source}",
    "Function{sanitize_obscure.sanitize_parameter_source_a_tito}"
  ],
  "Function{sanitize_obscure.propagation_of_b_source_via_parameter}": [
    "Function{sanitize_obscure.b_source}",
    "Function{sanitize_obscure.sanitize_parameter_source_a}"
  ],
  "Function{sanitize_obscure.propagation_of_b_source_via_return_tito}": [
    "Function{sanitize_obscure.b_source}",
    "Function{sanitize_obscure.sanitize_return_source_a_tito}"
  ],
  "Function{sanitize_obscure.propagation_of_b_source_via_return}": [
    "Function{sanitize_obscure.b_source}",
    "Function{sanitize_obscure.sanitize_return_source_a}"
  ],
  "Function{sanitize_obscure.propagation_of_b_source}": [
    "Function{sanitize_obscure.b_source}",
    "Function{sanitize_obscure.sanitize_a_source_tito}"
  ],
  "Function{sanitize_obscure.propagation_of_b_with_sanitize_a_tito}": [
    "Function{sanitize_obscure.b_source}",
    "Function{sanitize_obscure.sanitize_a_tito}"
  ],
  "Function{sanitize_obscure.sanitize_obscure_single_argument_tito}": [
    "Function{sanitize_obscure.sanitize_obscure_single_argument}"
  ],
  "Function{sanitize_obscure.test1}": [
    "Function{pysa._test_sink}", "Function{sanitize_obscure.sanitize_all}"
  ],
  "Function{sanitize_obscure.test2}": [
    "Function{pysa._test_sink}", "Function{pysa._test_source}",
    "Function{sanitize_obscure.sanitize_all}"
  ],
  "Function{sanitize_obscure.test3}": [
    "Function{pysa._test_sink}", "Function{sanitize_obscure.sanitize_tito}"
  ],
  "Function{sanitize_obscure.test4}": [
    "Function{pysa._test_sink}", "Function{pysa._test_source}",
    "Function{sanitize_obscure.sanitize_tito}"
  ]
}