@generated
Call dependencies
{
  "Function{sanitize_discard_flows.test_sink_a_sanitize_a_discarded}": [
    "Function{sanitize_discard_flows.a_sink}",
    "Function{sanitize_discard_flows.sanitize_a_source_tito}"
  ],
  "Function{sanitize_discard_flows.test_source_a_sanitize_a_b_discarded}": [
    "Function{sanitize_discard_flows.a_source}",
    "Function{sanitize_discard_flows.sanitize_a_sink_tito}",
    "Function{sanitize_discard_flows.sanitize_b_sink_tito}"
  ],
  "Function{sanitize_discard_flows.test_source_a_sanitize_a_kept}": [
    "Function{sanitize_discard_flows.a_source}",
    "Function{sanitize_discard_flows.sanitize_a_sink_tito}"
  ]
}