@generated
Call dependencies
{
  "Function{sanitize_parametric.partial_issue_sanitize}": [
    "Function{sanitize_parametric.partial_issue_sinks}",
    "Function{sanitize_parametric.partial_issue_sources}"
  ],
  "Function{sanitize_parametric.partial_issue_sinks}": [
    "Function{sanitize_parametric.a_sink_x}",
    "Function{sanitize_parametric.a_sink_y}",
    "Function{sanitize_parametric.sanitize_a_source_tito}",
    "Method{_random.Random.random}", "Method{builtins.float.__gt__}"
  ],
  "Function{sanitize_parametric.partial_issue_sources}": [
    "Function{sanitize_parametric.a_source_x}",
    "Function{sanitize_parametric.a_source_y}",
    "Function{sanitize_parametric.sanitize_a_sink_tito}",
    "Method{_random.Random.random}", "Method{builtins.float.__gt__}"
  ]
}