@generated
Call dependencies
{
  "Function{select.first_index_numeric}": [ "Function{pysa._test_source}" ],
  "Function{select.first_index_unknown}": [ "Function{pysa._test_source}" ],
  "Function{select.first_index}": [ "Function{pysa._test_source}" ],
  "Function{select.return_is_RCE}": [
    "ClassInstanceAttribute{django.http.Request.GET}",
    "Method{builtins.dict.get}"
  ],
  "Function{select.view_entry_field}": [ "Function{builtins.eval}" ],
  "Function{select.view_entry_get}": [
    "ClassInstanceAttribute{django.http.Request.GET}",
    "Function{builtins.eval}", "Method{builtins.dict.get}"
  ],
  "Function{select.view_entry_index}": [ "Function{builtins.eval}" ]
}