@generated
Call dependencies
{
  "Function{self.foo_class_attributes}": [
    "ClassTypeAttribute{self.Foo.tainted_class}", "Function{pysa._test_sink}"
  ],
  "Function{self.selftype_access_other}": [
    "ClassTypeAttribute{self.Foo.tainted_class}",
    "Function{pysa._test_sink}", "Method{builtins.object.__new__}",
    "Method{self.Foo.__init__}", "Method{self.Foo.selftype_access_other}"
  ],
  "Function{self.selftype_access_self}": [
    "ClassTypeAttribute{self.Foo.tainted_class}",
    "Function{pysa._test_sink}", "Method{builtins.object.__new__}",
    "Method{self.Foo.__init__}", "Method{self.Foo.selftype_access_self}"
  ],
  "Function{self.selftype_access_untyped_self}": [
    "ClassTypeAttribute{self.Foo.tainted_class}",
    "Function{pysa._test_sink}", "Method{builtins.object.__new__}",
    "Method{self.Foo.__init__}",
    "Method{self.Foo.selftype_access_untyped_self}"
  ],
  "Function{self.typevar_access_other}": [
    "ClassTypeAttribute{self.Foo.tainted_class}",
    "Function{pysa._test_sink}", "Method{builtins.object.__new__}",
    "Method{self.Foo.__init__}", "Method{self.Foo.typevar_access_other}"
  ],
  "Function{self.typevar_access_self}": [
    "ClassTypeAttribute{self.Foo.tainted_class}",
    "Function{pysa._test_sink}", "Method{builtins.object.__new__}",
    "Method{self.Foo.__init__}", "Method{self.Foo.typevar_access_self}"
  ],
  "Function{self.untyped_access_self}": [
    "ClassTypeAttribute{self.Foo.tainted_class}",
    "Function{pysa._test_sink}", "Method{builtins.object.__new__}",
    "Method{self.Foo.__init__}"
  ],
  "Method{self.Foo.__init__}": [ "Function{pysa._test_source}" ],
  "Method{self.Foo.selftype_self_class_direct}": [
    "ClassTypeAttribute{self.Foo.tainted_class}", "Function{pysa._test_sink}"
  ],
  "Method{self.Foo.selftype_self_class}": [ "Function{pysa._test_sink}" ],
  "Method{self.Foo.selftype_self_extra_instance}": [
    "Function{pysa._test_sink}"
  ],
  "Method{self.Foo.selftype_self_instance}": [ "Function{pysa._test_sink}" ],
  "Method{self.Foo.selftype_self_not_tainted}": [
    "Function{pysa._test_sink}"
  ],
  "Method{self.Foo.typevar_self_class_direct}": [
    "Function{pysa._test_sink}"
  ],
  "Method{self.Foo.typevar_self_class}": [ "Function{pysa._test_sink}" ],
  "Method{self.Foo.typevar_self_extra_instance}": [
    "Function{pysa._test_sink}"
  ],
  "Method{self.Foo.typevar_self_instance}": [ "Function{pysa._test_sink}" ],
  "Method{self.Foo.typevar_self_not_tainted}": [
    "Function{pysa._test_sink}"
  ],
  "Method{self.Foo.untyped_self_class_direct}": [
    "ClassTypeAttribute{self.Foo.tainted_class}", "Function{pysa._test_sink}"
  ],
  "Method{self.Foo.untyped_self_class}": [ "Function{pysa._test_sink}" ],
  "Method{self.Foo.untyped_self_extra_instance}": [
    "Function{pysa._test_sink}"
  ],
  "Method{self.Foo.untyped_self_instance}": [ "Function{pysa._test_sink}" ],
  "Method{self.Foo.untyped_self_not_tainted}": [
    "Function{pysa._test_sink}"
  ]
}