@generated
Call dependencies
{
  "Function{side_effects.dict_to_sink_via_side_effect}": [
    "Function{pysa._test_sink}", "Function{side_effects.change_arg0}",
    "Method{builtins.dict.__getitem__}"
  ],
  "Function{side_effects.test_from_0_to_1}": [
    "Function{pysa._test_source}", "Function{side_effects.change_arg1}"
  ],
  "Function{side_effects.test_from_1_to_0_nested_distinct}": [
    "Function{pysa._test_source}", "Function{side_effects.change_arg0}",
    "Method{builtins.object.__new__}", "Method{side_effects.Object.__init__}"
  ],
  "Function{side_effects.test_from_1_to_0_nested}": [
    "Function{pysa._test_source}", "Function{side_effects.change_arg0}",
    "Method{builtins.object.__new__}", "Method{side_effects.Object.__init__}"
  ],
  "Function{side_effects.test_from_1_to_0}": [
    "Function{pysa._test_source}", "Function{side_effects.change_arg0}"
  ],
  "Function{side_effects.test_list_append}": [
    "Function{pysa._test_source}", "Method{builtins.object.__init__}",
    "Method{builtins.object.__new__}", "Method{side_effects.MyList.append}"
  ],
  "Function{side_effects.to_sink_via_side_effect}": [
    "Function{pysa._test_sink}", "Function{side_effects.change_arg0}"
  ],
  "Function{side_effects.wrapper_from_0_to_1}": [
    "Function{side_effects.change_arg1}"
  ],
  "Function{side_effects.wrapper_from_1_to_0}": [
    "Function{side_effects.change_arg0}"
  ]
}