@generated
Call dependencies
{
  "Function{source_sink_flow.bad}": [ "Function{source_sink_flow.qux}" ],
  "Function{source_sink_flow.bar}": [ "Function{pysa._test_source}" ],
  "Function{source_sink_flow.match_flows}": [
    "Function{source_sink_flow.bad}",
    "Function{source_sink_flow.some_source}"
  ],
  "Function{source_sink_flow.qux}": [ "Function{pysa._test_sink}" ],
  "Function{source_sink_flow.some_source}": [
    "Function{source_sink_flow.bar}"
  ]
}