@generated
Call dependencies
{
  "Function{str_decorated_repr.cachedmethod.g}": [
    "Function{builtins.getattr}", "Function{builtins.hasattr}",
    "Function{builtins.setattr}"
  ],
  "Function{str_decorated_repr.cachedmethod.g}[captured_variable(f, str_decorated_repr.cachedmethod)=Method{str_decorated_repr.MyClass.__repr__}]": [
    "Function{builtins.getattr}", "Function{builtins.hasattr}",
    "Function{builtins.setattr}",
    "Method{str_decorated_repr.MyClass.__repr__}"
  ],
  "Function{str_decorated_repr.cachedmethod}": [
    "Method{builtins.str.__format__}"
  ],
  "Function{str_decorated_repr.cachedmethod}[formal(f, position=0)=Method{str_decorated_repr.MyClass.__repr__}]": [
    "Method{builtins.str.__format__}"
  ],
  "Function{str_decorated_repr.test_str_of_decorated_repr}": [
    "Function{str_decorated_repr._test_sink}",
    "Function{str_decorated_repr.cachedmethod.g}[captured_variable(f, str_decorated_repr.cachedmethod)=Method{str_decorated_repr.MyClass.__repr__}]",
    "Method{builtins.object.__init__}", "Method{builtins.str.__new__}"
  ],
  "Method{str_decorated_repr.MyClass.__repr__@decorated}": [
    "Function{str_decorated_repr.cachedmethod}[formal(f, position=0)=Method{str_decorated_repr.MyClass.__repr__}]"
  ]
}