@generated
Call dependencies
{
  "Function{strings.bad_1}": [
    "Function{pysa._test_sink}", "Function{pysa._test_source}",
    "Function{strings.concatenate_lhs}"
  ],
  "Function{strings.bad_2}": [
    "Function{pysa._test_sink}", "Function{pysa._test_source}",
    "Function{strings.concatenate_rhs}"
  ],
  "Function{strings.concatenate_lhs}": [ "Method{builtins.str.__add__}" ],
  "Function{strings.concatenate_rhs}": [ "Method{builtins.str.__add__}" ],
  "Function{strings.either}": [
    "Function{pysa._test_sink}", "Function{pysa._test_source}",
    "Function{strings.concatenate_lhs}", "Function{strings.concatenate_rhs}"
  ],
  "Function{strings.format_sink}": [
    "Function{pysa._test_sink}", "Method{builtins.str.format}"
  ],
  "Function{strings.format_source}": [
    "Function{pysa._test_source}", "Method{builtins.str.format}"
  ],
  "Function{strings.format_tito}": [ "Method{builtins.str.format}" ],
  "Function{strings.iadd_lhs_infer_sink}": [
    "Function{pysa._test_sink}", "Method{builtins.str.__add__}"
  ],
  "Function{strings.iadd_rhs_infer_sink}": [
    "Function{pysa._test_sink}", "Method{builtins.str.__add__}"
  ],
  "Function{strings.maybe_lhs}": [
    "Function{pysa._test_sink}", "Function{pysa._test_source}",
    "Function{strings.concatenate_lhs}"
  ],
  "Function{strings.maybe_rhs}": [
    "Function{pysa._test_sink}", "Function{pysa._test_source}",
    "Function{strings.concatenate_rhs}"
  ],
  "Function{strings.through_iadd}": [
    "Function{pysa._test_sink}", "Function{pysa._test_source}",
    "Method{builtins.str.__add__}"
  ]
}