@generated
Call dependencies
{
  "Function{string_conversion.analyze_implicit_call}": [
    "ClassInstanceAttribute{django.http.Request.GET}",
    "Function{builtins.eval}", "Method{builtins.dict.__getitem__}",
    "Method{builtins.object.__init__}", "Method{builtins.object.__new__}",
    "Method{builtins.str.__format__}", "Method{builtins.str.__new__}",
    "Method{string_conversion.B.__str__}"
  ],
  "Function{string_conversion.backward_unioned_callees_2}": [
    "Method{string_conversion.D.__str__}"
  ],
  "Function{string_conversion.backward_unioned_callees}": [
    "Method{builtins.str.__format__}", "Method{string_conversion.D.__str__}"
  ],
  "Function{string_conversion.base_exception}": [
    "Method{builtins.type.__init__}", "Method{builtins.type.__new__}"
  ],
  "Function{string_conversion.compute_tito}": [
    "Function{string_conversion.tito_f}",
    "Function{string_conversion.tito_g}"
  ],
  "Function{string_conversion.explicit_str}": [
    "Function{builtins.eval}", "Method{builtins.object.__init__}",
    "Method{builtins.object.__new__}",
    "Method{string_conversion.StrIsTainted.__str__}"
  ],
  "Function{string_conversion.forward_unioned_callees_2}": [
    "Function{pysa._test_source}", "Method{string_conversion.D.__str__}"
  ],
  "Function{string_conversion.forward_unioned_callees}": [
    "Function{pysa._test_source}", "Method{builtins.str.__format__}",
    "Method{string_conversion.D.__str__}"
  ],
  "Function{string_conversion.function_call_target_1}": [
    "Method{builtins.str.__format__}"
  ],
  "Function{string_conversion.implicit_repr}": [
    "Function{builtins.eval}", "Method{builtins.object.__init__}",
    "Method{builtins.object.__new__}",
    "Method{string_conversion.ReprIsTainted.__repr__}"
  ],
  "Function{string_conversion.implicit_str}": [
    "Function{builtins.eval}", "Method{builtins.object.__init__}",
    "Method{builtins.object.__new__}",
    "Method{string_conversion.StrIsTainted.__str__}"
  ],
  "Function{string_conversion.join_source_and_attribute_source}": [
    "ClassInstanceAttribute{django.http.Request.GET}",
    "Function{builtins.eval}", "Method{builtins.dict.__getitem__}",
    "Method{builtins.int.__gt__}", "Method{builtins.object.__init__}",
    "Method{builtins.object.__new__}", "Method{builtins.str.__format__}",
    "Method{string_conversion.C.__str__}"
  ],
  "Function{string_conversion.joined_base}": [
    "ClassInstanceAttribute{django.http.Request.GET}",
    "Function{builtins.eval}", "Method{builtins.dict.__getitem__}",
    "Method{builtins.str.__format__}"
  ],
  "Function{string_conversion.multiple_callees_same_location}": [
    "Method{builtins.object.__init__}", "Method{builtins.object.__new__}",
    "Method{builtins.str.__add__}", "Method{builtins.str.__new__}",
    "Method{string_conversion.StrIsTainted.__str__}"
  ],
  "Function{string_conversion.multiple_targets_for_single_expression_2}": [
    "Function{builtins.eval}", "Method{builtins.int.__format__}",
    "Method{string_conversion.B.__str__}",
    "Method{string_conversion.C.__str__}"
  ],
  "Function{string_conversion.multiple_targets_for_single_expression_3}": [
    "Method{builtins.int.__format__}", "Method{string_conversion.B.__str__}",
    "Method{string_conversion.C.__str__}"
  ],
  "Function{string_conversion.multiple_targets_for_single_expression}": [
    "Function{builtins.eval}", "Method{string_conversion.A.__str__}",
    "Method{string_conversion.StrIsTainted.__str__}"
  ],
  "Function{string_conversion.not_propagate_taint}": [
    "Function{builtins.eval}", "Method{builtins.object.__new__}",
    "Method{string_conversion.A.__init__}",
    "Method{string_conversion.A.__str__}"
  ],
  "Function{string_conversion.object_type}": [
    "Method{builtins.object.__format__}"
  ],
  "Function{string_conversion.optional_str}": [
    "Function{builtins.eval}", "Method{builtins.object.__init__}",
    "Method{builtins.object.__new__}", "Method{builtins.str.__new__}",
    "Method{string_conversion.StrIsTainted.__str__}",
    "Override{builtins.object.__repr__}"
  ],
  "Function{string_conversion.propagate_taint}": [
    "ClassInstanceAttribute{django.http.Request.GET}",
    "Function{builtins.eval}", "Method{builtins.dict.__getitem__}",
    "Method{builtins.object.__new__}",
    "Method{string_conversion.A.__init__}",
    "Method{string_conversion.A.__str__}"
  ],
  "Function{string_conversion.repr_is_tainted}": [
    "Function{builtins.eval}", "Function{builtins.repr}",
    "Method{builtins.object.__init__}", "Method{builtins.object.__new__}",
    "Method{string_conversion.ReprIsTainted.__repr__}"
  ],
  "Function{string_conversion.str_falls_back_to_repr}": [
    "Function{builtins.eval}", "Method{builtins.object.__init__}",
    "Method{builtins.object.__new__}", "Method{builtins.str.__new__}",
    "Method{string_conversion.ReprIsTainted.__repr__}"
  ],
  "Function{string_conversion.str_is_tainted}": [
    "Function{builtins.eval}", "Method{builtins.object.__init__}",
    "Method{builtins.object.__new__}", "Method{builtins.str.__new__}",
    "Method{string_conversion.StrIsTainted.__str__}"
  ],
  "Function{string_conversion.test_str_with_double_starred_kwargs}": [
    "Method{builtins.object.__init__}", "Method{builtins.str.__new__}"
  ],
  "Function{string_conversion.test_str_with_starred_args}": [
    "Method{builtins.object.__init__}", "Method{builtins.str.__new__}"
  ],
  "Method{string_conversion.C.__str__}": [
    "ClassInstanceAttribute{string_conversion.C.g}"
  ],
  "Method{string_conversion.OverrideStr.__str__}": [
    "Function{pysa._test_source}"
  ],
  "Method{string_conversion.ReprIsTainted.__repr__}": [
    "ClassInstanceAttribute{django.http.Request.GET}",
    "Method{builtins.dict.__getitem__}"
  ],
  "Method{string_conversion.StrIsTainted.__str__}": [
    "ClassInstanceAttribute{django.http.Request.GET}",
    "Method{builtins.dict.__getitem__}"
  ]
}