@generated
Call dependencies
{
  "Function{supers.B_overwrite_both}": [
    "Method{builtins.object.__new__}", "Method{supers.A.__init__}",
    "Override{supers.B.g2}"
  ],
  "Function{supers.B_overwrite_partial}": [
    "Method{builtins.object.__new__}", "Method{supers.A.__init__}",
    "Override{supers.B.g3}"
  ],
  "Function{supers.B_standard}": [
    "Method{builtins.object.__new__}", "Method{supers.A.__init__}",
    "Method{supers.B.g4}"
  ],
  "Function{supers.attribute_B_not_overwritten}": [
    "Method{builtins.object.__new__}", "Method{supers.A.__init__}",
    "Override{supers.B.g1}"
  ],
  "Function{supers.attribute_B_overwritten}": [
    "Method{builtins.object.__new__}", "Method{supers.A.__init__}",
    "Override{supers.B.g1}"
  ],
  "Function{supers.attribute_C_not_overwritten}": [
    "Method{builtins.object.__new__}", "Method{supers.A.__init__}",
    "Override{supers.C.g1}"
  ],
  "Function{supers.attribute_C_overwritten}": [
    "Method{builtins.object.__new__}", "Method{supers.A.__init__}",
    "Override{supers.C.g1}"
  ],
  "Function{supers.attribute_D_not_overwritten}": [
    "Method{builtins.object.__new__}", "Method{supers.A.__init__}",
    "Method{supers.D.g1}"
  ],
  "Function{supers.attribute_D_overwritten}": [
    "Method{builtins.object.__new__}", "Method{supers.A.__init__}",
    "Method{supers.D.g1}"
  ],
  "Function{supers.attribute_E_not_overwritten_RCE}": [
    "Method{builtins.object.__new__}", "Method{supers.A.__init__}",
    "Method{supers.E.g3}"
  ],
  "Function{supers.attribute_E_not_overwritten}": [
    "Method{builtins.object.__new__}", "Method{supers.A.__init__}",
    "Method{supers.E.g1}", "Method{supers.E.g2}"
  ],
  "Function{supers.attribute_E_overwritten}": [
    "Method{builtins.object.__new__}", "Method{supers.A.__init__}",
    "Method{supers.E.g1}", "Method{supers.E.g2}", "Method{supers.E.g3}"
  ],
  "Method{supers.A.__init__}": [ "Function{pysa._test_source}" ],
  "Method{supers.A.f1}": [ "Function{pysa._test_sink}" ],
  "Method{supers.A.f2}": [ "Function{pysa._test_sink}" ],
  "Method{supers.A.f3}": [ "Function{pysa._test_source}" ],
  "Method{supers.B.f4}": [ "Function{pysa._test_source}" ],
  "Method{supers.B.f5}": [ "Function{pysa._test_sink}" ],
  "Method{supers.B.g1}": [
    "Method{builtins.object.__new__}", "Method{builtins.super.__init__}",
    "Method{supers.A.f1}", "Method{supers.A.f2}", "Method{supers.A.f3}"
  ],
  "Method{supers.B.g2}": [
    "Method{builtins.object.__new__}", "Method{builtins.super.__init__}",
    "Method{supers.A.f4}", "Method{supers.A.f5}"
  ],
  "Method{supers.B.g3}": [
    "Method{builtins.object.__new__}", "Method{builtins.super.__init__}",
    "Method{supers.A.f4}", "Method{supers.A.f5}", "Method{supers.B.f4}",
    "Method{supers.B.f5}"
  ],
  "Method{supers.B.g4}": [ "Method{supers.B.f4}", "Method{supers.B.f5}" ],
  "Method{supers.C.g1}": [
    "Method{builtins.object.__new__}", "Method{builtins.super.__init__}",
    "Method{supers.A.f1}"
  ],
  "Method{supers.D.g1}": [
    "Method{builtins.object.__new__}", "Method{builtins.super.__init__}",
    "Method{supers.A.f1}"
  ],
  "Method{supers.E.g1}": [
    "Method{builtins.object.__new__}", "Method{builtins.super.__init__}",
    "Method{supers.B.f1}"
  ],
  "Method{supers.E.g2}": [
    "Method{builtins.object.__new__}", "Method{builtins.super.__init__}",
    "Method{supers.B.f1}"
  ],
  "Method{supers.E.g3}": [
    "Method{builtins.object.__new__}", "Method{builtins.super.__init__}",
    "Method{supers.A.f1}"
  ]
}