@generated
Call dependencies
{
  "Function{taint_in_taint_out.ComplexEvaluator.evaluate_lazy_payload._evaluate}": [
    "Function{builtins.isinstance}",
    "Method{taint_in_taint_out.ComplexEvaluator.evaluate_lazy_field}",
    "Method{taint_in_taint_out.ComplexEvaluator.evaluate_lazy_payload}"
  ],
  "Function{taint_in_taint_out.adds_tito_inherited}": [
    "ClassInstanceAttribute{taint_in_taint_out.FieldIsTITO.add_tito}"
  ],
  "Function{taint_in_taint_out.adds_tito_with_indirect_sink}": [
    "Function{taint_in_taint_out.indirect_sink}"
  ],
  "Function{taint_in_taint_out.adds_tito}": [
    "ClassInstanceAttribute{taint_in_taint_out.FieldIsTITO.add_tito}"
  ],
  "Function{taint_in_taint_out.collapse_two_then_into_deep_dict}": [
    "Function{taint_in_taint_out.tito_collapse_two}"
  ],
  "Function{taint_in_taint_out.collapse_two_then_into_dict}": [
    "Function{taint_in_taint_out.tito_collapse_two}"
  ],
  "Function{taint_in_taint_out.combine_collapse_one_and_two}": [
    "Function{taint_in_taint_out.tito_collapse_one}",
    "Function{taint_in_taint_out.tito_collapse_two}"
  ],
  "Function{taint_in_taint_out.combine_collapse_one}": [
    "Function{taint_in_taint_out.tito_collapse_one}"
  ],
  "Function{taint_in_taint_out.combine_collapse_three}": [
    "Function{taint_in_taint_out.tito_collapse_three}"
  ],
  "Function{taint_in_taint_out.combine_collapse_two_and_one}": [
    "Function{taint_in_taint_out.tito_collapse_one}",
    "Function{taint_in_taint_out.tito_collapse_two}"
  ],
  "Function{taint_in_taint_out.combine_collapse_two}": [
    "Function{taint_in_taint_out.tito_collapse_two}"
  ],
  "Function{taint_in_taint_out.evaluate_lazy}": [
    "Method{builtins.dict.items}", "Method{typing.ItemsView.__iter__}",
    "Method{typing.Iterator.__next__}"
  ],
  "Function{taint_in_taint_out.forward_taint_kwargs_into_parameters}": [
    "Function{pysa._test_sink}", "Function{pysa._test_source}",
    "Method{builtins.object.__new__}",
    "Method{taint_in_taint_out.ClassManyFields.__init__}"
  ],
  "Function{taint_in_taint_out.get_related}": [
    "Method{builtins.object.__new__}",
    "Method{taint_in_taint_out.Recursive.__init__}"
  ],
  "Function{taint_in_taint_out.indirect_sink}": [
    "ClassInstanceAttribute{taint_in_taint_out.FieldIsTITO.add_tito}",
    "Function{pysa._test_sink}"
  ],
  "Function{taint_in_taint_out.into_dict_then_collapse_two}": [
    "Function{taint_in_taint_out.tito_collapse_two}"
  ],
  "Function{taint_in_taint_out.into_dict_then_perfect_tito}": [
    "Function{taint_in_taint_out.perfect_tito}"
  ],
  "Function{taint_in_taint_out.into_dict_then_tito_collapse}": [
    "Function{taint_in_taint_out.obscure_tito}"
  ],
  "Function{taint_in_taint_out.issue_approximate_return_access_paths_common_prefix}": [
    "Function{pysa._test_sink}", "Function{pysa._test_source}",
    "Function{taint_in_taint_out.approximate_return_access_paths}",
    "Method{builtins.dict.__getitem__}", "Method{builtins.object.__new__}",
    "Method{taint_in_taint_out.Object.__init__}"
  ],
  "Function{taint_in_taint_out.issue_approximate_return_access_paths}": [
    "Function{pysa._test_sink}", "Function{pysa._test_source}",
    "Function{taint_in_taint_out.approximate_return_access_paths}",
    "Method{builtins.dict.__getitem__}", "Method{builtins.object.__new__}",
    "Method{taint_in_taint_out.Object.__init__}"
  ],
  "Function{taint_in_taint_out.issue_join_tito_collapse_test_3}": [
    "Function{pysa._test_sink}", "Function{pysa._test_source}",
    "Function{taint_in_taint_out.join_tito_collapse_test_3}",
    "Method{builtins.dict.__getitem__}"
  ],
  "Function{taint_in_taint_out.issue_user_declared_tito_collapse_one}": [
    "Function{pysa._test_sink}", "Function{pysa._test_source}",
    "Function{taint_in_taint_out.user_declared_tito_collapse_one}"
  ],
  "Function{taint_in_taint_out.issue_with_indirect_sink_tito}": [
    "Function{pysa._test_source}",
    "Function{taint_in_taint_out.adds_tito_with_indirect_sink}"
  ],
  "Function{taint_in_taint_out.issue_with_into_dict_then_tito_collapse}": [
    "Function{pysa._test_sink}", "Function{pysa._test_source}",
    "Function{taint_in_taint_out.into_dict_then_tito_collapse}"
  ],
  "Function{taint_in_taint_out.join_tito_collapse_test_1}": [
    "Function{taint_in_taint_out.tito_collapse_one}",
    "Function{taint_in_taint_out.tito_collapse_two}",
    "Method{_random.Random.random}", "Method{builtins.float.__gt__}",
    "Method{builtins.object.__new__}",
    "Method{taint_in_taint_out.Object.__init__}"
  ],
  "Function{taint_in_taint_out.join_tito_collapse_test_2}": [
    "Function{taint_in_taint_out.tito_collapse_three}",
    "Function{taint_in_taint_out.tito_collapse_two}",
    "Method{_random.Random.random}", "Method{builtins.float.__gt__}",
    "Method{builtins.object.__new__}",
    "Method{taint_in_taint_out.Object.__init__}"
  ],
  "Function{taint_in_taint_out.join_tito_collapse_test_3}": [
    "Function{taint_in_taint_out.tito_collapse_one}",
    "Function{taint_in_taint_out.tito_collapse_two}",
    "Method{_random.Random.random}", "Method{builtins.float.__gt__}"
  ],
  "Function{taint_in_taint_out.loop_perfect_tito}": [
    "Function{taint_in_taint_out.perfect_tito}",
    "Method{builtins.object.__init__}", "Method{builtins.range.__iter__}",
    "Method{builtins.range.__new__}", "Method{typing.Iterator.__next__}"
  ],
  "Function{taint_in_taint_out.loop_tito_collapse_one}": [
    "Function{taint_in_taint_out.tito_collapse_one}",
    "Method{builtins.object.__init__}", "Method{builtins.range.__iter__}",
    "Method{builtins.range.__new__}", "Method{typing.Iterator.__next__}"
  ],
  "Function{taint_in_taint_out.loop_tito_collapse_two}": [
    "Function{taint_in_taint_out.tito_collapse_two}",
    "Method{builtins.object.__init__}", "Method{builtins.range.__iter__}",
    "Method{builtins.range.__new__}", "Method{typing.Iterator.__next__}"
  ],
  "Function{taint_in_taint_out.no_issue_tito_collapse_two_with_input_path}": [
    "Function{pysa._test_sink}", "Function{pysa._test_source}",
    "Function{taint_in_taint_out.tito_collapse_one_with_input_path}"
  ],
  "Function{taint_in_taint_out.no_issue_user_declared_tito_collapse_one}": [
    "Function{pysa._test_sink}", "Function{pysa._test_source}",
    "Function{taint_in_taint_out.user_declared_tito_collapse_one}"
  ],
  "Function{taint_in_taint_out.no_issue_user_declared_tito_no_collapse}": [
    "Function{pysa._test_sink}", "Function{pysa._test_source}",
    "Function{taint_in_taint_out.user_declared_tito_no_collapse}"
  ],
  "Function{taint_in_taint_out.no_issue_with_into_dict_then_perfect_tito}": [
    "Function{pysa._test_sink}", "Function{pysa._test_source}",
    "Function{taint_in_taint_out.into_dict_then_perfect_tito}"
  ],
  "Function{taint_in_taint_out.no_issue_with_perfect_tito_then_into_dict}": [
    "Function{pysa._test_sink}", "Function{pysa._test_source}",
    "Function{taint_in_taint_out.perfect_tito_then_into_dict}",
    "Method{builtins.dict.__getitem__}"
  ],
  "Function{taint_in_taint_out.no_issue_with_tito_collapse_then_into_dict}": [
    "Function{pysa._test_sink}", "Function{pysa._test_source}",
    "Function{taint_in_taint_out.tito_collapse_then_into_dict}",
    "Method{builtins.dict.__getitem__}"
  ],
  "Function{taint_in_taint_out.no_tito_init_then_overwrite}": [
    "Method{builtins.dict.__setitem__}"
  ],
  "Function{taint_in_taint_out.non_issue_approximate_return_access_paths_common_prefix}": [
    "Function{pysa._test_sink}", "Function{pysa._test_source}",
    "Function{taint_in_taint_out.approximate_return_access_paths}",
    "Method{builtins.dict.__getitem__}", "Method{builtins.object.__new__}",
    "Method{taint_in_taint_out.Object.__init__}"
  ],
  "Function{taint_in_taint_out.perfect_tito_then_into_deep_dict}": [
    "Function{taint_in_taint_out.perfect_tito}"
  ],
  "Function{taint_in_taint_out.perfect_tito_then_into_dict}": [
    "Function{taint_in_taint_out.perfect_tito}"
  ],
  "Function{taint_in_taint_out.perfect_tito_with_tree_manipulation}": [
    "Method{builtins.dict.__getitem__}"
  ],
  "Function{taint_in_taint_out.product_data_wrapper}": [
    "Function{taint_in_taint_out.product_data}"
  ],
  "Function{taint_in_taint_out.product_data}": [
    "Function{taint_in_taint_out._unpack}",
    "Function{taint_in_taint_out.get_data}",
    "Function{taint_in_taint_out.product_data}",
    "Function{taint_in_taint_out.some_service}",
    "Method{builtins.dict.__getitem__}", "Method{builtins.object.__init__}",
    "Method{builtins.object.__new__}"
  ],
  "Function{taint_in_taint_out.test_always_via_feature}": [
    "Function{pysa._test_sink}", "Function{pysa._test_source}",
    "Function{taint_in_taint_out.tito_with_feature}"
  ],
  "Function{taint_in_taint_out.test_complex_argument_tito}": [
    "Function{pysa._test_sink}", "Function{pysa._test_source}",
    "Function{taint_in_taint_out.complex_argument_tito}",
    "Method{builtins.object.__new__}",
    "Method{taint_in_taint_out.Object.__init__}"
  ],
  "Function{taint_in_taint_out.test_complex_evaluator}": [
    "Function{pysa._test_sink}", "Function{pysa._test_source}",
    "Method{taint_in_taint_out.ComplexEvaluator.evaluate_lazy_payload}"
  ],
  "Function{taint_in_taint_out.test_explicit_call_to_superclass}": [
    "Function{pysa._test_sink}", "Function{pysa._test_source}",
    "Method{builtins.object.__new__}",
    "Method{taint_in_taint_out.GetUser.__init__}"
  ],
  "Function{taint_in_taint_out.test_simplified_evaluator}": [
    "Function{pysa._test_sink}", "Function{pysa._test_source}",
    "Function{taint_in_taint_out.evaluate_lazy}"
  ],
  "Function{taint_in_taint_out.test_tito_class_method}": [
    "Function{pysa._test_sink}", "Function{pysa._test_source}",
    "Method{taint_in_taint_out.TitoClassMethod.set_a}"
  ],
  "Function{taint_in_taint_out.test_tito_from_0_to_1}": [
    "Function{pysa._test_sink}", "Function{pysa._test_source}",
    "Function{taint_in_taint_out.tito_from_0_to_1}"
  ],
  "Function{taint_in_taint_out.test_tito_self}": [
    "Function{pysa._test_sink}", "Function{pysa._test_source}",
    "Method{builtins.object.__new__}",
    "Method{taint_in_taint_out.TitoSelf.__init__}",
    "Method{taint_in_taint_out.TitoSelf.set_a}",
    "Method{taint_in_taint_out.TitoSelf.set_join}",
    "Method{taint_in_taint_out.TitoSelf.set_subfield}"
  ],
  "Function{taint_in_taint_out.test_tuple_tito_indices}": [
    "Function{pysa._test_sink}", "Function{pysa._test_source}",
    "Function{taint_in_taint_out.return_taint}"
  ],
  "Function{taint_in_taint_out.tito_collapse_one_with_input_path_with_hop}": [
    "Function{taint_in_taint_out.tito_collapse_one_with_input_path}"
  ],
  "Function{taint_in_taint_out.tito_collapse_one_with_input_path}": [
    "Function{taint_in_taint_out.tito_collapse_one}"
  ],
  "Function{taint_in_taint_out.tito_collapse_one}": [
    "Function{taint_in_taint_out.tito_collapse_one_append_a_b_c}",
    "Method{builtins.dict.__getitem__}"
  ],
  "Function{taint_in_taint_out.tito_collapse_then_into_dict}": [
    "Function{taint_in_taint_out.obscure_tito}"
  ],
  "Function{taint_in_taint_out.tito_collapse_three}": [
    "Function{taint_in_taint_out.tito_collapse_three_append_a}",
    "Method{builtins.dict.__getitem__}"
  ],
  "Function{taint_in_taint_out.tito_collapse_two}": [
    "Function{taint_in_taint_out.tito_collapse_two_append_a_b}",
    "Method{builtins.dict.__getitem__}"
  ],
  "Function{taint_in_taint_out.tito_from_0_to_1}": [
    "Function{taint_in_taint_out.random_integer}",
    "Method{builtins.dict.__setitem__}"
  ],
  "Function{taint_in_taint_out.tito_via_kwargs_into_parameters}": [
    "Method{builtins.object.__new__}",
    "Method{taint_in_taint_out.ClassManyFields.__init__}"
  ],
  "Function{taint_in_taint_out.tito_with_feature}": [
    "Function{taint_in_taint_out.add_feature}"
  ],
  "Function{taint_in_taint_out.tito_with_sink}": [
    "Function{pysa._test_sink}"
  ],
  "Function{taint_in_taint_out.tito}": [
    "Function{pysa._test_source}",
    "Function{taint_in_taint_out.product_data_wrapper}"
  ],
  "Function{taint_in_taint_out.via_getattr}": [
    "Function{builtins.getattr}"
  ],
  "Method{taint_in_taint_out.ComplexEvaluator.evaluate_lazy_field}": [
    "Function{builtins.callable}"
  ],
  "Method{taint_in_taint_out.ComplexEvaluator.evaluate_lazy_payload}": [
    "Function{taint_in_taint_out.ComplexEvaluator.evaluate_lazy_payload._evaluate}"
  ],
  "Method{taint_in_taint_out.GetUser.__init__}": [
    "Method{taint_in_taint_out.GetQuery.__init__}"
  ],
  "Method{taint_in_taint_out.Recursive.__init__}": [
    "Function{taint_in_taint_out.get_related}",
    "Method{builtins.object.__init__}", "Method{builtins.slice.__new__}"
  ],
  "Method{taint_in_taint_out.TitoSelf.self_tito}": [
    "Function{taint_in_taint_out.perfect_tito}"
  ],
  "Method{taint_in_taint_out.TitoSelf.set_join}": [
    "Method{_random.Random.random}", "Method{builtins.float.__gt__}"
  ],
  "Method{taint_in_taint_out.TitoSelf.set_subfield}": [
    "Function{taint_in_taint_out.perfect_tito}"
  ]
}