@generated
Call dependencies
{
  "Function{taint_transform.a_sanitize_b_to_x_to_b_issue}": [
    "Function{taint_transform.sink_b}",
    "Function{taint_transform.source_a_sanitize_b_taint}",
    "Function{taint_transform.transform_x}"
  ],
  "Function{taint_transform.a_sanitize_b_to_xb_issue}": [
    "Function{taint_transform.sink_taint_with_transform_x}",
    "Function{taint_transform.source_a_sanitize_b_taint}"
  ],
  "Function{taint_transform.a_sanitize_b_x_to_b_issue}": [
    "Function{taint_transform.sink_b}",
    "Function{taint_transform.source_a_sanitize_b_transform_x_taint}"
  ],
  "Function{taint_transform.a_to_b_no_issue}": [
    "Function{taint_transform.sink_b}", "Function{taint_transform.source_a}"
  ],
  "Function{taint_transform.a_to_sanitize_a_to_x_to_b_no_issue}": [
    "Function{taint_transform.sanitize_source_a_tito}",
    "Function{taint_transform.sink_b}", "Function{taint_transform.source_a}",
    "Function{taint_transform.transform_x}"
  ],
  "Function{taint_transform.a_to_sanitize_a_x_to_b_no_issue}": [
    "Function{taint_transform.sanitize_a_transform_x_tito}",
    "Function{taint_transform.sink_b}", "Function{taint_transform.source_a}"
  ],
  "Function{taint_transform.a_to_sanitize_a_yzb_no_issue}": [
    "Function{taint_transform.sanitize_a_to_y_to_z_to_b_taint}",
    "Function{taint_transform.source_a}"
  ],
  "Function{taint_transform.a_to_sanitize_b_to_x_to_b_issue}": [
    "Function{taint_transform.sanitize_sink_b_tito}",
    "Function{taint_transform.sink_b}", "Function{taint_transform.source_a}",
    "Function{taint_transform.transform_x}"
  ],
  "Function{taint_transform.a_to_sanitize_b_x_to_b_issue}": [
    "Function{taint_transform.sanitize_b_transform_x_tito}",
    "Function{taint_transform.sink_b}", "Function{taint_transform.source_a}"
  ],
  "Function{taint_transform.a_to_x_sanitize_a_b_issue}": [
    "Function{taint_transform.source_a}",
    "Function{taint_transform.transform_x_sanitize_a_sink_b_taint}"
  ],
  "Function{taint_transform.a_to_x_sanitize_a_to_b_issue}": [
    "Function{taint_transform.sink_b}", "Function{taint_transform.source_a}",
    "Function{taint_transform.transform_x_sanitize_a_tito}"
  ],
  "Function{taint_transform.a_to_x_sanitize_b_to_b_no_issue}": [
    "Function{taint_transform.sink_b}", "Function{taint_transform.source_a}",
    "Function{taint_transform.transform_x_sanitize_b_tito}"
  ],
  "Function{taint_transform.a_to_x_to_b_issue}": [
    "Function{taint_transform.sink_b}", "Function{taint_transform.source_a}",
    "Function{taint_transform.transform_x}"
  ],
  "Function{taint_transform.a_to_x_to_sanitize_a_b_issue}": [
    "Function{taint_transform.sanitize_a_sink_b_taint}",
    "Function{taint_transform.source_a}",
    "Function{taint_transform.transform_x}"
  ],
  "Function{taint_transform.a_to_x_to_sanitize_a_to_b_issue}": [
    "Function{taint_transform.sanitize_source_a_tito}",
    "Function{taint_transform.sink_b}", "Function{taint_transform.source_a}",
    "Function{taint_transform.transform_x}"
  ],
  "Function{taint_transform.a_to_x_to_sanitize_b_to_b_no_issue}": [
    "Function{taint_transform.sanitize_sink_b_tito}",
    "Function{taint_transform.sink_b}", "Function{taint_transform.source_a}",
    "Function{taint_transform.transform_x}"
  ],
  "Function{taint_transform.a_to_x_to_x_b_no_issue}": [
    "Function{taint_transform.sink_b}", "Function{taint_transform.source_a}",
    "Function{taint_transform.transform_x}"
  ],
  "Function{taint_transform.a_to_y_to_z_to_b_issue}": [
    "Function{taint_transform.sink_b}", "Function{taint_transform.source_a}",
    "Function{taint_transform.transform_y}",
    "Function{taint_transform.transform_z}"
  ],
  "Function{taint_transform.a_to_y_zb_issue}": [
    "Function{taint_transform.sink_taint_with_transform_z}",
    "Function{taint_transform.source_a}",
    "Function{taint_transform.transform_y}"
  ],
  "Function{taint_transform.a_to_yz_to_b_issue}": [
    "Function{taint_transform.sink_b}", "Function{taint_transform.source_a}",
    "Function{taint_transform.tito_with_transform_yz}"
  ],
  "Function{taint_transform.a_to_yz_to_d_no_issue}": [
    "Function{taint_transform.sink_d}", "Function{taint_transform.source_a}",
    "Function{taint_transform.tito_with_transform_yz}"
  ],
  "Function{taint_transform.a_to_yzb_issue}": [
    "Function{taint_transform.sink_taint_with_transform_yz}",
    "Function{taint_transform.source_a}"
  ],
  "Function{taint_transform.a_to_z_to_y_to_b_no_issue}": [
    "Function{taint_transform.sink_b}", "Function{taint_transform.source_a}",
    "Function{taint_transform.transform_y}",
    "Function{taint_transform.transform_z}"
  ],
  "Function{taint_transform.a_x_sanitize_b_to_b_no_issue}": [
    "Function{taint_transform.sink_b}",
    "Function{taint_transform.source_a_transform_x_sanitize_b_taint}"
  ],
  "Function{taint_transform.ax_to_sanitize_a_b_issue}": [
    "Function{taint_transform.sanitize_a_sink_b_taint}",
    "Function{taint_transform.taint_with_transform_x}"
  ],
  "Function{taint_transform.ax_to_zb_no_issue}": [
    "Function{taint_transform.sink_taint_with_transform_z}",
    "Function{taint_transform.taint_with_transform_x_obscure}"
  ],
  "Function{taint_transform.axy_to_sanitize_a_yzb_issue}": [
    "Function{taint_transform.sanitize_a_to_y_to_z_to_b_taint}",
    "Function{taint_transform.taint_with_transform_yx}"
  ],
  "Function{taint_transform.ay_to_z_to_b_issue}": [
    "Function{taint_transform.sink_b}",
    "Function{taint_transform.source_taint_with_transform_y}",
    "Function{taint_transform.transform_z}"
  ],
  "Function{taint_transform.ay_to_zb_issue}": [
    "Function{taint_transform.sink_taint_with_transform_z}",
    "Function{taint_transform.source_taint_with_transform_y}"
  ],
  "Function{taint_transform.ayz_to_b_issue}": [
    "Function{taint_transform.sink_b}",
    "Function{taint_transform.source_taint_via_tito_tranform_yz}"
  ],
  "Function{taint_transform.c_to_d_issue}": [
    "Function{taint_transform.sink_d}", "Function{taint_transform.source_c}"
  ],
  "Function{taint_transform.c_to_sanitize_c_to_d_no_issue}": [
    "Function{taint_transform.sanitize_source_c_tito}",
    "Function{taint_transform.sink_d}", "Function{taint_transform.source_c}"
  ],
  "Function{taint_transform.c_to_sanitize_d_to_d_no_issue}": [
    "Function{taint_transform.sanitize_sink_d_tito}",
    "Function{taint_transform.sink_d}", "Function{taint_transform.source_c}"
  ],
  "Function{taint_transform.c_to_x_to_d_no_issue}": [
    "Function{taint_transform.sink_d}", "Function{taint_transform.source_c}",
    "Function{taint_transform.transform_x}"
  ],
  "Function{taint_transform.c_to_yz_to_b_no_issue}": [
    "Function{taint_transform.sink_b}", "Function{taint_transform.source_c}",
    "Function{taint_transform.tito_with_transform_yz}"
  ],
  "Function{taint_transform.issue_with_repeated_transforms}": [
    "Function{taint_transform.sink_taint_with_transform_yz}",
    "Function{taint_transform.taint_with_transform_yx}"
  ],
  "Function{taint_transform.nested_tito_transform_x}": [
    "Function{taint_transform.tito_with_transform_x}"
  ],
  "Function{taint_transform.no_issue_transform_x_tito_global_sanitize_b}": [
    "Function{taint_transform.sink_b}", "Function{taint_transform.source_a}",
    "Function{taint_transform.transform_x_tito_global_sanitize_b}"
  ],
  "Function{taint_transform.no_issue_transform_x_tito_sanitize_b_all_parameters}": [
    "Function{taint_transform.sink_b}", "Function{taint_transform.source_a}",
    "Function{taint_transform.transform_x_tito_sanitize_b_all_parameters}"
  ],
  "Function{taint_transform.no_issue_transform_x_tito_sanitize_b}": [
    "Function{taint_transform.sink_b}", "Function{taint_transform.source_a}",
    "Function{taint_transform.transform_x_tito_sanitize_b}"
  ],
  "Function{taint_transform.no_issue_transform_x_tito_sanitize_return}": [
    "Function{taint_transform.sink_b}", "Function{taint_transform.source_a}",
    "Function{taint_transform.transform_x_tito_sanitize_return}"
  ],
  "Function{taint_transform.no_sink_taint_with_transform_y}": [
    "Function{taint_transform.sink_b}",
    "Function{taint_transform.transform_y}"
  ],
  "Function{taint_transform.no_source_taint_with_transform_zx}": [
    "Function{taint_transform.source_a}",
    "Function{taint_transform.transform_x}",
    "Function{taint_transform.transform_z}"
  ],
  "Function{taint_transform.no_source_taint_with_transform_z}": [
    "Function{taint_transform.source_a}",
    "Function{taint_transform.transform_z}"
  ],
  "Function{taint_transform.sanitize_a_sink_b_taint}": [
    "Function{taint_transform.sanitize_source_a_tito}",
    "Function{taint_transform.sink_b}"
  ],
  "Function{taint_transform.sanitize_a_to_y_to_z_to_b_taint}": [
    "Function{taint_transform.sanitize_source_a_tito}",
    "Function{taint_transform.sink_b}",
    "Function{taint_transform.transform_y}",
    "Function{taint_transform.transform_z}"
  ],
  "Function{taint_transform.sanitize_a_transform_x_sanitize_c_transform_y}": [
    "Function{taint_transform.sanitize_a_transform_x}",
    "Function{taint_transform.sanitize_source_c_tito}",
    "Function{taint_transform.transform_y}"
  ],
  "Function{taint_transform.sanitize_a_transform_x_sink_b_no_taint}": [
    "Function{taint_transform.sanitize_source_a_tito}",
    "Function{taint_transform.sink_b}",
    "Function{taint_transform.transform_x}"
  ],
  "Function{taint_transform.sanitize_a_transform_x_tito}": [
    "Function{taint_transform.sanitize_source_a_tito}",
    "Function{taint_transform.transform_x}"
  ],
  "Function{taint_transform.sanitize_a_transform_x}": [
    "Function{taint_transform.sanitize_source_a_tito}",
    "Function{taint_transform.transform_x}"
  ],
  "Function{taint_transform.sanitize_b_transform_x_tito}": [
    "Function{taint_transform.sanitize_sink_b_tito}",
    "Function{taint_transform.transform_x}"
  ],
  "Function{taint_transform.sink_taint_via_tito_transform_yz}": [
    "Function{taint_transform.sink_b}",
    "Function{taint_transform.tito_with_transform_yz}"
  ],
  "Function{taint_transform.sink_taint_with_transform_x}": [
    "Function{taint_transform.sink_b}",
    "Function{taint_transform.transform_x}"
  ],
  "Function{taint_transform.sink_taint_with_transform_yz}": [
    "Function{taint_transform.sink_b}",
    "Function{taint_transform.transform_y}",
    "Function{taint_transform.transform_z}"
  ],
  "Function{taint_transform.sink_taint_with_transform_z}": [
    "Function{taint_transform.sink_b}",
    "Function{taint_transform.transform_z}"
  ],
  "Function{taint_transform.source_a_sanitize_b_taint}": [
    "Function{taint_transform.sanitize_sink_b_tito}",
    "Function{taint_transform.source_a}"
  ],
  "Function{taint_transform.source_a_sanitize_b_transform_x_taint}": [
    "Function{taint_transform.sanitize_sink_b_tito}",
    "Function{taint_transform.source_a}",
    "Function{taint_transform.transform_x}"
  ],
  "Function{taint_transform.source_a_transform_x_sanitize_b_taint}": [
    "Function{taint_transform.sanitize_sink_b_tito}",
    "Function{taint_transform.source_a}",
    "Function{taint_transform.transform_x}"
  ],
  "Function{taint_transform.source_a_transform_y_transform_z_sanitize_b_no_taint}": [
    "Function{taint_transform.sanitize_sink_b_tito}",
    "Function{taint_transform.source_a}",
    "Function{taint_transform.transform_y}",
    "Function{taint_transform.transform_z}"
  ],
  "Function{taint_transform.source_taint_via_tito_tranform_yz}": [
    "Function{taint_transform.source_a}",
    "Function{taint_transform.tito_with_transform_yz}"
  ],
  "Function{taint_transform.source_taint_with_transform_y}": [
    "Function{taint_transform.source_a}",
    "Function{taint_transform.transform_y}"
  ],
  "Function{taint_transform.taint_with_transform_x_obscure}": [
    "Function{taint_transform.source_a}",
    "Function{taint_transform.transform_x_obscure}"
  ],
  "Function{taint_transform.taint_with_transform_x_skip_obscure}": [
    "Function{taint_transform.source_a}",
    "Function{taint_transform.transform_x_skip_obscure}"
  ],
  "Function{taint_transform.taint_with_transform_x}": [
    "Function{taint_transform.source_a}",
    "Function{taint_transform.transform_x}"
  ],
  "Function{taint_transform.taint_with_transform_yx}": [
    "Function{taint_transform.source_a}",
    "Function{taint_transform.transform_x}",
    "Function{taint_transform.transform_y}"
  ],
  "Function{taint_transform.test_infinite_loop}": [
    "Function{taint_transform.source_a}",
    "Function{taint_transform.tito_with_transform_x}"
  ],
  "Function{taint_transform.tito_propagation_sink_sanitizer_1}": [
    "Function{taint_transform.sanitize_b_transform_x_tito}",
    "Function{taint_transform.sanitize_sink_d_tito}"
  ],
  "Function{taint_transform.tito_propagation_sink_sanitizer_2}": [
    "Function{taint_transform.sanitize_b_transform_x_tito}",
    "Function{taint_transform.sanitize_sink_d_tito}"
  ],
  "Function{taint_transform.tito_propagation_sink_sanitizer_3}": [
    "Function{taint_transform.sanitize_sink_d_tito}",
    "Function{taint_transform.transform_x_sanitize_b_tito}"
  ],
  "Function{taint_transform.tito_propagation_sink_sanitizer_4}": [
    "Function{taint_transform.sanitize_sink_d_tito}",
    "Function{taint_transform.transform_x_sanitize_b_tito}"
  ],
  "Function{taint_transform.tito_propagation_source_sanitizer_1}": [
    "Function{taint_transform.sanitize_a_transform_x_tito}",
    "Function{taint_transform.sanitize_source_c_tito}"
  ],
  "Function{taint_transform.tito_propagation_source_sanitizer_2}": [
    "Function{taint_transform.sanitize_a_transform_x_tito}",
    "Function{taint_transform.sanitize_source_c_tito}"
  ],
  "Function{taint_transform.tito_propagation_source_sanitizer_3}": [
    "Function{taint_transform.sanitize_source_c_tito}",
    "Function{taint_transform.transform_x_sanitize_a_tito}"
  ],
  "Function{taint_transform.tito_propagation_source_sanitizer_4}": [
    "Function{taint_transform.sanitize_source_c_tito}",
    "Function{taint_transform.transform_x_sanitize_a_tito}"
  ],
  "Function{taint_transform.tito_propagation_source_sink_sanitizers_mixed_1}": [
    "Function{taint_transform.sanitize_a_transform_x_tito}",
    "Function{taint_transform.sanitize_sink_d_tito}",
    "Function{taint_transform.sanitize_source_c_tito}",
    "Function{taint_transform.transform_y_sanitize_b_tito}"
  ],
  "Function{taint_transform.tito_propagation_source_sink_sanitizers_mixed_2}": [
    "Function{taint_transform.sanitize_a_transform_x_tito}",
    "Function{taint_transform.sanitize_sink_d_tito}",
    "Function{taint_transform.sanitize_source_c_tito}",
    "Function{taint_transform.transform_y_sanitize_b_tito}"
  ],
  "Function{taint_transform.tito_with_transform_x}": [
    "Function{taint_transform.transform_x}"
  ],
  "Function{taint_transform.tito_with_transform_yz}": [
    "Function{taint_transform.transform_y}",
    "Function{taint_transform.transform_z}"
  ],
  "Function{taint_transform.transform_x_sanitize_a_sink_b_taint}": [
    "Function{taint_transform.sanitize_source_a_tito}",
    "Function{taint_transform.sink_b}",
    "Function{taint_transform.transform_x}"
  ],
  "Function{taint_transform.transform_x_sanitize_a_tito}": [
    "Function{taint_transform.sanitize_source_a_tito}",
    "Function{taint_transform.transform_x}"
  ],
  "Function{taint_transform.transform_x_sanitize_all}": [
    "Function{taint_transform.sanitize_all}",
    "Function{taint_transform.transform_x}"
  ],
  "Function{taint_transform.transform_x_sanitize_b_tito}": [
    "Function{taint_transform.sanitize_sink_b_tito}",
    "Function{taint_transform.transform_x}"
  ],
  "Function{taint_transform.transform_x_tito_global_sanitize_b}": [
    "Function{taint_transform.transform_x}"
  ],
  "Function{taint_transform.transform_x_tito_sanitize_b_all_parameters}": [
    "Function{taint_transform.transform_x}"
  ],
  "Function{taint_transform.transform_x_tito_sanitize_b}": [
    "Function{taint_transform.transform_x}"
  ],
  "Function{taint_transform.transform_x_tito_sanitize_return}": [
    "Function{taint_transform.transform_x}"
  ],
  "Function{taint_transform.transform_y_sanitize_b_tito}": [
    "Function{taint_transform.sanitize_sink_b_tito}",
    "Function{taint_transform.transform_y}"
  ]
}