@generated
Call dependencies
{
  "Function{taint_broadening.issue_collapse}": [
    "Function{pysa._test_sink}", "Function{pysa._test_source}"
  ],
  "Function{taint_broadening.model_broadening_collapse_sink_width}": [
    "Function{pysa._test_sink}"
  ],
  "Function{taint_broadening.model_broadening_collapse_source_width}": [
    "Function{pysa._test_source}", "Method{builtins.dict.__setitem__}"
  ],
  "Function{taint_broadening.model_broadening_no_collapse_sink_width@decorated}": [
    "Function{taint_broadening.skip_model_broadening}[formal(f, position=0)=Function{taint_broadening.model_broadening_no_collapse_sink_width}]"
  ],
  "Function{taint_broadening.model_broadening_no_collapse_sink_width}": [
    "Function{pysa._test_sink}"
  ],
  "Function{taint_broadening.model_broadening_no_collapse_source_width@decorated}": [
    "Function{taint_broadening.skip_model_broadening}[formal(f, position=0)=Function{taint_broadening.model_broadening_no_collapse_source_width}]"
  ],
  "Function{taint_broadening.model_broadening_no_collapse_source_width}": [
    "Function{pysa._test_source}", "Method{builtins.dict.__setitem__}"
  ],
  "Function{taint_broadening.model_broadening_sink_no_collapse_depth}": [
    "Function{pysa._test_sink}"
  ],
  "Function{taint_broadening.model_broadening_source_no_collapse_depth}": [
    "Function{pysa._test_source}", "Method{builtins.dict.__getitem__}"
  ],
  "Function{taint_broadening.random_tito}": [ "Method{builtins.int.__eq__}" ],
  "Function{taint_broadening.recursive_sink_parent_attribute}": [
    "Function{pysa._test_sink}",
    "Function{taint_broadening.recursive_sink_parent_attribute}"
  ],
  "Function{taint_broadening.recursive_sink_parent}": [
    "Function{pysa._test_sink}",
    "Function{taint_broadening.recursive_sink_parent}"
  ],
  "Function{taint_broadening.sink_a}": [ "Function{pysa._test_sink}" ],
  "Function{taint_broadening.sink_taint_widening_collapse_depth}": [
    "Function{pysa._test_sink}", "Method{builtins.object.__init__}",
    "Method{builtins.range.__iter__}", "Method{builtins.range.__new__}",
    "Method{typing.Iterator.__next__}"
  ],
  "Function{taint_broadening.source_taint_widening_collapse_depth}": [
    "Function{pysa._test_source}", "Method{builtins.object.__init__}",
    "Method{builtins.range.__iter__}", "Method{builtins.range.__new__}",
    "Method{typing.Iterator.__next__}"
  ],
  "Function{taint_broadening.test_different_tito_broadenings}": [
    "Function{pysa._test_sink}", "Function{pysa._test_source}",
    "Function{taint_broadening.tito_broaden_input_and_output_paths}",
    "Function{taint_broadening.tito_broaden_input_paths_but_not_output_path}",
    "Method{builtins.dict.keys}", "Method{builtins.str.__format__}",
    "Method{builtins.str.join}"
  ],
  "Function{taint_broadening.tito_broaden_input_and_output_paths}": [
    "Method{builtins.dict.__setitem__}"
  ],
  "Function{taint_broadening.tito_broaden_input_paths_but_not_output_path}": [
    "Method{builtins.dict.__setitem__}"
  ],
  "Function{taint_broadening.tito_broaden_output_paths_but_not_input_path}": [
    "Function{taint_broadening.random_tito}",
    "Method{builtins.dict.__setitem__}"
  ],
  "Function{taint_broadening.tito_collapse_issue}": [
    "Function{pysa._test_sink}", "Function{pysa._test_source}",
    "Function{taint_broadening.tito}"
  ],
  "Function{taint_broadening.tito_collapse_sink}": [
    "Function{pysa._test_sink}", "Function{taint_broadening.tito}"
  ],
  "Function{taint_broadening.tito_collapse_source}": [
    "Function{pysa._test_source}", "Function{taint_broadening.tito}"
  ],
  "Function{taint_broadening.tito_no_broadening_input_and_output_paths@decorated}": [
    "Function{taint_broadening.skip_model_broadening}[formal(f, position=0)=Function{taint_broadening.tito_no_broadening_input_and_output_paths}]"
  ],
  "Function{taint_broadening.tito_no_broadening_input_and_output_paths}": [
    "Method{builtins.dict.__setitem__}"
  ]
}