@generated
Call dependencies
{
  "Function{typed_dict.test_sanitize_field}": [
    "Function{pysa._test_sink}", "Function{pysa._test_source}",
    "Method{typing.Mapping.__getitem__}"
  ],
  "Function{typed_dict.test_typed_dict_constructor}": [
    "Function{pysa._test_sink}", "Function{pysa._test_source}",
    "Method{_typeshed._type_checker_internals.TypedDictFallback.keys}",
    "Method{builtins.object.__new__}",
    "Method{typed_dict.SimpleTypedDict.__init__}",
    "Method{typing.Mapping.__getitem__}"
  ],
  "Function{typed_dict.test_typed_dict_setitem}": [
    "Function{pysa._test_sink}", "Function{pysa._test_source}",
    "Method{typing.Mapping.__getitem__}"
  ]
}