@generated
Call dependencies
{
  "Function{unknown_callee.test_collapse_depth}": [
    "Function{pysa._test_sink}", "Function{pysa._test_source}",
    "Function{unknown_callee.should_collapse_depth_zero}"
  ],
  "Function{unknown_callee.test_collapse_source}": [
    "Function{pysa._test_sink}", "Function{pysa._test_source}"
  ],
  "Function{unknown_callee.test_issue}": [
    "Function{pysa._test_sink}", "Function{pysa._test_source}"
  ],
  "Function{unknown_callee.test_sink_collapse}": [
    "Function{pysa._test_sink}"
  ]
}