@generated
Call dependencies
{
  "Function{via_type_of.Test3_C.$class_toplevel}": [
    "Method{builtins.object.__init__}", "Method{builtins.object.__new__}"
  ],
  "Function{via_type_of.meta}": [
    "Function{via_type_of.return_via_parameter_type}"
  ],
  "Function{via_type_of.test1_alarm1}": [
    "ClassInstanceAttribute{via_type_of.Test1_C.x}",
    "Function{pysa._test_sink}", "Function{pysa._test_source}",
    "Method{builtins.object.__new__}", "Method{via_type_of.Test1_C.__init__}"
  ],
  "Function{via_type_of.test1_alarm2}": [
    "ClassInstanceAttribute{via_type_of.Test1_C.y}",
    "Function{pysa._test_sink}", "Function{pysa._test_source}",
    "Method{builtins.object.__new__}", "Method{via_type_of.Test1_C.__init__}"
  ],
  "Function{via_type_of.test1_alarm3}": [
    "ClassInstanceAttribute{via_type_of.Test1_C.z}",
    "Function{pysa._test_sink}", "Function{pysa._test_source}",
    "Method{builtins.object.__new__}", "Method{via_type_of.Test1_C.__init__}"
  ],
  "Function{via_type_of.test1_alarm4}": [
    "ClassInstanceAttribute{via_type_of.Test1_C.x}",
    "ClassInstanceAttribute{via_type_of.Test1_C.y}",
    "ClassInstanceAttribute{via_type_of.Test1_C.z}",
    "Function{pysa._test_sink}", "Function{pysa._test_source}",
    "Method{_random.Random.random}", "Method{builtins.float.__gt__}",
    "Method{builtins.object.__new__}", "Method{via_type_of.Test1_C.__init__}"
  ],
  "Function{via_type_of.test2_alarm1}": [
    "ClassInstanceAttribute{via_type_of.Test2_C.x}",
    "Function{pysa._test_sink}", "Function{pysa._test_source}",
    "Method{builtins.object.__new__}", "Method{via_type_of.Test2_C.__init__}"
  ],
  "Function{via_type_of.test2_alarm2}": [
    "ClassInstanceAttribute{via_type_of.Test2_C.y}",
    "Function{pysa._test_sink}", "Function{pysa._test_source}",
    "Method{builtins.object.__new__}", "Method{via_type_of.Test2_C.__init__}"
  ],
  "Function{via_type_of.test2_alarm3}": [
    "ClassInstanceAttribute{via_type_of.Test2_C.z}",
    "Function{pysa._test_sink}", "Function{pysa._test_source}",
    "Method{builtins.object.__new__}", "Method{via_type_of.Test2_C.__init__}"
  ],
  "Function{via_type_of.test2_alarm4}": [
    "ClassInstanceAttribute{via_type_of.Test2_C.x}",
    "ClassInstanceAttribute{via_type_of.Test2_C.y}",
    "ClassInstanceAttribute{via_type_of.Test2_C.z}",
    "Function{pysa._test_sink}", "Function{pysa._test_source}",
    "Method{_random.Random.random}", "Method{builtins.float.__gt__}",
    "Method{builtins.object.__new__}", "Method{via_type_of.Test2_C.__init__}"
  ],
  "Function{via_type_of.test2_alarm5_via_constructor}": [
    "Function{pysa._test_sink}", "Function{pysa._test_source}",
    "Method{builtins.object.__new__}", "Method{via_type_of.Test2_C.__init__}"
  ],
  "Function{via_type_of.test3_alarm1}": [
    "ClassInstanceAttribute{via_type_of.Test3_C.x}",
    "Function{pysa._test_sink}"
  ],
  "Function{via_type_of.test3_alarm2}": [
    "ClassInstanceAttribute{via_type_of.Test3_C.y}",
    "Function{pysa._test_sink}"
  ],
  "Function{via_type_of.test3_alarm3}": [
    "ClassInstanceAttribute{via_type_of.Test3_C.z}",
    "Function{pysa._test_sink}"
  ],
  "Function{via_type_of.test3_alarm4}": [
    "ClassInstanceAttribute{via_type_of.Test3_C.x}",
    "ClassInstanceAttribute{via_type_of.Test3_C.y}",
    "ClassInstanceAttribute{via_type_of.Test3_C.z}",
    "Function{pysa._test_sink}", "Method{_random.Random.random}",
    "Method{builtins.float.__gt__}"
  ],
  "Function{via_type_of.test4_alarm1}": [
    "ClassInstanceAttribute{via_type_of.Test4_C.x}",
    "Function{pysa._test_source}"
  ],
  "Function{via_type_of.test4_alarm2}": [
    "ClassInstanceAttribute{via_type_of.Test4_C.y}",
    "Function{pysa._test_source}"
  ],
  "Function{via_type_of.test4_alarm3}": [
    "ClassInstanceAttribute{via_type_of.Test4_C.z}",
    "Function{pysa._test_source}"
  ],
  "Function{via_type_of.test_backwards_tito}": [
    "Function{via_type_of.tito}"
  ],
  "Function{via_type_of.test_lists}": [
    "Function{via_type_of.return_via_parameter_type}"
  ],
  "Function{via_type_of.test_numerals}": [
    "Function{via_type_of.return_via_parameter_type}"
  ],
  "Function{via_type_of.test_sink}": [
    "Function{via_type_of.sink_via_type_of}"
  ],
  "Function{via_type_of.test_strings}": [
    "Function{via_type_of.return_via_parameter_type}"
  ],
  "Function{via_type_of.test_tito}": [
    "Function{pysa._test_source}", "Function{via_type_of.tito}"
  ],
  "Function{via_type_of.test_via_type_of_does_not_propagate}": [
    "Function{via_type_of.meta}"
  ],
  "Method{via_type_of.Test1_C.__init__}": [
    "ClassInstanceAttribute{via_type_of.Test1_C.x}",
    "ClassInstanceAttribute{via_type_of.Test1_C.y}",
    "ClassInstanceAttribute{via_type_of.Test1_C.z}"
  ]
}