@generated
Call dependencies
{
  "Function{via_attribute_name.test_sink_attribute_x}": [
    "ClassInstanceAttribute{via_attribute_name.SinkAttributes.x}",
    "Function{pysa._test_source}"
  ],
  "Function{via_attribute_name.test_sink_attribute_y}": [
    "ClassInstanceAttribute{via_attribute_name.SinkAttributes.y}",
    "Function{pysa._test_source}"
  ],
  "Function{via_attribute_name.test_sink_attribute_z}": [
    "ClassInstanceAttribute{via_attribute_name.SinkAttributes.z}",
    "Function{pysa._test_source}"
  ],
  "Function{via_attribute_name.test_source_attribute_join}": [
    "ClassInstanceAttribute{via_attribute_name.SourceAttributes.x}",
    "ClassInstanceAttribute{via_attribute_name.SourceAttributes.y}",
    "ClassInstanceAttribute{via_attribute_name.SourceAttributes.z}",
    "Function{pysa._test_sink}", "Method{_random.Random.random}",
    "Method{builtins.float.__gt__}"
  ],
  "Function{via_attribute_name.test_source_attribute_x}": [
    "ClassInstanceAttribute{via_attribute_name.SourceAttributes.x}",
    "Function{pysa._test_sink}"
  ],
  "Function{via_attribute_name.test_source_attribute_y}": [
    "ClassInstanceAttribute{via_attribute_name.SourceAttributes.y}",
    "Function{pysa._test_sink}"
  ],
  "Function{via_attribute_name.test_source_attribute_z}": [
    "ClassInstanceAttribute{via_attribute_name.SourceAttributes.z}",
    "Function{pysa._test_sink}"
  ],
  "Function{via_attribute_name.test_tito_attribute_join}": [
    "ClassInstanceAttribute{via_attribute_name.TitoAttributes.x}",
    "ClassInstanceAttribute{via_attribute_name.TitoAttributes.y}",
    "ClassInstanceAttribute{via_attribute_name.TitoAttributes.z}",
    "Function{pysa._test_sink}", "Function{pysa._test_source}",
    "Method{_random.Random.random}", "Method{builtins.float.__gt__}",
    "Method{builtins.object.__new__}",
    "Method{via_attribute_name.TitoAttributes.__init__}"
  ],
  "Function{via_attribute_name.test_tito_attribute_model_query_x}": [
    "Function{pysa._test_sink}", "Function{pysa._test_source}",
    "Method{builtins.object.__new__}",
    "Method{via_attribute_name.TitoAttributeModelQuery.__init__}"
  ],
  "Function{via_attribute_name.test_tito_attribute_model_query_y}": [
    "Function{pysa._test_sink}", "Function{pysa._test_source}",
    "Method{builtins.object.__new__}",
    "Method{via_attribute_name.TitoAttributeModelQuery.__init__}"
  ],
  "Function{via_attribute_name.test_tito_attribute_model_query_z}": [
    "Function{pysa._test_sink}", "Function{pysa._test_source}",
    "Method{builtins.object.__new__}",
    "Method{via_attribute_name.TitoAttributeModelQuery.__init__}"
  ],
  "Function{via_attribute_name.test_tito_attribute_x}": [
    "ClassInstanceAttribute{via_attribute_name.TitoAttributes.x}",
    "Function{pysa._test_sink}", "Function{pysa._test_source}",
    "Method{builtins.object.__new__}",
    "Method{via_attribute_name.TitoAttributes.__init__}"
  ],
  "Function{via_attribute_name.test_tito_attribute_y}": [
    "ClassInstanceAttribute{via_attribute_name.TitoAttributes.y}",
    "Function{pysa._test_sink}", "Function{pysa._test_source}",
    "Method{builtins.object.__new__}",
    "Method{via_attribute_name.TitoAttributes.__init__}"
  ],
  "Function{via_attribute_name.test_tito_attribute_z_with_tag}": [
    "ClassInstanceAttribute{via_attribute_name.TitoAttributes.z}",
    "Function{pysa._test_sink}", "Function{pysa._test_source}",
    "Method{builtins.object.__new__}",
    "Method{via_attribute_name.TitoAttributes.__init__}"
  ],
  "Method{via_attribute_name.TitoAttributes.__init__}": [
    "ClassInstanceAttribute{via_attribute_name.TitoAttributes.x}",
    "ClassInstanceAttribute{via_attribute_name.TitoAttributes.y}",
    "ClassInstanceAttribute{via_attribute_name.TitoAttributes.z}"
  ]
}