@generated
Call dependencies
{
  "Function{via_value_of.attach_to_sink}": [ "Function{pysa._test_sink}" ],
  "Function{via_value_of.attach_to_source}": [
    "Function{pysa._test_source}"
  ],
  "Function{via_value_of.meta_named}": [
    "Function{via_value_of.return_via_parameter_name}"
  ],
  "Function{via_value_of.meta_sink_args}": [
    "Function{via_value_of.sink_via_value_of}"
  ],
  "Function{via_value_of.meta_sink_kwargs}": [
    "Function{via_value_of.sink_via_value_of}"
  ],
  "Function{via_value_of.meta_sink_positional_kwargs}": [
    "Function{via_value_of.sink_via_value_of}"
  ],
  "Function{via_value_of.meta_sink}": [
    "Function{via_value_of.sink_via_value_of}"
  ],
  "Function{via_value_of.meta}": [
    "Function{via_value_of.return_via_parameter_name}"
  ],
  "Function{via_value_of.test_args_kwargs_parameter}": [
    "Function{via_value_of.return_via_second_parameter}"
  ],
  "Function{via_value_of.test_args_parameter}": [
    "Function{via_value_of.return_via_second_parameter}"
  ],
  "Function{via_value_of.test_attach_to_sink}": [
    "Function{via_value_of.attach_to_sink}"
  ],
  "Function{via_value_of.test_attach_to_source}": [
    "Function{via_value_of.attach_to_source}"
  ],
  "Function{via_value_of.test_backwards_tito}": [
    "Function{via_value_of.tito}"
  ],
  "Function{via_value_of.test_bool}": [
    "Function{via_value_of.return_via_parameter_name}"
  ],
  "Function{via_value_of.test_enums}": [
    "Function{via_value_of.return_via_parameter_name}"
  ],
  "Function{via_value_of.test_kwargs_parameter}": [
    "Function{via_value_of.return_via_second_parameter}"
  ],
  "Function{via_value_of.test_missing}": [
    "Function{via_value_of.return_via_parameter_name}"
  ],
  "Function{via_value_of.test_named_kwargs_parameter}": [
    "Function{via_value_of.return_via_second_parameter}"
  ],
  "Function{via_value_of.test_numerals}": [
    "Function{via_value_of.return_via_parameter_name}"
  ],
  "Function{via_value_of.test_positional_kwargs_parameter}": [
    "Function{via_value_of.return_via_second_parameter}"
  ],
  "Function{via_value_of.test_return_including_name}": [
    "Function{via_value_of.return_including_name}"
  ],
  "Function{via_value_of.test_return_second_parameter_keyword}": [
    "Function{via_value_of.return_via_second_parameter}"
  ],
  "Function{via_value_of.test_return_second_parameter}": [
    "Function{via_value_of.return_via_second_parameter}"
  ],
  "Function{via_value_of.test_return_via_keyword_only}": [
    "Function{via_value_of.return_via_keyword_only}"
  ],
  "Function{via_value_of.test_sinks_do_not_propagate}": [
    "Function{via_value_of.meta_sink}"
  ],
  "Function{via_value_of.test_sink}": [
    "Function{via_value_of.sink_via_value_of}"
  ],
  "Function{via_value_of.test_string_literals}": [
    "Function{via_value_of.return_via_parameter_name}"
  ],
  "Function{via_value_of.test_tito}": [
    "Function{pysa._test_source}", "Function{via_value_of.tito}"
  ],
  "Function{via_value_of.test_unknown_named_args_kwargs}": [
    "Function{via_value_of.return_via_second_parameter}"
  ],
  "Function{via_value_of.test_unknown_named_args}": [
    "Function{via_value_of.return_via_second_parameter}"
  ],
  "Function{via_value_of.test_unknown_named_kwargs}": [
    "Function{via_value_of.return_via_second_parameter}"
  ],
  "Function{via_value_of.test_unknown_positional_args}": [
    "Function{via_value_of.return_via_second_parameter}"
  ],
  "Function{via_value_of.test_unknown_positional_kwargs}": [
    "Function{via_value_of.return_via_second_parameter}"
  ],
  "Function{via_value_of.test_unknown_positional_named_args1}": [
    "Function{via_value_of.return_via_second_parameter}"
  ],
  "Function{via_value_of.test_unknown_positional_named_args2}": [
    "Function{via_value_of.return_via_second_parameter}"
  ],
  "Function{via_value_of.test_unknown_positional_named_args_kwargs1}": [
    "Function{via_value_of.return_via_second_parameter}"
  ],
  "Function{via_value_of.test_unknown_positional_named_kwargs1}": [
    "Function{via_value_of.return_via_second_parameter}"
  ],
  "Function{via_value_of.test_unknown_positional_named_kwargs2}": [
    "Function{via_value_of.return_via_second_parameter}"
  ],
  "Function{via_value_of.test_via_value_of_does_not_propagate}": [
    "Function{via_value_of.meta}"
  ]
}